#!/usr/bin/env bash
set -euo pipefail

# Use CLAUDE_PROJECT_DIR if set (Claude Code provides it), else fall back to cwd
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$PROJECT_DIR"

CHECKPOINT_DIR=".claude/checkpoints"
mkdir -p "$CHECKPOINT_DIR"

TS=$(date -u +%Y%m%dT%H%M%SZ)
LATEST="$CHECKPOINT_DIR/LATEST.md"
TIMESTAMPED="$CHECKPOINT_DIR/$TS.md"

{
  echo "# Pre-compact checkpoint — $TS"
  echo
  echo "## Git state"
  echo
  echo "- **Branch:** \`$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "(detached)")\`"
  echo "- **HEAD:** \`$(git rev-parse --short HEAD 2>/dev/null || echo "?")\` — $(git log -1 --pretty=%s 2>/dev/null || echo "?")"
  echo
  echo "### Last 15 commits on current branch"
  echo
  echo '```'
  git log --oneline -15 2>/dev/null || echo "(no git history)"
  echo '```'
  echo
  echo "### Working tree"
  echo
  echo '```'
  git status --short 2>/dev/null || echo "(no working tree)"
  echo '```'
  echo
  echo "## Open PRs (Sharko)"
  echo
  if command -v gh >/dev/null 2>&1; then
    gh pr list --json number,title,headRefName,isDraft,state 2>/dev/null \
      | jq -r '.[] | "- #\(.number) **\(.title)** (`\(.headRefName)`)\(if .isDraft then " [draft]" else "" end) [\(.state)]"' \
      || echo "_gh CLI ran but returned no PRs (or failed)._"
  else
    echo "_gh CLI not available._"
  fi
  echo
  echo "## Recent tags"
  echo
  echo '```'
  git tag --sort=-creatordate 2>/dev/null | head -10 || echo "(no tags)"
  echo '```'
  echo
  echo "## Maintainer-curated session notes"
  echo
  if [ -f "$CHECKPOINT_DIR/SESSION-NOTES.md" ]; then
    cat "$CHECKPOINT_DIR/SESSION-NOTES.md"
  else
    echo "_No SESSION-NOTES.md present. Update \`$CHECKPOINT_DIR/SESSION-NOTES.md\` with current decisions, in-flight bundle, last test image tag, what's next._"
  fi
  echo
  echo "---"
  echo "_Auto-generated by .claude/hooks/pre-compact.sh on $(date -u). Conversation transcript JSONL is in ~/.claude/projects/<repo-hash>/<session-id>.jsonl if you need full history._"
} > "$LATEST"

cp "$LATEST" "$TIMESTAMPED"

# Keep only the most recent 10 timestamped checkpoints to bound disk use
cd "$CHECKPOINT_DIR"
ls -t [0-9]*.md 2>/dev/null | tail -n +11 | xargs -I{} rm -f {} 2>/dev/null || true
