"""MkDocs build hook: copy the generated OpenAPI spec into the built site.

Why this exists
---------------
The authoritative OpenAPI spec is generated by ``swag`` and lives at
``docs/swagger/swagger.json`` — which is OUTSIDE the MkDocs ``docs_dir``
(``docs/site``). A CI gate ("Swagger Up To Date") keeps that file in sync with
the running server, so it is the single source of truth.

If we committed a second copy of the spec inside ``docs/site`` it could silently
drift from the generated one. Instead, this hook copies the generated spec into
the built site at ``<site_dir>/api/openapi.json`` at the end of every build. The
``api/reference.md`` page then loads ``../openapi.json`` and renders it with
Redoc, so the published API reference always matches the generated spec with no
committed duplicate to maintain.

Pure stdlib — adds no pip dependency, so it cannot break the RTD build.
"""

import json
import logging
import os
import shutil

log = logging.getLogger("mkdocs")


def on_post_build(config, **kwargs):
    """Copy docs/swagger/swagger.json into <site_dir>/api/openapi.json."""
    # config['config_file_path'] is the absolute path to mkdocs.yml.
    repo_root = os.path.dirname(os.path.abspath(config["config_file_path"]))
    spec_src = os.path.join(repo_root, "docs", "swagger", "swagger.json")

    if not os.path.isfile(spec_src):
        log.warning(
            "copy_openapi: spec not found at %s; API reference page will be empty",
            spec_src,
        )
        return

    # Sanity-check it is valid JSON before publishing it.
    with open(spec_src, "r", encoding="utf-8") as fh:
        json.load(fh)

    dest_dir = os.path.join(config["site_dir"], "api")
    os.makedirs(dest_dir, exist_ok=True)
    spec_dest = os.path.join(dest_dir, "openapi.json")
    shutil.copyfile(spec_src, spec_dest)

    log.info("copy_openapi: copied %s -> %s", spec_src, spec_dest)
