package orchestrator

import (
	"context"
	"fmt"
	"log/slog"
	"path"

	"github.com/MoranWeissman/sharko/internal/gitops"
	"github.com/MoranWeissman/sharko/internal/models"
)

// DisableAddon disables a specific addon on a cluster with configurable cleanup.
//
// Cleanup scopes:
//   - "all" (default): update values file (set addon=false) + update managed-clusters.yaml
//     (set label to disabled) via PR; after merge, delete addon secrets from remote.
//   - "labels": same Git changes, but skip remote addon secret deletion.
//   - "none": only update the values file (labels and secrets unchanged).
//
// Steps:
//  1. Validate input and confirmation.
//  2. Update values file (set addon to false).
//  3. Update managed-clusters.yaml (set addon label to disabled) — unless cleanup=none.
//  4. Create single PR with both changes.
//  5. If cleanup=all, delete addon secrets from remote cluster.
func (o *Orchestrator) DisableAddon(ctx context.Context, req DisableAddonRequest) (*DisableAddonResult, error) {
	if req.Cluster == "" {
		return nil, fmt.Errorf("cluster name is required")
	}
	if req.Addon == "" {
		return nil, fmt.Errorf("addon name is required")
	}

	// Normalize cleanup scope.
	cleanup := req.Cleanup
	if cleanup == "" {
		cleanup = "all"
	}
	if cleanup != "all" && cleanup != "labels" && cleanup != "none" {
		return nil, fmt.Errorf("invalid cleanup scope %q: must be all, labels, or none", cleanup)
	}

	result := &DisableAddonResult{
		Cluster: req.Cluster,
		Addon:   req.Addon,
		Cleanup: cleanup,
	}

	valuesPath := path.Join(o.paths.ClusterValues, req.Cluster+".yaml")
	clusterAddonsPath := o.paths.ManagedClusters
	if clusterAddonsPath == "" {
		clusterAddonsPath = "configuration/managed-clusters.yaml"
	}

	// Dry-run exit point.
	if req.DryRun {
		filePreviews := []FilePreview{
			{Path: valuesPath, Action: "update"},
		}
		if cleanup != "none" {
			filePreviews = append(filePreviews, FilePreview{Path: clusterAddonsPath, Action: "update"})
		}
		prTitle := fmt.Sprintf("%s disable addon %s on cluster %s", o.gitops.CommitPrefix, req.Addon, req.Cluster)

		var secretsToDelete []string
		if cleanup == "all" {
			if def, ok := o.secretDefs[req.Addon]; ok {
				secretsToDelete = []string{def.SecretName}
			}
		}

		result.Status = "success"
		result.DryRun = &DryRunResult{
			FilesToWrite:    filePreviews,
			PRTitle:         prTitle,
			SecretsToCreate: secretsToDelete,
		}
		return result, nil
	}

	// Require confirmation.
	if !req.Yes {
		return nil, fmt.Errorf("confirmation required: set yes: true in request body")
	}

	var steps []string
	files := make(map[string][]byte)

	// Step 1: Read and update the cluster values file — set the addon to false.
	existingValues, valuesErr := o.git.GetFileContent(ctx, valuesPath, o.gitops.BaseBranch)
	if valuesErr != nil {
		return nil, fmt.Errorf("reading values file for cluster %q: %w", req.Cluster, valuesErr)
	}

	// Read current addons from managed-clusters.yaml to get the full addon map.
	// Then set the target addon to false and regenerate the values file.
	clusterAddonsData, _ := o.git.GetFileContent(ctx, clusterAddonsPath, o.gitops.BaseBranch)

	// Parse existing values to extract current addons state, then override the target addon.
	// Since values files are generated by Sharko, we reconstruct from managed-clusters.yaml
	// labels if possible, or fall back to a minimal update.
	addons := o.extractAddonsFromValues(existingValues, req.Addon)

	var catalog []models.AddonCatalogEntry
	catalogData, catalogErr := o.git.GetFileContent(ctx, "configuration/addons-catalog.yaml", o.gitops.BaseBranch)
	if catalogErr == nil && catalogData != nil {
		catalog, _ = parseAddonsCatalog(catalogData)
	}

	updatedValues := generateClusterValues(req.Cluster, "", addons, catalog)
	files[valuesPath] = updatedValues
	steps = append(steps, "update_values_file")

	// Step 2: Update managed-clusters.yaml — set addon label to "disabled".
	if cleanup != "none" && clusterAddonsData != nil {
		updatedClusterAddons, labelErr := gitops.DisableAddonLabel(clusterAddonsData, req.Cluster, req.Addon)
		if labelErr != nil {
			slog.Warn("failed to disable addon label in managed-clusters.yaml",
				"cluster", req.Cluster, "addon", req.Addon, "error", labelErr)
		} else {
			files[clusterAddonsPath] = updatedClusterAddons
			steps = append(steps, "update_addon_label")
		}
	}

	// Step 3: Create PR with combined changes.
	gitResult, gitErr := o.commitChanges(ctx, files, nil, fmt.Sprintf("disable addon %s on cluster %s", req.Addon, req.Cluster))
	if gitErr != nil {
		if gitResult != nil {
			result.Status = "partial"
			result.CompletedSteps = steps
			result.FailedStep = "pr_merge"
			result.Error = gitErr.Error()
			result.Message = fmt.Sprintf("PR created but merge failed: %s", gitResult.PRUrl)
			result.Git = gitResult
			return result, nil
		}
		result.Status = "failed"
		result.CompletedSteps = steps
		result.FailedStep = "git_commit"
		result.Error = gitErr.Error()
		result.Message = "Git commit failed while disabling addon"
		return result, nil
	}
	result.Git = gitResult
	steps = append(steps, "git_commit")

	// Step 4: If cleanup=all, delete addon secrets from remote cluster (best-effort).
	if cleanup == "all" && o.credProvider != nil {
		creds, credErr := o.credProvider.GetCredentials(req.Cluster)
		if credErr == nil {
			disabledAddons := map[string]bool{req.Addon: false}
			deleted, _ := o.deleteAddonSecrets(ctx, creds.Raw, disabledAddons)
			if len(deleted) > 0 {
				steps = append(steps, "delete_remote_secrets")
			}
		} else {
			slog.Warn("could not fetch credentials for remote secret cleanup",
				"cluster", req.Cluster, "addon", req.Addon, "error", credErr)
		}
	}

	result.Status = "success"
	result.CompletedSteps = steps
	return result, nil
}

// EnableAddon enables a specific addon on a cluster.
//
// Steps:
//  1. Validate input and confirmation.
//  2. Update values file (set addon to true).
//  3. Update managed-clusters.yaml (set addon label to enabled).
//  4. Create single PR with both changes.
//  5. If the cluster has a credential provider, create addon secrets on remote cluster (best-effort).
func (o *Orchestrator) EnableAddon(ctx context.Context, req EnableAddonRequest) (*EnableAddonResult, error) {
	if req.Cluster == "" {
		return nil, fmt.Errorf("cluster name is required")
	}
	if req.Addon == "" {
		return nil, fmt.Errorf("addon name is required")
	}

	result := &EnableAddonResult{
		Cluster: req.Cluster,
		Addon:   req.Addon,
	}

	valuesPath := path.Join(o.paths.ClusterValues, req.Cluster+".yaml")
	clusterAddonsPath := o.paths.ManagedClusters
	if clusterAddonsPath == "" {
		clusterAddonsPath = "configuration/managed-clusters.yaml"
	}

	// Dry-run exit point.
	if req.DryRun {
		filePreviews := []FilePreview{
			{Path: valuesPath, Action: "update"},
			{Path: clusterAddonsPath, Action: "update"},
		}
		prTitle := fmt.Sprintf("%s enable addon %s on cluster %s", o.gitops.CommitPrefix, req.Addon, req.Cluster)

		var secretsToCreate []string
		if def, ok := o.secretDefs[req.Addon]; ok {
			secretsToCreate = []string{def.SecretName}
		}

		result.Status = "success"
		result.DryRun = &DryRunResult{
			FilesToWrite:    filePreviews,
			PRTitle:         prTitle,
			SecretsToCreate: secretsToCreate,
		}
		return result, nil
	}

	// Require confirmation.
	if !req.Yes {
		return nil, fmt.Errorf("confirmation required: set yes: true in request body")
	}

	var steps []string
	files := make(map[string][]byte)

	// Step 1: Read and update the cluster values file — set the addon to true.
	existingValues, valuesErr := o.git.GetFileContent(ctx, valuesPath, o.gitops.BaseBranch)
	if valuesErr != nil {
		return nil, fmt.Errorf("reading values file for cluster %q: %w", req.Cluster, valuesErr)
	}

	// Read current addons from managed-clusters.yaml to get the full addon map.
	clusterAddonsData, _ := o.git.GetFileContent(ctx, clusterAddonsPath, o.gitops.BaseBranch)

	// Parse existing values and set the target addon to true.
	addons := o.extractAddonsFromValuesForEnable(existingValues, req.Addon)

	var catalog []models.AddonCatalogEntry
	catalogData, catalogErr := o.git.GetFileContent(ctx, "configuration/addons-catalog.yaml", o.gitops.BaseBranch)
	if catalogErr == nil && catalogData != nil {
		catalog, _ = parseAddonsCatalog(catalogData)
	}

	updatedValues := generateClusterValues(req.Cluster, "", addons, catalog)
	files[valuesPath] = updatedValues
	steps = append(steps, "update_values_file")

	// Step 2: Update managed-clusters.yaml — set addon label to "enabled".
	if clusterAddonsData != nil {
		updatedClusterAddons, labelErr := gitops.EnableAddonLabel(clusterAddonsData, req.Cluster, req.Addon)
		if labelErr != nil {
			slog.Warn("failed to enable addon label in managed-clusters.yaml",
				"cluster", req.Cluster, "addon", req.Addon, "error", labelErr)
		} else {
			files[clusterAddonsPath] = updatedClusterAddons
			steps = append(steps, "update_addon_label")
		}
	}

	// Step 3: Create PR with combined changes.
	gitResult, gitErr := o.commitChanges(ctx, files, nil, fmt.Sprintf("enable addon %s on cluster %s", req.Addon, req.Cluster))
	if gitErr != nil {
		if gitResult != nil {
			result.Status = "partial"
			result.CompletedSteps = steps
			result.FailedStep = "pr_merge"
			result.Error = gitErr.Error()
			result.Message = fmt.Sprintf("PR created but merge failed: %s", gitResult.PRUrl)
			result.Git = gitResult
			return result, nil
		}
		result.Status = "failed"
		result.CompletedSteps = steps
		result.FailedStep = "git_commit"
		result.Error = gitErr.Error()
		result.Message = "Git commit failed while enabling addon"
		return result, nil
	}
	result.Git = gitResult
	steps = append(steps, "git_commit")

	// Step 4: Create addon secrets on remote cluster (best-effort).
	if o.credProvider != nil {
		creds, credErr := o.credProvider.GetCredentials(req.Cluster)
		if credErr == nil {
			enabledAddons := map[string]bool{req.Addon: true}
			secretRes, _ := o.createAddonSecrets(ctx, creds.Raw, enabledAddons)
			if secretRes != nil && len(secretRes.Created) > 0 {
				steps = append(steps, "create_remote_secrets")
			}
		} else {
			slog.Warn("could not fetch credentials for remote secret creation",
				"cluster", req.Cluster, "addon", req.Addon, "error", credErr)
		}
	}

	result.Status = "success"
	result.CompletedSteps = steps
	return result, nil
}

// extractAddonsFromValuesForEnable parses a cluster values file to extract the current addon
// states, then sets the target addon to true.
func (o *Orchestrator) extractAddonsFromValuesForEnable(valuesData []byte, enableAddon string) map[string]bool {
	addons := o.extractAddonsFromValues(valuesData, enableAddon)
	// Override: set the target addon to true.
	addons[enableAddon] = true
	return addons
}

// extractAddonsFromValues parses a cluster values file to extract the current addon
// states, then sets the target addon to false. This is a best-effort parser that
// looks for "<addon>:\n  enabled: true/false" patterns.
func (o *Orchestrator) extractAddonsFromValues(valuesData []byte, disableAddon string) map[string]bool {
	addons := make(map[string]bool)

	// Parse simple YAML pattern: "addonName:\n  enabled: true/false"
	lines := splitLines(string(valuesData))
	for i := 0; i < len(lines)-1; i++ {
		line := lines[i]
		nextLine := lines[i+1]

		// Skip indented lines and comments.
		if len(line) == 0 || line[0] == ' ' || line[0] == '#' || line[0] == '_' {
			continue
		}

		// Check if this looks like "addonName:"
		if len(line) > 1 && line[len(line)-1] == ':' {
			name := line[:len(line)-1]
			if name == "clusterGlobalValues" {
				continue
			}
			// Check if next line is "  enabled: true/false"
			trimmed := trimSpaces(nextLine)
			if trimmed == "enabled: true" {
				addons[name] = true
			} else if trimmed == "enabled: false" {
				addons[name] = false
			}
		}
	}

	// Override the target addon.
	addons[disableAddon] = false

	return addons
}

// splitLines splits a string into lines without importing strings.
func splitLines(s string) []string {
	var lines []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			lines = append(lines, s[start:i])
			start = i + 1
		}
	}
	if start < len(s) {
		lines = append(lines, s[start:])
	}
	return lines
}

// trimSpaces removes leading and trailing whitespace.
func trimSpaces(s string) string {
	start := 0
	for start < len(s) && (s[start] == ' ' || s[start] == '\t') {
		start++
	}
	end := len(s)
	for end > start && (s[end-1] == ' ' || s[end-1] == '\t' || s[end-1] == '\r') {
		end--
	}
	return s[start:end]
}
