// Package orchestrator — smart-values heuristic + splitter tests
// (Epic V121-6 Stories 6.1, 6.2, 6.3).

package orchestrator

import (
	"strings"
	"testing"
	"time"
)

// TestClassifyClusterSpecificFields_PositiveAndNegative pins each
// pattern in clusterSpecificPatterns to a positive case (a path that
// must match) and a representative negative case (a path that must NOT
// match). The acceptance criterion for Story V121-6.1 requires both per
// pattern.
func TestClassifyClusterSpecificFields_PositiveAndNegative(t *testing.T) {
	cases := []struct {
		name        string
		yaml        string
		mustHit     []string // paths required to be classified cluster-specific
		mustNotHit  []string // paths that must NOT be classified cluster-specific
	}{
		{
			name: "ingress host + replicaCount + resources",
			yaml: `
ingress:
  enabled: true
  host: example.com
replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 128Mi
image:
  repository: ghcr.io/example/app
`,
			mustHit:    []string{"ingress.host", "replicaCount", "resources.requests.cpu", "resources.requests.memory"},
			mustNotHit: []string{"image.repository"},
		},
		{
			name: "tls + persistence + storageClass + nodeSelector",
			yaml: `
tls:
  enabled: true
persistence:
  size: 10Gi
storageClass: gp3
nodeSelector:
  kubernetes.io/os: linux
`,
			mustHit: []string{"tls.enabled", "persistence.size", "storageClass", "nodeSelector"},
			mustNotHit: []string{},
		},
		{
			name: "domain endpoint url hostname",
			yaml: `
externalDatabase:
  host: db.example.com
  url: postgres://x
api:
  endpoint: https://example.com/api
domain: example.com
`,
			mustHit:    []string{"externalDatabase.host", "externalDatabase.url", "api.endpoint", "domain"},
			mustNotHit: []string{},
		},
		{
			name: "tolerations affinity externalSecret existingSecret region environment clusterName",
			yaml: `
tolerations:
  - key: dedicated
affinity:
  podAntiAffinity: {}
externalSecret:
  refreshInterval: 1h
existingSecret: my-secret
secretName: foo
clusterName: prod-eu
region: us-east-1
environment: production
`,
			mustHit: []string{
				"tolerations", "affinity",
				"externalSecret.refreshInterval", "existingSecret", "secretName",
				"clusterName", "region", "environment",
			},
			mustNotHit: []string{},
		},
		{
			name: "serviceAccount.annotations.* (IRSA)",
			yaml: `
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/foo
`,
			mustHit:    []string{"serviceAccount.annotations.eks.amazonaws.com/role-arn"},
			mustNotHit: []string{"serviceAccount.create"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := ClassifyClusterSpecificFields([]byte(tc.yaml))
			gotSet := map[string]bool{}
			for _, g := range got {
				gotSet[g] = true
			}
			for _, want := range tc.mustHit {
				if !gotSet[want] {
					t.Errorf("expected %q to be classified cluster-specific, got %v", want, got)
				}
			}
			for _, no := range tc.mustNotHit {
				if gotSet[no] {
					t.Errorf("path %q must NOT be classified cluster-specific, got %v", no, got)
				}
			}
		})
	}
}

// TestSplitUpstreamValues_GlobalFileShape pins the v1.21 Bundle 5 shape:
// upstream defaults preserved at TOP LEVEL with cluster-specific scalars
// replaced by a commented placeholder, plus a trailing per-cluster template
// block (still wrapped under the addon name because that block is meant to
// be copy-pasted into the per-cluster file).
func TestSplitUpstreamValues_GlobalFileShape(t *testing.T) {
	upstream := []byte(`# Upstream comment
ingress:
  enabled: true
  host: example.com
replicaCount: 2
image:
  repository: ghcr.io/example/app
`)

	out := SplitUpstreamValues(SmartValuesInput{
		AddonName:      "cert-manager",
		Chart:          "cert-manager",
		Version:        "v1.14.4",
		RepoURL:        "https://charts.jetstack.io",
		UpstreamValues: upstream,
	})

	body := string(out.File)

	// Header lines + format-shape comment.
	for _, want := range []string{
		"# Generated by Sharko from cert-manager@v1.14.4 on ",
		"# Chart source: https://charts.jetstack.io",
		"# AI annotation: disabled",
		"# sharko: managed=true",
		"# Helm values for cert-manager",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("expected output to contain %q\n--- output ---\n%s", want, body)
		}
	}

	// CRITICAL: there must NOT be an `<addonName>:` wrap around the body.
	// Lines starting at column 0 with `cert-manager:` are forbidden — the
	// file is meant to be passed directly to Helm via `valueFiles:`.
	for _, line := range strings.Split(body, "\n") {
		if line == "cert-manager:" {
			t.Fatalf("global file must NOT be wrapped under <addon>: at the body root, got:\n%s", body)
		}
	}

	// `ingress.host` becomes a comment placeholder. Indentation now
	// matches the upstream (no extra two-space wrap), so `# host:` is
	// indented exactly two spaces as in the upstream.
	if !strings.Contains(body, "  # host: <cluster-specific>") {
		t.Errorf("expected commented host placeholder at upstream indent, got:\n%s", body)
	}
	// `replicaCount` becomes a comment placeholder at column 0 (top-level
	// scalar in the chart values).
	if !strings.Contains(body, "\n# replicaCount: <cluster-specific>") {
		t.Errorf("expected top-level commented replicaCount placeholder, got:\n%s", body)
	}
	// `image.repository` survives at upstream indent.
	if !strings.Contains(body, "  repository: ghcr.io/example/app") {
		t.Errorf("expected image.repository to survive at upstream indent, got:\n%s", body)
	}
	// Upstream comment passed through verbatim.
	if !strings.Contains(body, "# Upstream comment") {
		t.Errorf("expected upstream comment to be preserved, got:\n%s", body)
	}
	// Template block at the bottom — still wrapped under the addon name
	// because that block is the per-cluster overrides template.
	if !strings.Contains(body, "# --- per-cluster overrides template ---") {
		t.Errorf("missing template block marker, got:\n%s", body)
	}
	if !strings.Contains(body, "# cert-manager:") {
		t.Errorf("missing addon header inside template block, got:\n%s", body)
	}
	// Template includes the cluster-specific leaves we found.
	if !strings.Contains(body, `"ingress.host": <set per cluster>`) {
		t.Errorf("missing ingress.host template line, got:\n%s", body)
	}
	if !strings.Contains(body, "replicaCount: <set per cluster>") {
		t.Errorf("missing replicaCount template line, got:\n%s", body)
	}

	// ClusterSpecificPaths matches what we found.
	if len(out.ClusterSpecificPaths) == 0 {
		t.Errorf("expected at least one cluster-specific path, got empty")
	}
}

// TestSplitUpstreamValues_NoClusterSpecific exercises the path where the
// chart's values.yaml has no cluster-specific fields. The template block
// should still render with the "no fields detected" hint.
func TestSplitUpstreamValues_NoClusterSpecific(t *testing.T) {
	upstream := []byte(`image:
  repository: ghcr.io/example/app
  tag: v1
`)
	out := SplitUpstreamValues(SmartValuesInput{
		AddonName:      "noop",
		Chart:          "noop",
		Version:        "v0.0.1",
		RepoURL:        "https://charts.example.com",
		UpstreamValues: upstream,
	})
	body := string(out.File)
	if !strings.Contains(body, "(no cluster-specific fields detected") {
		t.Errorf("expected the no-fields template hint, got:\n%s", body)
	}
	if len(out.ClusterSpecificPaths) != 0 {
		t.Errorf("expected zero cluster-specific paths, got %v", out.ClusterSpecificPaths)
	}
}

// TestWriteAndParseSmartValuesHeader_Roundtrip ensures the header can
// round-trip through the writer + parser, including the optional
// per-addon AI opt-out directive (Story V121-6.3 + Story V121-7.3).
func TestWriteAndParseSmartValuesHeader_Roundtrip(t *testing.T) {
	now := time.Date(2026, 4, 17, 12, 0, 0, 0, time.UTC)

	for _, tc := range []struct {
		name string
		h    SmartValuesHeader
	}{
		{
			name: "ai annotated, no opt-out",
			h: SmartValuesHeader{
				Chart: "cert-manager", Version: "v1.14.4",
				RepoURL: "https://charts.jetstack.io",
				AIAnnotated: true, Now: now,
			},
		},
		{
			name: "ai disabled with per-addon opt-out",
			h: SmartValuesHeader{
				Chart: "external-secrets", Version: "v0.10.0",
				RepoURL: "https://charts.external-secrets.io",
				AIAnnotated: false, AIOptOut: true, Now: now,
			},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			out := WriteSmartValuesHeader(tc.h)
			parsed := ParseSmartValuesHeader([]byte(out))
			if parsed.Chart != tc.h.Chart {
				t.Errorf("chart: want %q got %q", tc.h.Chart, parsed.Chart)
			}
			if parsed.Version != tc.h.Version {
				t.Errorf("version: want %q got %q", tc.h.Version, parsed.Version)
			}
			if parsed.RepoURL != tc.h.RepoURL {
				t.Errorf("repo: want %q got %q", tc.h.RepoURL, parsed.RepoURL)
			}
			if parsed.AIAnnotated != tc.h.AIAnnotated {
				t.Errorf("AIAnnotated: want %v got %v", tc.h.AIAnnotated, parsed.AIAnnotated)
			}
			if parsed.AIOptOut != tc.h.AIOptOut {
				t.Errorf("AIOptOut: want %v got %v", tc.h.AIOptOut, parsed.AIOptOut)
			}
			if !parsed.Managed {
				t.Errorf("expected Managed=true, got false")
			}
		})
	}
}

// TestParseSmartValuesHeader_LegacyFile checks that a values file with
// no Sharko header parses to a zero ParsedHeader (Managed=false). The
// version-mismatch banner must NOT fire on legacy files.
func TestParseSmartValuesHeader_LegacyFile(t *testing.T) {
	legacy := []byte(`# A user comment
cert-manager:
  enabled: true
  replicaCount: 2
`)
	h := ParseSmartValuesHeader(legacy)
	if h.Managed {
		t.Errorf("legacy file must parse to Managed=false, got true")
	}
	if h.Version != "" {
		t.Errorf("legacy file must parse to empty Version, got %q", h.Version)
	}
}

// TestVersionMismatch_All exercises the four cases the banner gates on.
func TestVersionMismatch_All(t *testing.T) {
	managed := ParsedHeader{Chart: "cert-manager", Version: "v1.15.1", Managed: true}
	unmanaged := ParsedHeader{Chart: "cert-manager", Version: "v1.15.1", Managed: false}

	cases := []struct {
		name       string
		catalog    string
		header     ParsedHeader
		wantCat    string
		wantValues string
	}{
		{name: "mismatch with managed=true", catalog: "v1.16.2", header: managed, wantCat: "v1.16.2", wantValues: "v1.15.1"},
		{name: "match suppresses banner", catalog: "v1.15.1", header: managed, wantCat: "", wantValues: ""},
		{name: "no managed=true header — banner suppressed", catalog: "v1.16.2", header: unmanaged, wantCat: "", wantValues: ""},
		{name: "v-prefix vs no-prefix counted as match", catalog: "1.15.1", header: managed, wantCat: "", wantValues: ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cat, val := VersionMismatch(tc.catalog, tc.header)
			if cat != tc.wantCat {
				t.Errorf("catalog: want %q got %q", tc.wantCat, cat)
			}
			if val != tc.wantValues {
				t.Errorf("values: want %q got %q", tc.wantValues, val)
			}
		})
	}
}

// TestExtractClusterTemplateLeaves verifies the parser used by Story
// V121-6.6 can pull leaves out of a SplitUpstreamValues output.
func TestExtractClusterTemplateLeaves(t *testing.T) {
	out := SplitUpstreamValues(SmartValuesInput{
		AddonName: "cert-manager",
		Chart:     "cert-manager",
		Version:   "v1.14.4",
		RepoURL:   "https://charts.jetstack.io",
		UpstreamValues: []byte(`ingress:
  host: example.com
replicaCount: 2
`),
	})

	leaves := ExtractClusterTemplateLeaves(out.File, "cert-manager")
	if len(leaves) == 0 {
		t.Fatal("expected leaves from template block")
	}
	gotSet := map[string]bool{}
	for _, l := range leaves {
		gotSet[l] = true
	}
	for _, want := range []string{"ingress.host", "replicaCount"} {
		if !gotSet[want] {
			t.Errorf("expected leaf %q in extracted set, got %v", want, leaves)
		}
	}
}

// TestExtractClusterTemplateLeaves_LegacyFileNoMarker returns nil for
// values files written before V121-6 (no marker line).
func TestExtractClusterTemplateLeaves_LegacyFileNoMarker(t *testing.T) {
	legacy := []byte(`cert-manager:
  enabled: true
`)
	if got := ExtractClusterTemplateLeaves(legacy, "cert-manager"); len(got) != 0 {
		t.Errorf("legacy file must yield no leaves, got %v", got)
	}
}

// TestInjectTemplateLeaves_FreshStanza creates a brand-new addon stanza
// with the seeded fields. Other top-level keys are preserved.
func TestInjectTemplateLeaves_FreshStanza(t *testing.T) {
	cluster := []byte(`clusterGlobalValues:
  region: us-east-1
external-secrets:
  enabled: true
`)
	out, err := injectTemplateLeaves(cluster, "cert-manager", []string{"ingress.host", "replicaCount"})
	if err != nil {
		t.Fatalf("inject: %v", err)
	}
	body := string(out)
	for _, want := range []string{
		"clusterGlobalValues:", // preserved
		"external-secrets:",    // preserved
		"cert-manager:",        // added
		"enabled: true",        // EnableAddon added enabled flag
		"ingress:",
		"host: <set per cluster>",
		"replicaCount: <set per cluster>",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("expected %q in injected output:\n%s", want, body)
		}
	}
}

// TestInjectTemplateLeaves_ExistingValuesPreserved — a leaf that already
// has a user value must not be overwritten by the placeholder.
func TestInjectTemplateLeaves_ExistingValuesPreserved(t *testing.T) {
	cluster := []byte(`cert-manager:
  enabled: true
  ingress:
    host: my-real-host
`)
	out, err := injectTemplateLeaves(cluster, "cert-manager", []string{"ingress.host", "replicaCount"})
	if err != nil {
		t.Fatalf("inject: %v", err)
	}
	body := string(out)
	if !strings.Contains(body, "host: my-real-host") {
		t.Errorf("user-authored host was clobbered, got:\n%s", body)
	}
	if !strings.Contains(body, "replicaCount: <set per cluster>") {
		t.Errorf("expected new replicaCount leaf to be added, got:\n%s", body)
	}
}

// TestHasAddonStanzaUserFields covers the three cases the seeder uses to
// decide whether to skip seeding.
func TestHasAddonStanzaUserFields(t *testing.T) {
	cases := []struct {
		name string
		yaml string
		want bool
	}{
		{name: "no stanza at all", yaml: `clusterGlobalValues: {}`, want: false},
		{name: "stanza with only enabled", yaml: `cert-manager:
  enabled: true
`, want: false},
		{name: "stanza with user fields", yaml: `cert-manager:
  enabled: true
  ingress:
    host: foo
`, want: true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := hasAddonStanzaUserFields([]byte(tc.yaml), "cert-manager")
			if got != tc.want {
				t.Errorf("want %v got %v", tc.want, got)
			}
		})
	}
}

// TestUnwrapChartNameRoot covers the v1.21 QA Bundle 4 Fix #6 — Velero
// double-wrap fix. Ensures we detect a chart-name-rooted upstream values.yaml
// and unwrap one level so the smart-values writer doesn't produce
// `velero:\n  velero:\n    …`.
func TestUnwrapChartNameRoot(t *testing.T) {
	t.Run("velero-style root key matching addon name is unwrapped", func(t *testing.T) {
		input := []byte(`# Default values for velero.
velero:
  configuration:
    backupStorageLocation: []
  resources:
    requests:
      cpu: 500m
`)
		out := unwrapChartNameRoot(input, "velero", "velero")
		body := string(out)
		if strings.Contains(body, "velero:") && strings.Index(body, "velero:") > 0 {
			// Comment header may still mention "velero" — fine. The
			// failure case is the actual `velero:` map line surviving.
		}
		// First non-comment line should be `configuration:` at indent 0.
		for _, line := range strings.Split(body, "\n") {
			trim := strings.TrimSpace(line)
			if trim == "" || strings.HasPrefix(trim, "#") {
				continue
			}
			if !strings.HasPrefix(line, "configuration:") {
				t.Fatalf("expected first non-comment line to be 'configuration:' at indent 0, got %q\nfull body:\n%s", line, body)
			}
			break
		}
		if !strings.Contains(body, "  backupStorageLocation:") {
			t.Errorf("expected backupStorageLocation indented under configuration, got:\n%s", body)
		}
	})

	t.Run("multi-root file is left untouched", func(t *testing.T) {
		input := []byte(`replicaCount: 2
ingress:
  enabled: true
`)
		out := unwrapChartNameRoot(input, "anything", "anything")
		if string(out) != string(input) {
			t.Errorf("multi-root file should be a no-op, got:\n%s", string(out))
		}
	})

	t.Run("root key unrelated to chart is left untouched", func(t *testing.T) {
		input := []byte(`global:
  foo: bar
`)
		out := unwrapChartNameRoot(input, "velero", "velero")
		if string(out) != string(input) {
			t.Errorf("unrelated single-root file should be a no-op, got:\n%s", string(out))
		}
	})
}

// TestSplitUpstreamValues_VeleroDoubleWrapAvoided is the integration-level
// verification that the splitter unwraps a velero-style upstream and emits
// the chart's keys at the top level (no `velero:` wrap anywhere in the body).
//
// v1.21 Bundle 5 (the wrap fix): the global file is now passed directly to
// Helm via `valueFiles:`, so it must NOT have any `<chart>:` or `<addon>:`
// wrap at the body root. The only `velero:` line we tolerate is the
// commented `# velero:` line in the per-cluster template block.
func TestSplitUpstreamValues_VeleroDoubleWrapAvoided(t *testing.T) {
	upstream := []byte(`velero:
  configuration:
    defaultVolumesToFsBackup: false
  metrics:
    enabled: true
  resources:
    requests:
      cpu: 500m
`)
	out := SplitUpstreamValues(SmartValuesInput{
		AddonName:      "velero",
		Chart:          "velero",
		Version:        "12.0.0",
		RepoURL:        "https://vmware-tanzu.github.io/helm-charts",
		UpstreamValues: upstream,
	})
	body := string(out.File)
	// Forbidden: any uncommented `velero:` line at column 0.
	for _, line := range strings.Split(body, "\n") {
		if line == "velero:" {
			t.Fatalf("forbidden uncommented `velero:` root key in body:\n%s", body)
		}
	}
	// Required: `configuration:` lives at column 0 — the chart's own keys
	// are at the document root.
	if !strings.Contains(body, "\nconfiguration:") {
		t.Errorf("expected configuration: at document root, got:\n%s", body)
	}
	// Required: the per-cluster template block keeps the `# velero:`
	// commented header (that block IS namespaced because it lands in the
	// per-cluster file). Resources matched the cluster-specific
	// heuristic, so the template block renders.
	if !strings.Contains(body, "# velero:") {
		t.Errorf("expected per-cluster template to keep commented `# velero:` header, got:\n%s", body)
	}
}

// Use time import to keep imports stable when running this file in isolation.
var _ = time.Now
