// Package orchestrator — generated-file header (Story V121-6.3).
//
// Every file the smart-values layer writes carries a self-describing
// header that downstream code (the version-mismatch banner, the AI
// opt-out machinery) parses to know what state the file is in.
//
// Header format (4 lines, in order):
//
//	# Generated by Sharko from <chart>@<version> on <YYYY-MM-DD>
//	# Chart source: <repoURL>
//	# AI annotation: enabled|disabled
//	# sharko: managed=true
//
// Optional 5th line, only when the user opted out per-addon:
//
//	# sharko: ai-annotate=off
//
// Backwards compatibility: existing values files written before v1.21
// have no header. The version-mismatch banner suppresses itself when
// `sharko: managed=true` is missing, so legacy files keep working.

package orchestrator

import (
	"fmt"
	"strings"
	"time"
)

// SmartValuesHeader carries the values stamped onto every generated file.
// `Now` is overridable for tests; production callers should leave it zero
// and the writer fills in time.Now().UTC().
type SmartValuesHeader struct {
	Chart       string
	Version     string
	RepoURL     string
	AIAnnotated bool
	AIOptOut    bool
	// Now overrides time.Now for deterministic tests. Zero value means
	// "use the wall clock now".
	Now time.Time
}

// WriteSmartValuesHeader returns the header bytes (with trailing newline).
func WriteSmartValuesHeader(h SmartValuesHeader) string {
	now := h.Now
	if now.IsZero() {
		now = time.Now().UTC()
	}
	annotation := "disabled"
	if h.AIAnnotated {
		annotation = "enabled"
	}
	chartRef := h.Chart
	if h.Version != "" {
		chartRef = fmt.Sprintf("%s@%s", h.Chart, h.Version)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by Sharko from %s on %s\n", chartRef, now.Format("2006-01-02"))
	fmt.Fprintf(&b, "# Chart source: %s\n", h.RepoURL)
	fmt.Fprintf(&b, "# AI annotation: %s\n", annotation)
	b.WriteString("# sharko: managed=true\n")
	if h.AIOptOut {
		b.WriteString("# sharko: ai-annotate=off\n")
	}
	return b.String()
}

// ParsedHeader is what ParseSmartValuesHeader returns. Fields are zero
// when the corresponding header line is absent. `Managed` is the truth
// value the version-mismatch banner gates on.
type ParsedHeader struct {
	Chart       string
	Version     string
	RepoURL     string
	AIAnnotated bool
	AIOptOut    bool
	Managed     bool
}

// ParseSmartValuesHeader scans the first ~10 non-blank lines of a values
// file and extracts the smart-values header. Returns a zero-value
// ParsedHeader when no header is present (legacy file). The function
// stops scanning at the first non-comment line so it doesn't accidentally
// pull `# foo: bar` comments from elsewhere in the YAML.
//
// Designed to be cheap — called on every Values-tab GET to compute the
// version-mismatch flag.
func ParseSmartValuesHeader(content []byte) ParsedHeader {
	var h ParsedHeader
	lines := strings.SplitN(string(content), "\n", 30)
	for _, raw := range lines {
		line := strings.TrimSpace(raw)
		if line == "" {
			continue
		}
		if !strings.HasPrefix(line, "#") {
			break
		}
		body := strings.TrimSpace(strings.TrimPrefix(line, "#"))

		switch {
		case strings.HasPrefix(body, "Generated by Sharko from "):
			rest := strings.TrimPrefix(body, "Generated by Sharko from ")
			// Format: "<chart>@<version> on <date>" — split on " on " so the
			// chart name itself can contain dashes etc.
			if idx := strings.Index(rest, " on "); idx > 0 {
				ref := rest[:idx]
				if at := strings.LastIndex(ref, "@"); at > 0 {
					h.Chart = ref[:at]
					h.Version = ref[at+1:]
				} else {
					h.Chart = ref
				}
			}
		case strings.HasPrefix(body, "Chart source:"):
			h.RepoURL = strings.TrimSpace(strings.TrimPrefix(body, "Chart source:"))
		case strings.HasPrefix(body, "AI annotation:"):
			val := strings.TrimSpace(strings.TrimPrefix(body, "AI annotation:"))
			h.AIAnnotated = strings.EqualFold(val, "enabled")
		case strings.HasPrefix(body, "sharko:"):
			rest := strings.TrimSpace(strings.TrimPrefix(body, "sharko:"))
			switch {
			case strings.EqualFold(rest, "managed=true"):
				h.Managed = true
			case strings.EqualFold(rest, "ai-annotate=off"):
				h.AIOptOut = true
			}
		}
	}
	return h
}

// VersionMismatch returns the (catalogVersion, valuesVersion) pair when
// the catalog points at a different chart version than the one stamped
// into the values file's header. Returns ("", "") when there is no
// mismatch (or when the header is missing — legacy files don't get a
// banner). The first return is the catalog (the "should be"), the second
// is the values file (the "is").
func VersionMismatch(catalogVersion string, header ParsedHeader) (string, string) {
	if !header.Managed {
		return "", ""
	}
	if header.Version == "" || catalogVersion == "" {
		return "", ""
	}
	if normalizeVersion(catalogVersion) == normalizeVersion(header.Version) {
		return "", ""
	}
	return catalogVersion, header.Version
}

// normalizeVersion strips a single leading 'v' so that "v1.16.2" and
// "1.16.2" compare equal — Helm chart indices use both conventions and
// users naturally interchange them.
func normalizeVersion(v string) string {
	v = strings.TrimSpace(v)
	return strings.TrimPrefix(v, "v")
}
