package main

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io/fs"
	"log/slog"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/MoranWeissman/sharko/internal/ai"
	"github.com/MoranWeissman/sharko/internal/api"
	"github.com/MoranWeissman/sharko/internal/argosecrets"
	"github.com/MoranWeissman/sharko/internal/audit"
	"github.com/MoranWeissman/sharko/internal/cmstore"
	"github.com/MoranWeissman/sharko/internal/config"
	"github.com/MoranWeissman/sharko/internal/demo"
	"github.com/MoranWeissman/sharko/internal/models"
	"github.com/MoranWeissman/sharko/internal/notifications"
	"github.com/MoranWeissman/sharko/internal/orchestrator"
	"github.com/MoranWeissman/sharko/internal/platform"
	"github.com/MoranWeissman/sharko/internal/providers"
	"github.com/MoranWeissman/sharko/internal/prtracker"
	"github.com/MoranWeissman/sharko/internal/remoteclient"
	"github.com/MoranWeissman/sharko/internal/secrets"
	"github.com/MoranWeissman/sharko/internal/service"
	"github.com/MoranWeissman/sharko/templates"
	"github.com/spf13/cobra"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

func init() {
	serveCmd.Flags().Int("port", 8080, "HTTP server port")
	serveCmd.Flags().String("config", "config.yaml", "Path to config file (local mode)")
	serveCmd.Flags().String("static", "", "Path to static files directory (UI)")
	serveCmd.Flags().Bool("demo", false, "Run with mock backends for QA testing (no external dependencies)")
	rootCmd.AddCommand(serveCmd)
}

// @title Sharko API
// @version 1.0.0
// @description Addon management server for Kubernetes clusters, built on ArgoCD.
// @host localhost:8080
// @BasePath /api/v1
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the Sharko API server",
	RunE: func(cmd *cobra.Command, args []string) error {
		// Configure structured logging from SHARKO_LOG_LEVEL env var (default: info).
		logLevel := getEnvDefault("SHARKO_LOG_LEVEL", "info")
		var level slog.Level
		switch strings.ToLower(logLevel) {
		case "debug":
			level = slog.LevelDebug
		case "warn":
			level = slog.LevelWarn
		case "error":
			level = slog.LevelError
		default:
			level = slog.LevelInfo
		}
		slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: level})))

		port, _ := cmd.Flags().GetInt("port")
		configPath, _ := cmd.Flags().GetString("config")
		staticDir, _ := cmd.Flags().GetString("static")
		demoMode, _ := cmd.Flags().GetBool("demo")

		// Override from env
		if envPort := os.Getenv("SHARKO_PORT"); envPort != "" {
			fmt.Sscanf(envPort, "%d", &port)
		}
		if envConfig := os.Getenv("SHARKO_CONFIG"); envConfig != "" {
			configPath = envConfig
		}
		if envStatic := os.Getenv("SHARKO_STATIC_DIR"); envStatic != "" {
			staticDir = envStatic
		}

		// Load secrets from secrets.env for local development
		loadSecretsEnv("secrets.env")

		// Detect runtime mode
		mode := platform.Detect()
		slog.Info("sharko starting", "mode", mode)

		// Initialize config store
		var store config.Store
		switch mode {
		case platform.ModeKubernetes:
			encKey := os.Getenv("SHARKO_ENCRYPTION_KEY")
			if encKey == "" {
				return fmt.Errorf("SHARKO_ENCRYPTION_KEY is required when running on Kubernetes. " +
					"It is auto-generated by the Helm chart on first install.")
			}
			secretName := os.Getenv("CONNECTION_SECRET_NAME")
			if secretName == "" {
				secretName = "sharko-connections"
			}
			namespace := os.Getenv("SHARKO_NAMESPACE")
			if namespace == "" {
				namespace = "sharko"
			}
			var err error
			store, err = config.NewK8sStore(namespace, secretName, encKey)
			if err != nil {
				return fmt.Errorf("failed to create K8s connection store: %w", err)
			}
			slog.Info("connection config stored in encrypted k8s secret", "namespace", namespace, "secret", secretName)
		default:
			store = config.NewFileStore(configPath)
		}

		// AI configuration — resolve per-provider API key and model
		aiProvider := ai.Provider(os.Getenv("AI_PROVIDER"))
		aiAPIKey := os.Getenv("AI_API_KEY")    // generic fallback
		aiModel := os.Getenv("AI_CLOUD_MODEL") // generic fallback
		aiBaseURL := os.Getenv("AI_BASE_URL")
		aiAuthHeader := os.Getenv("AI_AUTH_HEADER")

		switch aiProvider {
		case ai.ProviderOpenAI:
			if k := os.Getenv("OPENAI_API_KEY"); k != "" {
				aiAPIKey = k
			}
			if m := os.Getenv("OPENAI_MODEL"); m != "" {
				aiModel = m
			}
		case ai.ProviderClaude:
			if k := os.Getenv("CLAUDE_API_KEY"); k != "" {
				aiAPIKey = k
			}
			if m := os.Getenv("CLAUDE_MODEL"); m != "" {
				aiModel = m
			}
		case ai.ProviderGemini:
			if k := os.Getenv("GEMINI_API_KEY"); k != "" {
				aiAPIKey = k
			}
			if m := os.Getenv("GEMINI_MODEL"); m != "" {
				aiModel = m
			}
		case ai.ProviderCustomOpenAI:
			if k := os.Getenv("CUSTOM_OPENAI_API_KEY"); k != "" {
				aiAPIKey = k
			}
			if m := os.Getenv("CUSTOM_OPENAI_MODEL"); m != "" {
				aiModel = m
			}
			if u := os.Getenv("CUSTOM_OPENAI_BASE_URL"); u != "" {
				aiBaseURL = u
			}
			if h := os.Getenv("CUSTOM_OPENAI_AUTH_HEADER"); h != "" {
				aiAuthHeader = h
			}
		}

		aiCfg := ai.Config{
			Provider:      aiProvider,
			OllamaURL:     getEnvDefault("AI_OLLAMA_URL", "http://localhost:11434"),
			OllamaModel:   getEnvDefault("AI_OLLAMA_MODEL", "llama3.2"),
			AgentModel:     os.Getenv("AI_AGENT_MODEL"),
			APIKey:         aiAPIKey,
			CloudModel:     aiModel,
			BaseURL:        aiBaseURL,
			AuthHeader:     aiAuthHeader,
			GitOpsEnabled:  os.Getenv("GITOPS_ACTIONS_ENABLED") == "true",
		}
		if v := os.Getenv("AI_MAX_ITERATIONS"); v != "" {
			fmt.Sscanf(v, "%d", &aiCfg.MaxIterations)
		}
		aiClient := ai.NewClient(aiCfg)
		if aiClient.IsEnabled() {
			model := aiCfg.OllamaModel
			if aiCfg.Provider == ai.ProviderClaude || aiCfg.Provider == ai.ProviderOpenAI || aiCfg.Provider == ai.ProviderGemini {
				model = aiCfg.CloudModel
			}
			slog.Info("ai provider enabled", "provider", aiCfg.Provider, "model", model)
		}

		// Wire up services
		connSvc := service.NewConnectionService(store)
		clusterSvc := service.NewClusterService(getEnvDefault("SHARKO_REPO_PATH_MANAGED_CLUSTERS", "configuration/managed-clusters.yaml"))
		addonSvc := service.NewAddonService(getEnvDefault("SHARKO_REPO_PATH_MANAGED_CLUSTERS", "configuration/managed-clusters.yaml"))
		dashboardSvc := service.NewDashboardService(connSvc, getEnvDefault("SHARKO_REPO_PATH_MANAGED_CLUSTERS", "configuration/managed-clusters.yaml"))
		observabilitySvc := service.NewObservabilityService()
		upgradeSvc := service.NewUpgradeService(aiClient, getEnvDefault("SHARKO_REPO_PATH_MANAGED_CLUSTERS", "configuration/managed-clusters.yaml"))

		// Build server
		srv := api.NewServer(connSvc, clusterSvc, addonSvc, dashboardSvc, observabilitySvc, upgradeSvc, aiClient)
		srv.SetVersion(version)                 // Propagate ldflags-injected version to health endpoint
		srv.SetTemplateFS(templates.TemplateFS) // Always available — init doesn't need a provider

		slog.Info("sharko starting", "version", version)

		// Initialize provider + gitops config from active connection (if exists).
		// This ensures a pod restart doesn't leave the provider nil when a connection is already stored.
		slog.Info("initializing from stored connection")
		srv.ReinitializeFromConnection()
		slog.Info("server initialization complete")

		// Start notification checker (background goroutine, checks every 30 min).
		notifProvider := notifications.NewServiceProvider(connSvc, addonSvc)
		notifChecker := notifications.NewChecker(srv.NotificationStore(), notifProvider, 30*time.Minute)
		notifChecker.Start()
		defer notifChecker.Stop()

		// Demo mode: wire up mock backends and skip all real provider setup.
		if demoMode {
			slog.Info("demo mode: running with mock backends", "users", "admin/admin, qa/sharko")
			demoCleanup, err := demo.SetupDemoServer(srv, port)
			if err != nil {
				return fmt.Errorf("setting up demo server: %w", err)
			}
			defer demoCleanup()

			// Skip the normal provider/connection setup; go straight to static files + listen.
			var staticFS fs.FS
			if staticDir != "" {
				if info, err := os.Stat(staticDir); err == nil && info.IsDir() {
					staticFS = os.DirFS(staticDir)
				}
			}
			router := api.NewRouter(srv, staticFS)
			addr := fmt.Sprintf(":%d", port)
			slog.Info("listening", "addr", addr)
			if err := http.ListenAndServe(addr, router); err != nil {
				return fmt.Errorf("server error: %w", err)
			}
			return nil
		}

		// Repo path and GitOps config — always constructed (not provider-dependent).
		repoPaths := orchestrator.RepoPathsConfig{
			ClusterValues:   "configuration/addons-clusters-values",
			GlobalValues:    "configuration/addons-global-values",
			Catalog:         "configuration/addons-catalog.yaml",
			Charts:          "charts/",
			Bootstrap:       "bootstrap/",
			ManagedClusters: getEnvDefault("SHARKO_REPO_PATH_MANAGED_CLUSTERS", "configuration/managed-clusters.yaml"),
		}

		gitopsCfg := orchestrator.GitOpsConfig{
			BranchPrefix: "sharko/",
			CommitPrefix: "sharko:",
			BaseBranch:   "main",
		}

		// Build product config from active connection (connection store is sole authority).
		if conn, err := connSvc.GetActiveConnection(); err == nil && conn != nil {
			if conn.GitOps != nil {
				if conn.GitOps.BaseBranch != "" {
					gitopsCfg.BaseBranch = conn.GitOps.BaseBranch
				}
				if conn.GitOps.BranchPrefix != "" {
					gitopsCfg.BranchPrefix = conn.GitOps.BranchPrefix
				}
				if conn.GitOps.CommitPrefix != "" {
					gitopsCfg.CommitPrefix = conn.GitOps.CommitPrefix
				}
				if conn.GitOps.PRAutoMerge != nil {
					gitopsCfg.PRAutoMerge = *conn.GitOps.PRAutoMerge
				}
				if conn.GitOps.HostClusterName != "" {
					repoPaths.HostClusterName = conn.GitOps.HostClusterName
				} else if mode == platform.ModeKubernetes {
					if detected := platform.DetectClusterName(); detected != "" {
						repoPaths.HostClusterName = detected
						slog.Info("host cluster name auto-detected", "cluster", detected)
					}
				}
			}
			if conn.Git.RepoURL != "" {
				gitopsCfg.RepoURL = conn.Git.RepoURL
			}
		}

		// Provider + Orchestrator write-API deps (optional — only if provider is configured).
		var credProvider providers.ClusterCredentialsProvider
		var provCfgPtr *providers.Config

		namespace := os.Getenv("SHARKO_NAMESPACE")
		if namespace == "" {
			namespace = "sharko"
		}

		var resolvedProvCfg *providers.Config
		if connProv := connSvc.GetProviderConfig(); connProv != nil && connProv.Type != "" {
			ns := connProv.Namespace
			if ns == "" {
				ns = namespace
			}
			resolvedProvCfg = &providers.Config{
				Type:      connProv.Type,
				Region:    connProv.Region,
				Prefix:    connProv.Prefix,
				Namespace: ns,
				RoleARN:   connProv.RoleARN,
			}
			slog.Info("secrets provider configured from connection", "type", connProv.Type)
		}

		if resolvedProvCfg != nil {
			cp, err := providers.New(*resolvedProvCfg)
			if err != nil {
				slog.Warn("could not create secrets provider", "error", err)
			} else {
				credProvider = cp
				provCfgPtr = resolvedProvCfg

				// Default addons (applied to clusters registered without explicit addons).
				if connGitOps := getConnectionGitOps(connSvc); connGitOps != nil && connGitOps.DefaultAddons != "" {
					defaults := make(map[string]bool)
					for _, name := range strings.Split(connGitOps.DefaultAddons, ",") {
						name = strings.TrimSpace(name)
						if name != "" {
							defaults[name] = true
						}
					}
					if len(defaults) > 0 {
						srv.SetDefaultAddons(defaults)
						slog.Info("default addons configured", "addons", connGitOps.DefaultAddons)
					}
				}

				slog.Info("secrets provider enabled", "type", resolvedProvCfg.Type)
			}
		}

		// Always wire write-API deps — credProvider may be nil if no provider is configured.
		srv.SetWriteAPIDeps(credProvider, provCfgPtr, repoPaths, gitopsCfg)

		// Secret reconciler — reconciles addon secrets on remote clusters.
		if credProvider != nil && provCfgPtr != nil {
			secretProvider, spErr := providers.NewSecretProvider(*provCfgPtr)
			if spErr != nil {
				slog.Warn("could not create secret provider for reconciler", "error", spErr)
			} else {
				reconcileInterval := getEnvDefault("SHARKO_SECRET_RECONCILE_INTERVAL", "5m")
				dur, parseErr := time.ParseDuration(reconcileInterval)
				if parseErr != nil {
					slog.Warn("invalid reconcile interval, using 5m", "interval", reconcileInterval)
					dur = 5 * time.Minute
				}

				parser := config.NewParser()
				baseBranch := gitopsCfg.BaseBranch
				if baseBranch == "" {
					baseBranch = "main"
				}

				gitReaderFn := func() secrets.GitReader {
					gp, err := connSvc.GetActiveGitProvider()
					if err != nil {
						return nil
					}
					return gp
				}

				reconciler := secrets.NewReconciler(
					credProvider,
					secretProvider,
					gitReaderFn,
					remoteclient.NewClientFromKubeconfig,
					parser,
					baseBranch,
					repoPaths.ManagedClusters,
					dur,
				)
				srv.SetSecretReconciler(reconciler)

				// Wire audit callback so reconcile events appear in GET /api/v1/audit.
				auditLog := srv.AuditLog()
				reconciler.SetAuditFunc(func(clusterName string, created, updated int) {
					auditLog.Add(audit.Entry{
						Level:    "info",
						Event:    "secret_push",
						User:     "sharko",
						Action:   "push",
						Resource: fmt.Sprintf("secrets reconciled — created: %d, updated: %d", created, updated),
						Source:   "reconciler",
						Result:   "success",
					})
				})

				reconciler.Start()
				defer reconciler.Stop()
				slog.Info("secret reconciler started", "interval", dur)
			}
		}

		// ArgoCD cluster secrets reconciler — writes ArgoCD cluster secrets into the argocd namespace
		// so that ArgoCD's ApplicationSet cluster generator can discover Sharko-managed clusters.
		// Only starts if credProvider is configured (same guard as the existing secrets reconciler).
		if credProvider != nil {
			inClusterCfg, inClusterErr := rest.InClusterConfig()
			if inClusterErr != nil {
				slog.Warn("not running in-cluster, skipping argocd secrets reconciler", "error", inClusterErr)
			} else {
				k8sClient, k8sErr := kubernetes.NewForConfig(inClusterCfg)
				if k8sErr != nil {
					slog.Warn("could not create in-cluster k8s client, skipping argocd secrets reconciler", "error", k8sErr)
				} else {
					argocdNamespace := getEnvDefault("SHARKO_ARGOCD_NAMESPACE", "argocd")

					argoIntervalStr := getEnvDefault("SHARKO_ARGOCD_RECONCILE_INTERVAL", "3m")
					argoDur, argoParseErr := time.ParseDuration(argoIntervalStr)
					if argoParseErr != nil {
						slog.Warn("invalid argocd reconcile interval, using 3m", "interval", argoIntervalStr)
						argoDur = 3 * time.Minute
					}

					argoParser := config.NewParser()
					argoBaseBranch := gitopsCfg.BaseBranch
					if argoBaseBranch == "" {
						argoBaseBranch = "main"
					}

					argoGitReaderFn := func() argosecrets.GitReader {
						gp, err := connSvc.GetActiveGitProvider()
						if err != nil {
							return nil
						}
						return gp
					}

					argoDefaultRoleARN := ""
					if provCfgPtr != nil {
						argoDefaultRoleARN = provCfgPtr.RoleARN
					}

					argoManager := argosecrets.NewManager(k8sClient, argocdNamespace)
					argoReconciler := argosecrets.NewReconciler(
						argoManager,
						credProvider,
						argoGitReaderFn,
						argoParser,
						argoBaseBranch,
						argoDefaultRoleARN,
						repoPaths.ManagedClusters,
						argoDur,
					)

					auditLog := srv.AuditLog()
					argoReconciler.SetAuditFunc(func(created, updated, deleted int) {
						auditLog.Add(audit.Entry{
							Level:    "info",
							Event:    "cluster_secret_sync",
							User:     "sharko",
							Action:   "sync",
							Resource: fmt.Sprintf("ArgoCD secrets reconciled — created: %d, updated: %d, deleted: %d", created, updated, deleted),
							Source:   "reconciler",
							Result:   "success",
						})
					})

					srv.SetArgoSecretManager(argoManager)
					srv.SetArgoSecretReconciler(argoReconciler)

					// Store stable config for ReinitializeFromConnection to use.
					srv.SetArgoReconcilerConfig(&api.ArgoReconcilerCfg{
						K8sClient:           k8sClient,
						ArgocdNamespace:     argocdNamespace,
						Interval:            argoDur,
						GitReaderFn:         argoGitReaderFn,
						Parser:              argoParser,
						ManagedClustersPath: repoPaths.ManagedClusters,
					})

					argoReconciler.Start(context.Background())
					// Use a closure that reads through the getter so that if
					// ReinitializeFromConnection replaces the reconciler the correct
					// (current) instance is stopped on shutdown, not the one captured
					// at startup time.
					defer func() {
						if r := srv.ArgoSecretReconciler(); r != nil {
							r.Stop()
						}
					}()
					slog.Info("argocd secrets reconciler started", "namespace", argocdNamespace, "interval", argoDur)
				}
			}
		}

		// PR Tracker — polls Git provider for PR status changes and emits audit events.
		// Uses a ConfigMap to persist tracking state across restarts.
		{
			prNamespace := os.Getenv("SHARKO_NAMESPACE")
			if prNamespace == "" {
				prNamespace = "sharko"
			}

			// Build K8s client for cmstore — in-cluster or skip if not available.
			var prCMStore *cmstore.Store
			if mode == platform.ModeKubernetes {
				inClusterCfg, inClusterErr := rest.InClusterConfig()
				if inClusterErr == nil {
					k8sClient, k8sErr := kubernetes.NewForConfig(inClusterCfg)
					if k8sErr == nil {
						prCMStore = cmstore.NewStore(k8sClient, prNamespace, "sharko-pending-prs")
					} else {
						slog.Warn("could not create k8s client for pr tracker", "error", k8sErr)
					}
				} else {
					slog.Warn("not running in-cluster, skipping pr tracker cmstore", "error", inClusterErr)
				}
			}

			if prCMStore != nil {
				auditLog := srv.AuditLog()
				gitProviderFn := func() prtracker.GitProvider {
					gp, err := connSvc.GetActiveGitProvider()
					if err != nil {
						return nil
					}
					return gp
				}

				prTracker := prtracker.NewTracker(prCMStore, gitProviderFn, func(e audit.Entry) {
					auditLog.Add(e)
				})

				// On merge, trigger the argosecrets reconciler so it picks up changes immediately.
				if srv.ArgoSecretReconciler() != nil {
					prTracker.SetOnMergeFn(func(pr prtracker.PRInfo) {
						if r := srv.ArgoSecretReconciler(); r != nil {
							r.Trigger()
						}
					})
				}

				srv.SetPRTracker(prTracker)
				prTracker.ReconcileOnStartup(context.Background())
				prTracker.Start(context.Background())
				defer prTracker.Stop()
				slog.Info("pr tracker started")
			}
		}

		// AI config persistence (K8s mode — encrypted Secret)
		if mode == platform.ModeKubernetes {
			encKey := os.Getenv("SHARKO_ENCRYPTION_KEY")
			namespace := os.Getenv("SHARKO_NAMESPACE")
			if namespace == "" {
				namespace = "sharko"
			}
			if encKey != "" {
				aiStore, err := config.NewAIConfigStore(namespace, encKey)
				if err != nil {
					slog.Warn("could not create ai config store", "error", err)
				} else {
					srv.SetAIConfigStore(aiStore)
					// Load persisted AI config (UI-set values override env vars)
					if savedJSON, err := aiStore.LoadJSON(); err != nil {
						slog.Warn("could not load ai config", "error", err)
					} else if savedJSON != nil {
						var savedCfg ai.Config
						if err := json.Unmarshal(savedJSON, &savedCfg); err != nil {
							slog.Warn("could not decode ai config", "error", err)
						} else if savedCfg.Provider != "" {
							aiClient.SetConfig(savedCfg)
							slog.Info("ai config loaded from k8s secret", "provider", savedCfg.Provider)
						}
					}
				}
			}
		}

		// Static files
		var staticFS fs.FS
		if staticDir != "" {
			if info, err := os.Stat(staticDir); err == nil && info.IsDir() {
				staticFS = os.DirFS(staticDir)
				slog.Info("serving static files", "dir", staticDir)
			}
		}

		router := api.NewRouter(srv, staticFS)

		addr := fmt.Sprintf(":%d", port)
		slog.Info("listening", "addr", addr)
		if err := http.ListenAndServe(addr, router); err != nil {
			return fmt.Errorf("server error: %w", err)
		}
		return nil
	},
}

func getEnvDefault(key, defaultVal string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return defaultVal
}

// getConnectionGitOps returns the GitOpsSettings from the active connection, or nil if not set.
func getConnectionGitOps(connSvc *service.ConnectionService) *models.GitOpsSettings {
	conn, err := connSvc.GetActiveConnection()
	if err != nil || conn == nil {
		return nil
	}
	return conn.GitOps
}

// loadSecretsEnv loads KEY=VALUE pairs from secrets.env into the environment.
// Lines starting with # and empty lines are skipped. Does not override existing env vars.
func loadSecretsEnv(path string) {
	f, err := os.Open(path)
	if err != nil {
		return // file doesn't exist, that's fine
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	count := 0
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		// Remove surrounding quotes if present
		if len(value) >= 2 && ((value[0] == '"' && value[len(value)-1] == '"') || (value[0] == '\'' && value[len(value)-1] == '\'')) {
			value = value[1 : len(value)-1]
		}
		// Don't override existing env vars
		if os.Getenv(key) == "" {
			os.Setenv(key, value)
			count++
		}
	}
	if count > 0 {
		slog.Info("loaded secrets from file", "count", count, "path", path)
	}
}
