package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io/fs"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/MoranWeissman/sharko/internal/ai"
	"github.com/MoranWeissman/sharko/internal/api"
	"github.com/MoranWeissman/sharko/internal/config"
	"github.com/MoranWeissman/sharko/internal/demo"
	"github.com/MoranWeissman/sharko/internal/models"
	"github.com/MoranWeissman/sharko/internal/notifications"
	"github.com/MoranWeissman/sharko/internal/orchestrator"
	"github.com/MoranWeissman/sharko/internal/platform"
	"github.com/MoranWeissman/sharko/internal/providers"
	"github.com/MoranWeissman/sharko/internal/remoteclient"
	"github.com/MoranWeissman/sharko/internal/secrets"
	"github.com/MoranWeissman/sharko/internal/service"
	"github.com/MoranWeissman/sharko/templates"
	"github.com/spf13/cobra"
)

func init() {
	serveCmd.Flags().Int("port", 8080, "HTTP server port")
	serveCmd.Flags().String("config", "config.yaml", "Path to config file (local mode)")
	serveCmd.Flags().String("static", "", "Path to static files directory (UI)")
	serveCmd.Flags().Bool("demo", false, "Run with mock backends for QA testing (no external dependencies)")
	rootCmd.AddCommand(serveCmd)
}

// @title Sharko API
// @version 1.0.0
// @description Addon management server for Kubernetes clusters, built on ArgoCD.
// @host localhost:8080
// @BasePath /api/v1
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the Sharko API server",
	RunE: func(cmd *cobra.Command, args []string) error {
		port, _ := cmd.Flags().GetInt("port")
		configPath, _ := cmd.Flags().GetString("config")
		staticDir, _ := cmd.Flags().GetString("static")
		demoMode, _ := cmd.Flags().GetBool("demo")

		// Override from env
		if envPort := os.Getenv("SHARKO_PORT"); envPort != "" {
			fmt.Sscanf(envPort, "%d", &port)
		}
		if envConfig := os.Getenv("SHARKO_CONFIG"); envConfig != "" {
			configPath = envConfig
		}
		if envStatic := os.Getenv("SHARKO_STATIC_DIR"); envStatic != "" {
			staticDir = envStatic
		}

		// Load secrets from secrets.env for local development
		loadSecretsEnv("secrets.env")

		// Detect runtime mode
		mode := platform.Detect()
		log.Printf("Sharko starting in %s mode", mode)

		// Initialize config store
		var store config.Store
		switch mode {
		case platform.ModeKubernetes:
			encKey := os.Getenv("SHARKO_ENCRYPTION_KEY")
			if encKey == "" {
				return fmt.Errorf("SHARKO_ENCRYPTION_KEY is required when running on Kubernetes. " +
					"It is auto-generated by the Helm chart on first install.")
			}
			secretName := os.Getenv("CONNECTION_SECRET_NAME")
			if secretName == "" {
				secretName = "sharko-connections"
			}
			namespace := os.Getenv("SHARKO_NAMESPACE")
			if namespace == "" {
				namespace = "sharko"
			}
			var err error
			store, err = config.NewK8sStore(namespace, secretName, encKey)
			if err != nil {
				return fmt.Errorf("failed to create K8s connection store: %w", err)
			}
			log.Printf("Connection config stored in encrypted K8s Secret: %s/%s", namespace, secretName)
		default:
			store = config.NewFileStore(configPath)
		}

		// AI configuration — resolve per-provider API key and model
		aiProvider := ai.Provider(os.Getenv("AI_PROVIDER"))
		aiAPIKey := os.Getenv("AI_API_KEY")    // generic fallback
		aiModel := os.Getenv("AI_CLOUD_MODEL") // generic fallback
		aiBaseURL := os.Getenv("AI_BASE_URL")
		aiAuthHeader := os.Getenv("AI_AUTH_HEADER")

		switch aiProvider {
		case ai.ProviderOpenAI:
			if k := os.Getenv("OPENAI_API_KEY"); k != "" {
				aiAPIKey = k
			}
			if m := os.Getenv("OPENAI_MODEL"); m != "" {
				aiModel = m
			}
		case ai.ProviderClaude:
			if k := os.Getenv("CLAUDE_API_KEY"); k != "" {
				aiAPIKey = k
			}
			if m := os.Getenv("CLAUDE_MODEL"); m != "" {
				aiModel = m
			}
		case ai.ProviderGemini:
			if k := os.Getenv("GEMINI_API_KEY"); k != "" {
				aiAPIKey = k
			}
			if m := os.Getenv("GEMINI_MODEL"); m != "" {
				aiModel = m
			}
		case ai.ProviderCustomOpenAI:
			if k := os.Getenv("CUSTOM_OPENAI_API_KEY"); k != "" {
				aiAPIKey = k
			}
			if m := os.Getenv("CUSTOM_OPENAI_MODEL"); m != "" {
				aiModel = m
			}
			if u := os.Getenv("CUSTOM_OPENAI_BASE_URL"); u != "" {
				aiBaseURL = u
			}
			if h := os.Getenv("CUSTOM_OPENAI_AUTH_HEADER"); h != "" {
				aiAuthHeader = h
			}
		}

		aiCfg := ai.Config{
			Provider:      aiProvider,
			OllamaURL:     getEnvDefault("AI_OLLAMA_URL", "http://localhost:11434"),
			OllamaModel:   getEnvDefault("AI_OLLAMA_MODEL", "llama3.2"),
			AgentModel:     os.Getenv("AI_AGENT_MODEL"),
			APIKey:         aiAPIKey,
			CloudModel:     aiModel,
			BaseURL:        aiBaseURL,
			AuthHeader:     aiAuthHeader,
			GitOpsEnabled:  os.Getenv("GITOPS_ACTIONS_ENABLED") == "true",
		}
		if v := os.Getenv("AI_MAX_ITERATIONS"); v != "" {
			fmt.Sscanf(v, "%d", &aiCfg.MaxIterations)
		}
		aiClient := ai.NewClient(aiCfg)
		if aiClient.IsEnabled() {
			model := aiCfg.OllamaModel
			if aiCfg.Provider == ai.ProviderClaude || aiCfg.Provider == ai.ProviderOpenAI || aiCfg.Provider == ai.ProviderGemini {
				model = aiCfg.CloudModel
			}
			log.Printf("AI provider enabled: %s (model: %s)", aiCfg.Provider, model)
		}

		// Wire up services
		connSvc := service.NewConnectionService(store)
		clusterSvc := service.NewClusterService()
		addonSvc := service.NewAddonService()
		dashboardSvc := service.NewDashboardService(connSvc)
		observabilitySvc := service.NewObservabilityService()
		upgradeSvc := service.NewUpgradeService(aiClient)

		// Build server
		srv := api.NewServer(connSvc, clusterSvc, addonSvc, dashboardSvc, observabilitySvc, upgradeSvc, aiClient)
		srv.SetVersion(version)                 // Propagate ldflags-injected version to health endpoint
		srv.SetTemplateFS(templates.TemplateFS) // Always available — init doesn't need a provider

		// Start notification checker (background goroutine, checks every 30 min).
		notifProvider := notifications.NewServiceProvider(connSvc, addonSvc)
		notifChecker := notifications.NewChecker(srv.NotificationStore(), notifProvider, 30*time.Minute)
		notifChecker.Start()
		defer notifChecker.Stop()

		// Demo mode: wire up mock backends and skip all real provider setup.
		if demoMode {
			log.Printf("DEMO MODE: Running with mock backends. Login: admin/admin or qa/sharko")
			demoCleanup, err := demo.SetupDemoServer(srv, port)
			if err != nil {
				return fmt.Errorf("setting up demo server: %w", err)
			}
			defer demoCleanup()

			// Skip the normal provider/connection setup; go straight to static files + listen.
			var staticFS fs.FS
			if staticDir != "" {
				if info, err := os.Stat(staticDir); err == nil && info.IsDir() {
					staticFS = os.DirFS(staticDir)
				}
			}
			router := api.NewRouter(srv, staticFS)
			addr := fmt.Sprintf(":%d", port)
			log.Printf("Listening on %s", addr)
			if err := http.ListenAndServe(addr, router); err != nil {
				return fmt.Errorf("server error: %w", err)
			}
			return nil
		}

		// Repo path and GitOps config — always constructed (not provider-dependent).
		repoPaths := orchestrator.RepoPathsConfig{
			ClusterValues: "configuration/addons-clusters-values",
			GlobalValues:  "configuration/addons-global-values",
			Catalog:       "configuration/addons-catalog.yaml",
			Charts:        "charts/",
			Bootstrap:     "bootstrap/",
		}

		gitopsCfg := orchestrator.GitOpsConfig{
			BranchPrefix: "sharko/",
			CommitPrefix: "sharko:",
			BaseBranch:   "main",
		}

		// Build product config from active connection (connection store is sole authority).
		if conn, err := connSvc.GetActiveConnection(); err == nil && conn != nil {
			if conn.GitOps != nil {
				if conn.GitOps.BaseBranch != "" {
					gitopsCfg.BaseBranch = conn.GitOps.BaseBranch
				}
				if conn.GitOps.BranchPrefix != "" {
					gitopsCfg.BranchPrefix = conn.GitOps.BranchPrefix
				}
				if conn.GitOps.CommitPrefix != "" {
					gitopsCfg.CommitPrefix = conn.GitOps.CommitPrefix
				}
				if conn.GitOps.PRAutoMerge != nil {
					gitopsCfg.PRAutoMerge = *conn.GitOps.PRAutoMerge
				}
				if conn.GitOps.HostClusterName != "" {
					repoPaths.HostClusterName = conn.GitOps.HostClusterName
				}
			}
			if conn.Git.RepoURL != "" {
				gitopsCfg.RepoURL = conn.Git.RepoURL
			}
		}

		// Provider + Orchestrator write-API deps (optional — only if provider is configured).
		var credProvider providers.ClusterCredentialsProvider
		var provCfgPtr *providers.Config

		namespace := os.Getenv("SHARKO_NAMESPACE")
		if namespace == "" {
			namespace = "sharko"
		}

		var resolvedProvCfg *providers.Config
		if connProv := connSvc.GetProviderConfig(); connProv != nil && connProv.Type != "" {
			ns := connProv.Namespace
			if ns == "" {
				ns = namespace
			}
			resolvedProvCfg = &providers.Config{
				Type:      connProv.Type,
				Region:    connProv.Region,
				Prefix:    connProv.Prefix,
				Namespace: ns,
			}
			log.Printf("Secrets provider configured from connection: %s", connProv.Type)
		}

		if resolvedProvCfg != nil {
			cp, err := providers.New(*resolvedProvCfg)
			if err != nil {
				log.Printf("WARNING: Could not create secrets provider: %v", err)
			} else {
				credProvider = cp
				provCfgPtr = resolvedProvCfg

				// Default addons (applied to clusters registered without explicit addons).
				if connGitOps := getConnectionGitOps(connSvc); connGitOps != nil && connGitOps.DefaultAddons != "" {
					defaults := make(map[string]bool)
					for _, name := range strings.Split(connGitOps.DefaultAddons, ",") {
						name = strings.TrimSpace(name)
						if name != "" {
							defaults[name] = true
						}
					}
					if len(defaults) > 0 {
						srv.SetDefaultAddons(defaults)
						log.Printf("Default addons configured: %v", connGitOps.DefaultAddons)
					}
				}

				log.Printf("Secrets provider enabled: %s", resolvedProvCfg.Type)
			}
		}

		// Always wire write-API deps — credProvider may be nil if no provider is configured.
		srv.SetWriteAPIDeps(credProvider, provCfgPtr, repoPaths, gitopsCfg)

		// Secret reconciler — reconciles addon secrets on remote clusters.
		if credProvider != nil && provCfgPtr != nil {
			secretProvider, spErr := providers.NewSecretProvider(*provCfgPtr)
			if spErr != nil {
				log.Printf("WARNING: Could not create secret provider for reconciler: %v", spErr)
			} else {
				reconcileInterval := getEnvDefault("SHARKO_SECRET_RECONCILE_INTERVAL", "5m")
				dur, parseErr := time.ParseDuration(reconcileInterval)
				if parseErr != nil {
					log.Printf("WARNING: Invalid reconcile interval %q, using 5m", reconcileInterval)
					dur = 5 * time.Minute
				}

				parser := config.NewParser()
				baseBranch := gitopsCfg.BaseBranch
				if baseBranch == "" {
					baseBranch = "main"
				}

				gitReaderFn := func() secrets.GitReader {
					gp, err := connSvc.GetActiveGitProvider()
					if err != nil {
						return nil
					}
					return gp
				}

				reconciler := secrets.NewReconciler(
					credProvider,
					secretProvider,
					gitReaderFn,
					remoteclient.NewClientFromKubeconfig,
					parser,
					baseBranch,
					dur,
				)
				srv.SetSecretReconciler(reconciler)
				reconciler.Start()
				defer reconciler.Stop()
				log.Printf("Secret reconciler started (interval: %s)", dur)
			}
		}

		// AI config persistence (K8s mode — encrypted Secret)
		if mode == platform.ModeKubernetes {
			encKey := os.Getenv("SHARKO_ENCRYPTION_KEY")
			namespace := os.Getenv("SHARKO_NAMESPACE")
			if namespace == "" {
				namespace = "sharko"
			}
			if encKey != "" {
				aiStore, err := config.NewAIConfigStore(namespace, encKey)
				if err != nil {
					log.Printf("WARNING: Could not create AI config store: %v", err)
				} else {
					srv.SetAIConfigStore(aiStore)
					// Load persisted AI config (UI-set values override env vars)
					if savedJSON, err := aiStore.LoadJSON(); err != nil {
						log.Printf("WARNING: Could not load AI config: %v", err)
					} else if savedJSON != nil {
						var savedCfg ai.Config
						if err := json.Unmarshal(savedJSON, &savedCfg); err != nil {
							log.Printf("WARNING: Could not decode AI config: %v", err)
						} else if savedCfg.Provider != "" {
							aiClient.SetConfig(savedCfg)
							log.Printf("AI config loaded from K8s Secret (provider: %s)", savedCfg.Provider)
						}
					}
				}
			}
		}

		// Static files
		var staticFS fs.FS
		if staticDir != "" {
			if info, err := os.Stat(staticDir); err == nil && info.IsDir() {
				staticFS = os.DirFS(staticDir)
				log.Printf("Serving static files from %s", staticDir)
			}
		}

		router := api.NewRouter(srv, staticFS)

		addr := fmt.Sprintf(":%d", port)
		log.Printf("Listening on %s", addr)
		if err := http.ListenAndServe(addr, router); err != nil {
			return fmt.Errorf("server error: %w", err)
		}
		return nil
	},
}

func getEnvDefault(key, defaultVal string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return defaultVal
}

// getConnectionGitOps returns the GitOpsSettings from the active connection, or nil if not set.
func getConnectionGitOps(connSvc *service.ConnectionService) *models.GitOpsSettings {
	conn, err := connSvc.GetActiveConnection()
	if err != nil || conn == nil {
		return nil
	}
	return conn.GitOps
}

// loadSecretsEnv loads KEY=VALUE pairs from secrets.env into the environment.
// Lines starting with # and empty lines are skipped. Does not override existing env vars.
func loadSecretsEnv(path string) {
	f, err := os.Open(path)
	if err != nil {
		return // file doesn't exist, that's fine
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	count := 0
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		// Remove surrounding quotes if present
		if len(value) >= 2 && ((value[0] == '"' && value[len(value)-1] == '"') || (value[0] == '\'' && value[len(value)-1] == '\'')) {
			value = value[1 : len(value)-1]
		}
		// Don't override existing env vars
		if os.Getenv(key) == "" {
			os.Setenv(key, value)
			count++
		}
	}
	if count > 0 {
		log.Printf("Loaded %d secrets from %s", count, path)
	}
}
