apiVersion: v2
name: sharko
description: Addon management for Kubernetes clusters, built on ArgoCD
type: application
version: 1.6.1
appVersion: "1.6.1"
keywords:
  - argocd
  - kubernetes
  - addons
  - helm
  - observability
home: https://github.com/MoranWeissman/sharko
maintainers:
  - name: MoranWeissman
