# ---- Istio EKS Auto Mode infra-karpenter Overrides ---- #

# Istiod Control Plane - target infrastructure nodes
pilot:
  nodeSelector:
    node-type: infrastructure
  tolerations:
    - key: infrastructure
      operator: Equal
      value: "true"
      effect: NoSchedule

# Global settings for all Istio components
global:
  defaultNodeSelector:
    node-type: infrastructure
  defaultTolerations:
    - key: infrastructure
      operator: Equal
      value: "true"
      effect: NoSchedule
