//go:build e2e

// Package lifecycle — V2 Epic 7-1 Story 7-1.8 (values editor + AI flows).
//
// Two top-level tests cover the 10 values-editor endpoints end-to-end
// against an in-process Sharko + the harness MockGitProvider:
//
//   TestGlobalValuesEditor:
//     - GET  /api/v1/addons/{name}/values-schema           (current + AI flags)
//     - PUT  /api/v1/addons/{name}/values                  (commits via mock)
//     - GET  /api/v1/addons/{name}/values/recent-prs       (lists merged PRs)
//     - PUT  /api/v1/addons/{name}/values/ai-opt-out       (toggles directive)
//     - POST /api/v1/addons/{name}/values/preview-merge    (additive diff)
//     - POST /api/v1/addons/{name}/values/annotate         (AI; gated)
//
//   TestPerClusterValuesOverride:
//     - GET  /api/v1/clusters/{c}/addons/{n}/values        (empty inherit)
//     - PUT  /api/v1/clusters/{c}/addons/{n}/values        (commits override)
//     - GET  /api/v1/clusters/{c}/addons/{n}/values        (echoes override)
//     - GET  /api/v1/clusters/{c}/addons/{n}/values/recent-prs
//
// Both tests run with E2E_AUTO_MERGE off (the default), so PUT requests
// open a PR and the orchestrator does NOT merge it — the recent-prs panel
// only surfaces MERGED PRs, so the test explicitly merges the PR via the
// MockGitProvider's MergePR helper to simulate human approval.
//
// Story 7-1.8 is independent of cluster registration (story 7-1.4) and
// per-cluster addon enable (7-1.7) — we sidestep the orchestrator's
// register-cluster machinery by seeding cluster + addon catalog state
// directly through the MockGitProvider. This keeps the test scope tight
// to the values surface.
package lifecycle

import (
	"net/http"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/MoranWeissman/sharko/internal/orchestrator"
	"github.com/MoranWeissman/sharko/tests/e2e/harness"
)

// addonName is the catalog-pinned addon every subtest acts on. cert-manager
// is in the bootstrap template (charts.jetstack.io is a stable public Helm
// repo) so the preview-merge path can fetch real upstream values.
const (
	testAddonName    = "cert-manager"
	testAddonChart   = "cert-manager"
	testAddonRepoURL = "https://charts.jetstack.io"
	testAddonVersion = "1.16.3"
)

// TestGlobalValuesEditor drives the global values surface through the API.
// All write operations land on the MockGitProvider so we can assert the
// committed file content + opened PR shape directly.
//
// Subtests are ORDERED — they share state on the shared mock. The order is:
//
//  1. GetValuesSchema          (read on empty repo → current_values empty)
//  2. PutGlobalValues          (writes a smart-values-headered file → opens PR #1)
//  3. RecentPRs                (merges PR #1, then verifies the panel surfaces it)
//  4. AIOptOutToggle           (flips opt-out off → on, asserts header diff)
//  5. PreviewMerge             (additive merge from upstream; gated on network)
//  6. Annotate                 (AI annotate; gated on E2E_AI_ENABLED)
func TestGlobalValuesEditor(t *testing.T) {
	git := harness.StartGitFake(t)
	mock := harness.StartGitMock(t)
	sharko := harness.StartSharko(t, harness.SharkoConfig{
		Mode:        harness.SharkoModeInProcess,
		GitFake:     git,
		GitProvider: mock,
	})
	sharko.WaitHealthy(t, 10*time.Second)

	admin := harness.NewClient(t, sharko)

	// Seed the addons catalog so AddonService.GetAddonDetail finds the
	// addon. Without this, every PUT 404s with "addon not found in catalog".
	harness.SeedAddonsCatalog(t, mock)

	// Seed an active connection so handlers calling GetActiveArgocdClient()
	// (PUT values, AI annotate, AI opt-out, preview-merge) construct one.
	// The synthetic ArgoCD URL never gets dialled during the values flow.
	harness.SeedActiveConnection(t, sharko, admin, harness.SeedActiveConnectionConfig{})

	// ─── Subtest 1: GET values-schema on empty file ─────────────────────
	t.Run("GetValuesSchema", func(t *testing.T) {
		schema := admin.GetAddonValuesSchema(t, testAddonName)
		if schema.AddonName != testAddonName {
			t.Errorf("schema.AddonName = %q, want %q", schema.AddonName, testAddonName)
		}
		// No file exists yet — current_values is empty, AI flags both false.
		if schema.CurrentValues != "" {
			t.Errorf("schema.CurrentValues = %q (want empty for fresh addon)", schema.CurrentValues)
		}
		if schema.AIAnnotated {
			t.Errorf("schema.AIAnnotated = true on fresh addon (want false)")
		}
		if schema.AIOptOut {
			t.Errorf("schema.AIOptOut = true on fresh addon (want false)")
		}
		if schema.LegacyWrapDetected {
			t.Errorf("schema.LegacyWrapDetected = true on fresh addon (want false)")
		}
	})

	// ─── Subtest 2: PUT global values → opens a PR with the YAML ────────
	const initialValuesYAML = `# Generated by Sharko from cert-manager@1.16.3 on 2026-05-13
# Chart source: https://charts.jetstack.io
# AI annotation: disabled
# sharko: managed=true

replicaCount: 2
prometheus:
  enabled: true
`

	var putResult *harness.SetAddonValuesResult
	t.Run("PutGlobalValues", func(t *testing.T) {
		putResult = admin.SetAddonValues(t, testAddonName, harness.SetAddonValuesRequest{
			Values: initialValuesYAML,
		})
		if putResult.PRID <= 0 {
			t.Fatalf("PutGlobalValues: pr_id = %d (want > 0)", putResult.PRID)
		}
		if putResult.PRUrl == "" {
			t.Errorf("PutGlobalValues: empty pr_url")
		}
		if putResult.Branch == "" {
			t.Errorf("PutGlobalValues: empty branch")
		}
		if putResult.ValuesFile != "configuration/addons-global-values/cert-manager.yaml" {
			t.Errorf("PutGlobalValues: values_file = %q, want canonical global-values path", putResult.ValuesFile)
		}
		if putResult.Merged {
			t.Errorf("PutGlobalValues: merged=true but auto-merge is off")
		}

		// Mock-side assertion: the PR exists in open state with the
		// branch we got back, and the new YAML lives on the head branch.
		prs := mock.PRsForBranch(putResult.Branch)
		if len(prs) != 1 {
			t.Fatalf("mock: expected 1 PR for branch %q, got %d", putResult.Branch, len(prs))
		}
		if got := prs[0].State; got != "open" {
			t.Errorf("mock PR state = %q, want open", got)
		}
		if got := mock.FileAt(putResult.Branch, putResult.ValuesFile); got != initialValuesYAML {
			t.Errorf("mock head-branch file content mismatch.\n got: %q\nwant: %q", got, initialValuesYAML)
		}

		// Schema GET now reflects the new file's smart-values header.
		schema := admin.GetAddonValuesSchema(t, testAddonName)
		// The PR has not merged yet — the values-schema reads the BASE
		// branch (main), so CurrentValues stays empty until the merge.
		if schema.CurrentValues != "" {
			t.Errorf("schema.CurrentValues should still be empty pre-merge, got len=%d", len(schema.CurrentValues))
		}
	})

	// ─── Subtest 3: simulate human approval + verify recent-prs ─────────
	t.Run("RecentPRs", func(t *testing.T) {
		if putResult == nil {
			t.Skip("PutGlobalValues did not run; skipping")
		}
		// Simulate a human merging the PR. The orchestrator's
		// auto-merge stayed off so the PR is open after the PUT — merge
		// it via the mock to land the file on main.
		mock.MergePR(t, putResult.PRID)

		// File should now exist on main and the schema GET reflects it.
		if got := mock.FileAt("main", putResult.ValuesFile); got != initialValuesYAML {
			t.Fatalf("post-merge: main file content mismatch.\n got: %q\nwant: %q", got, initialValuesYAML)
		}
		schema := admin.GetAddonValuesSchema(t, testAddonName)
		if schema.CurrentValues != initialValuesYAML {
			t.Errorf("schema.CurrentValues mismatch post-merge.\n got: %q\nwant: %q",
				schema.CurrentValues, initialValuesYAML)
		}
		// Smart-values header parsed end-to-end.
		if !schema.AIAnnotated {
			// initialValuesYAML has "AI annotation: disabled" — the
			// schema.AIAnnotated mirrors that as false. Just confirm the
			// header parse path ran (no panic, AIOptOut still false).
		}
		if schema.AIOptOut {
			t.Errorf("schema.AIOptOut = true post-PUT (want false; the seed YAML didn't opt out)")
		}

		// recent-prs panel should now surface the merged PR.
		recent := admin.RecentAddonValuesPRs(t, testAddonName)
		if recent.ValuesFile != putResult.ValuesFile {
			t.Errorf("recent.ValuesFile = %q, want %q", recent.ValuesFile, putResult.ValuesFile)
		}
		var found bool
		for _, e := range recent.Entries {
			if e.PRID == putResult.PRID {
				found = true
				if e.Title == "" {
					t.Errorf("recent PR entry has empty title")
				}
				if e.URL == "" {
					t.Errorf("recent PR entry has empty url")
				}
				break
			}
		}
		if !found {
			t.Errorf("recent.Entries missing PR #%d; got %d entries", putResult.PRID, len(recent.Entries))
		}
	})

	// ─── Subtest 4: AI opt-out toggle (header-only mutation) ────────────
	t.Run("AIOptOutToggle", func(t *testing.T) {
		// Pre-state: schema reflects opt_out=false (the seed YAML has
		// no `ai-annotate=off` directive).
		before := admin.GetAddonValuesSchema(t, testAddonName)
		if before.AIOptOut {
			t.Fatalf("AIOptOutToggle: pre-state schema.AIOptOut=true (expected false)")
		}

		// Flip to opt_out=true. Returns a status="ok" with a fresh PR id.
		out := admin.SetAddonAIOptOut(t, testAddonName, true)
		if out.Status != "ok" {
			t.Errorf("AIOptOutToggle: status = %q, want ok", out.Status)
		}
		if !out.OptOut {
			t.Errorf("AIOptOutToggle: opt_out echo = false (want true)")
		}
		if out.PRID <= 0 {
			t.Fatalf("AIOptOutToggle: pr_id = %d (want > 0)", out.PRID)
		}

		// Merge to land the header diff on main.
		mock.MergePR(t, out.PRID)

		// Schema GET now mirrors the header — AIOptOut=true.
		after := admin.GetAddonValuesSchema(t, testAddonName)
		if !after.AIOptOut {
			t.Errorf("AIOptOutToggle: schema.AIOptOut post-merge = false (want true). content=%q",
				after.CurrentValues)
		}
		// Smart-values directive should appear in the header.
		if !strings.Contains(after.CurrentValues, "ai-annotate=off") {
			t.Errorf("AIOptOutToggle: header missing `ai-annotate=off` directive. content=%q",
				after.CurrentValues)
		}

		// Idempotency: re-applying opt_out=true returns status=noop (no
		// new PR opened, no Git activity).
		out2 := admin.SetAddonAIOptOut(t, testAddonName, true)
		if out2.Status != "noop" {
			t.Errorf("AIOptOutToggle: 2nd call status = %q, want noop", out2.Status)
		}
		if out2.PRID != 0 {
			t.Errorf("AIOptOutToggle: 2nd call opened PR #%d (want 0 — idempotent)", out2.PRID)
		}

		// Flip back so subsequent subtests see opt_out=false (cleaner
		// test state — the AI annotate path requires opt_out=false).
		out3 := admin.SetAddonAIOptOut(t, testAddonName, false)
		if out3.Status != "ok" {
			t.Errorf("AIOptOutToggle: revert status = %q, want ok", out3.Status)
		}
		if out3.PRID > 0 {
			mock.MergePR(t, out3.PRID)
		}
	})

	// ─── Subtest 5: preview-merge (network-gated; reaches public Helm repo) ──
	t.Run("PreviewMerge", func(t *testing.T) {
		// Use Do so we can detect the upstream-fetch failure path
		// gracefully (offline CI sandboxes will fail on the index.yaml
		// fetch — that's an environment issue, not a sharko bug).
		resp := admin.Do(t, http.MethodPost,
			"/api/v1/addons/"+testAddonName+"/values/preview-merge", nil)
		defer resp.Body.Close()
		if resp.StatusCode == http.StatusBadGateway {
			t.Skip("PreviewMerge: upstream Helm repo unreachable (502 from helm.FetchValues); skipping in offline sandbox")
		}
		if resp.StatusCode != http.StatusOK {
			t.Fatalf("PreviewMerge: unexpected status %d", resp.StatusCode)
		}
		// Re-issue through the typed wrapper now that we know the path
		// is reachable — keeps the assertion logic in one place.
		preview := admin.PreviewMergeAddonValues(t, testAddonName)
		if preview.UpstreamVersion != testAddonVersion {
			t.Errorf("PreviewMerge: upstream_version = %q, want %q",
				preview.UpstreamVersion, testAddonVersion)
		}
		// Merged body must be non-empty (cert-manager has many keys).
		if strings.TrimSpace(preview.Merged) == "" {
			t.Errorf("PreviewMerge: empty merged body")
		}
		// The user's existing replicaCount key (set in subtest 2 +
		// preserved across the opt-out flow) must appear in the
		// `preserved_user_keys` list — the preview is additive.
		var preserved bool
		for _, k := range preview.DiffSummary.PreservedUserKeys {
			if k == "replicaCount" {
				preserved = true
				break
			}
		}
		if !preserved {
			t.Logf("PreviewMerge: replicaCount not in preserved keys (chart may not define it; preserved=%v)",
				preview.DiffSummary.PreservedUserKeys)
		}
		// Shape sanity.
		if preview.DiffSummary.NewKeys == nil {
			t.Errorf("PreviewMerge: new_keys is nil (expected an empty or non-empty slice)")
		}
	})

	// ─── Subtest 6: AI annotate (gated on E2E_AI_ENABLED) ────────────────
	t.Run("Annotate", func(t *testing.T) {
		if os.Getenv("E2E_AI_ENABLED") != "1" {
			// AI client is disabled in StartSharko (always), so the
			// handler returns 503. Assert that contract instead of
			// skipping outright — verifies the gate is in place.
			resp := admin.Do(t, http.MethodPost,
				"/api/v1/addons/"+testAddonName+"/values/annotate", nil)
			defer resp.Body.Close()
			if resp.StatusCode != http.StatusServiceUnavailable {
				t.Fatalf("Annotate (no AI): status = %d, want 503", resp.StatusCode)
			}
			return
		}
		// Real AI configured (CI with E2E_AI_ENABLED=1) — exercise the
		// happy path. AnnotateAddonValues returns a typed result; AI
		// failures land in AISkipReason rather than as a top-level error.
		ann := admin.AnnotateAddonValues(t, testAddonName)
		if ann.PRID <= 0 && ann.AISkipReason == "" {
			t.Errorf("Annotate: pr_id=0 and ai_skip_reason empty — handler likely produced no PR")
		}
	})
}

// TestPerClusterValuesOverride drives the per-cluster overrides surface
// through the API. Setup is identical to TestGlobalValuesEditor (same boot,
// same mock) plus a single seeded cluster on managed-clusters.yaml so the
// catalog parser knows about the cluster.
func TestPerClusterValuesOverride(t *testing.T) {
	git := harness.StartGitFake(t)
	mock := harness.StartGitMock(t)
	sharko := harness.StartSharko(t, harness.SharkoConfig{
		Mode:        harness.SharkoModeInProcess,
		GitFake:     git,
		GitProvider: mock,
	})
	sharko.WaitHealthy(t, 10*time.Second)

	admin := harness.NewClient(t, sharko)

	harness.SeedAddonsCatalog(t, mock)
	harness.SeedActiveConnection(t, sharko, admin, harness.SeedActiveConnectionConfig{})

	const clusterName = "dev-eu"
	harness.SeedManagedCluster(t, mock, clusterName, map[string]string{
		testAddonName: "enabled",
	})

	// ─── Subtest 1: GET per-cluster values on a fresh repo (empty inherit) ──
	t.Run("GetEmptyOverrides", func(t *testing.T) {
		out := admin.GetClusterAddonValues(t, clusterName, testAddonName)
		if out.ClusterName != clusterName {
			t.Errorf("ClusterName = %q, want %q", out.ClusterName, clusterName)
		}
		if out.AddonName != testAddonName {
			t.Errorf("AddonName = %q, want %q", out.AddonName, testAddonName)
		}
		// No overrides file exists → CurrentOverrides empty.
		if out.CurrentOverrides != "" {
			t.Errorf("CurrentOverrides = %q (want empty for fresh cluster)", out.CurrentOverrides)
		}
	})

	// ─── Subtest 2: PUT per-cluster override → opens a PR ────────────────
	const overrideYAML = `replicaCount: 5
prometheus:
  enabled: false
`
	var putResult *harness.SetClusterAddonValuesResult
	t.Run("PutOverride", func(t *testing.T) {
		putResult = admin.SetClusterAddonValues(t, clusterName, testAddonName,
			harness.SetClusterAddonValuesRequest{Values: overrideYAML})
		if putResult.PRID <= 0 {
			t.Fatalf("PutOverride: pr_id = %d (want > 0)", putResult.PRID)
		}
		expectedPath := "configuration/addons-clusters-values/" + clusterName + ".yaml"
		if putResult.ValuesFile != expectedPath {
			t.Errorf("PutOverride: values_file = %q, want %q", putResult.ValuesFile, expectedPath)
		}
		// The PR's head branch carries the merged file (addonName section
		// nested under the cluster file).
		got := mock.FileAt(putResult.Branch, expectedPath)
		if !strings.Contains(got, testAddonName+":") {
			t.Errorf("PutOverride: head-branch file missing addon section.\n got: %q", got)
		}
		if !strings.Contains(got, "replicaCount: 5") {
			t.Errorf("PutOverride: head-branch file missing override scalar.\n got: %q", got)
		}
	})

	// ─── Subtest 3: GET reflects the override post-merge ────────────────
	t.Run("GetReflectsOverridePostMerge", func(t *testing.T) {
		if putResult == nil {
			t.Skip("PutOverride did not run; skipping")
		}
		mock.MergePR(t, putResult.PRID)

		out := admin.GetClusterAddonValues(t, clusterName, testAddonName)
		if out.CurrentOverrides == "" {
			t.Fatalf("GetReflectsOverridePostMerge: CurrentOverrides empty (want non-empty)")
		}
		if !strings.Contains(out.CurrentOverrides, "replicaCount: 5") {
			t.Errorf("CurrentOverrides missing override scalar.\n got: %q", out.CurrentOverrides)
		}
		if !strings.Contains(out.CurrentOverrides, "enabled: false") {
			t.Errorf("CurrentOverrides missing nested override.\n got: %q", out.CurrentOverrides)
		}
	})

	// ─── Subtest 4: recent-prs panel surfaces the merged cluster PR ──────
	t.Run("RecentPRs", func(t *testing.T) {
		if putResult == nil {
			t.Skip("PutOverride did not run; skipping")
		}
		recent := admin.RecentClusterAddonValuesPRs(t, clusterName, testAddonName)
		if recent.ValuesFile == "" {
			t.Errorf("RecentPRs: empty values_file in response")
		}
		var found bool
		for _, e := range recent.Entries {
			if e.PRID == putResult.PRID {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("RecentPRs: PR #%d missing from %d entries (titles=%v)",
				putResult.PRID, len(recent.Entries), prTitles(recent.Entries))
		}
	})
}

// prTitles is a tiny debug helper for failure messages — keeps the
// surrounding assertion expressive without inlining a loop.
func prTitles(entries []harness.RecentValuesPRsEntry) []string {
	out := make([]string, len(entries))
	for i, e := range entries {
		out[i] = e.Title
	}
	return out
}

// _ keeps the orchestrator import live — the test imports it so a future
// refactor (e.g. story 7-1.13 covering write-tier classification) can drop
// in a typed assertion against orchestrator.PRMetadata without re-touching
// the import block.
var _ = orchestrator.PRMetadata{}
