// Code generated by cmd/gen-engine-version. DO NOT EDIT.
// Source: charts/sharko-engine/Chart.yaml (name + version fields).
// Run 'go run ./cmd/gen-engine-version' or 'make generate-engine-version' to
// refresh after bumping the engine chart's version. CI's "Engine Version Up
// To Date" job fails the build on any diff.
package engineversion

// BundledChartName is the sharko-engine chart's name, as declared in its
// own Chart.yaml. Used to locate the engine chart's source block inside a
// user's engine.yaml (the source with a matching 'chart:'
// field is the engine pin; the second source in that file, the git values
// ref, has no 'chart:' field at all — see
// docs/design/2026-07-30-v4-data-file-format.md section 2.5).
const BundledChartName = "sharko-engine"

// BundledVersion is the sharko-engine chart version bundled with THIS
// build of the Sharko server — i.e. the version Story 2.4's release
// pipeline packages, pushes to the OCI registry, and cosign-signs
// alongside this binary. The engine pin-bump check compares a repo's
// pinned engine.yaml targetRevision against this constant.
const BundledVersion = "0.2.0"
