package main

// main_test.go — GUARD B: the generator reads the real catalog, and holds no
// second copy of the words.
//
// The concrete risk the product owner asked to see closed is a generator that
// carries its own hardcoded list of sentences. Such a generator produces a
// browser file that looks generated, carries a generator's authority, and is
// wrong the moment the server edits a sentence — the original bug with a
// certificate on it.
//
// So this is proved structurally, three ways, none of which depends on anyone
// remembering the rule:
//
//  1. No string literal in main.go is any catalogued sentence, or any part of
//     one. Exact, not a heuristic.
//  2. No string literal in main.go is prose-shaped at all, apart from the
//     handful of scaffolding strings named below. Anything new fails by name.
//  3. main.go imports internal/api and reads api.ConnectionSentences, and does
//     NOT import go/ast, go/parser or go/token — it cannot be re-parsing Go
//     source instead.
//
// Note what is deliberately NOT here: any assertion of the shape
// `ConnectionSentences["x"] == x`. That compares a thing with itself — the
// catalog's values ARE the production constants — and would be green forever
// while proving nothing. Guard A (internal/api/connection_sentence_catalog_test.go)
// is what proves the catalog is honest.

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strconv"
	"strings"
	"testing"
	"unicode"

	"github.com/MoranWeissman/sharko/internal/api"
)

const generatorSource = "main.go"

// generatorScaffolding is every prose-shaped string literal this generator is
// allowed to contain: the header lines it writes into the output, and its own
// error text. Each is scaffolding ABOUT the contract, never a sentence FROM
// it.
//
// It is an exhaustive allowlist rather than a pattern, because "is this a
// product sentence or a generator's own words" is not something a pattern can
// decide — the header line "Code generated by …" is capitalised prose too. A
// list makes every addition a visible decision in a diff.
var generatorScaffolding = map[string]bool{
	"// Code generated by cmd/gen-connection-sentences. DO NOT EDIT.\n":               true,
	"// Source: internal/api/connection_sentences.go\n":                               true,
	"// Run `make generate-connection-sentences` to refresh.\n":                       true,
	"// Every sentence the server authors for the connection surface, keyed by the\n": true,
	"// identifier the server owns. Render these by identifier. Never type one of\n":  true,
	"// these sentences into browser code, and never match on the text of one:\n":     true,
	"// a copy drifts the moment the server edits the wording, and a text match\n":    true,
	"// silently stops matching at the same moment.\n":                                true,
	"export const CONNECTION_SENTENCES = {\n":                                         true,
	"export type ConnectionSentenceId = keyof typeof CONNECTION_SENTENCES\n":          true,
	"path to the TypeScript file to (over)write":                                      true,
	"gen-connection-sentences: %v\n":                                                  true,
	"gen-connection-sentences: wrote %d sentences and %d failure messages to %s\n":    true,
	"the sentence catalog is empty — refusing to write an empty contract to %s":       true,
	// The parameterized failure family (story P2c).
	"// The connection-test failure family, already assembled by the server. Each\n":      true,
	"// entry is the FINISHED sentence for one connection kind and one failure\n":         true,
	"// code. The response carries the finished sentence and its identifier, so\n":        true,
	"// render what the server sent; these are here for the offline case only.\n":         true,
	"// Never join a fragment to a hint in browser code — that is the second\n":           true,
	"// formatter this contract exists to remove.\n":                                      true,
	"export const CONNECTION_FAILURE_MESSAGES = {\n":                                      true,
	"export type ConnectionFailureMessageId = keyof typeof CONNECTION_FAILURE_MESSAGES\n": true,
	"the failure-message catalog is empty — refusing to write an empty contract to %s":    true,
	// Error-wrapping formats. Developer-facing, never rendered to a user.
	"render: %w":             true,
	"mkdir %s: %w":           true,
	"write %s: %w":           true,
	"sentence %q: %w":        true,
	"failure message %q: %w": true,
}

// generatorLiterals returns every string literal in the generator's source.
func generatorLiterals(t *testing.T) map[string]int {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, generatorSource, nil, 0)
	if err != nil {
		t.Fatalf("parsing %s: %v", generatorSource, err)
	}
	out := map[string]int{}
	ast.Inspect(file, func(n ast.Node) bool {
		lit, ok := n.(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			return true
		}
		text, unquoteErr := strconv.Unquote(lit.Value)
		if unquoteErr != nil {
			return true
		}
		out[text] = fset.Position(lit.Pos()).Line
		return true
	})
	if len(out) == 0 {
		t.Fatalf("no string literals were found in %s at all — this guard has lost its reach", generatorSource)
	}
	return out
}

// catalogedSentences is every sentence the generator must not hold a copy of:
// the fixed catalog AND the parameterized failure family. The failure family
// matters most here — its sentences are ASSEMBLED, so a generator that grew
// its own copy of a fragment or a hint would be rebuilding the very
// concatenation the ruling forbids the browser to reproduce.
func catalogedSentences() map[string]string {
	all := map[string]string{}
	for id, sentence := range api.ConnectionSentences {
		all[id] = sentence
	}
	for _, f := range api.ConnectionFailureMessages {
		all[f.ID] = f.Sentence
	}
	return all
}

// TestGenerator_HoldsNoCopyOfAnySentence is the exact half of Guard B.
func TestGenerator_HoldsNoCopyOfAnySentence(t *testing.T) {
	literals := generatorLiterals(t)

	for text, line := range literals {
		for id, sentence := range catalogedSentences() {
			// A whole sentence pasted in, or a sentence pasted into a longer
			// literal.
			if strings.Contains(text, sentence) {
				t.Errorf("%s:%d holds the catalogued sentence %q (%s).\n"+
					"The generator must read the words from api.ConnectionSentences, never carry them.",
					generatorSource, line, sentence, id)
			}
			// A truncated or partial copy. The floor keeps ordinary words
			// ("json", "write") from matching by accident while still catching
			// a recognisable fragment of a sentence.
			if len(text) >= 12 && strings.Contains(sentence, text) {
				t.Errorf("%s:%d holds %q, which is a fragment of the catalogued sentence %s.\n"+
					"A partial copy drifts exactly like a whole one.",
					generatorSource, line, text, id)
			}
		}
	}
}

// TestGenerator_HoldsNoUnexpectedProse is the shape half of Guard B: it fails
// on ANY prose-shaped literal that is not declared scaffolding, so a sentence
// added to this file has to be argued for rather than merely not-noticed.
func TestGenerator_HoldsNoUnexpectedProse(t *testing.T) {
	literals := generatorLiterals(t)

	var unexpected []string
	seen := map[string]bool{}
	for text, line := range literals {
		if generatorScaffolding[text] {
			seen[text] = true
			continue
		}
		if !proseShaped(text) {
			continue
		}
		unexpected = append(unexpected, strconv.Itoa(line)+": "+strconv.Quote(text))
	}
	if len(unexpected) > 0 {
		sort.Strings(unexpected)
		t.Errorf("%s holds prose-shaped string literal(s) that are not declared scaffolding:\n  %s\n"+
			"If this is a product sentence it belongs in internal/api/connection_sentences.go, not here.\n"+
			"If it is genuinely the generator's own words, add it to generatorScaffolding.",
			generatorSource, strings.Join(unexpected, "\n  "))
	}

	// Stale scaffolding rots the same way a stale catalog entry does: it makes
	// the allowlist look bigger than the ground it actually covers.
	for text := range generatorScaffolding {
		if !seen[text] {
			t.Errorf("generatorScaffolding declares %q, which no longer appears in %s — remove the stale entry.",
				text, generatorSource)
		}
	}
}

// proseShaped reports whether a literal reads like a sentence: an uppercase or
// comment/keyword opening plus a space. It is deliberately WIDER than the
// catalog's own rule, because a guard that has to be over-eager is the right
// kind of guard here — a false positive costs one line in the allowlist, a
// false negative costs the whole point of the file.
func proseShaped(s string) bool {
	if !strings.Contains(s, " ") {
		return false
	}
	trimmed := strings.TrimLeft(s, "/ \t\n")
	for _, r := range trimmed {
		return unicode.IsUpper(r) || unicode.IsLower(r)
	}
	return false
}

// TestGenerator_ReadsTheCatalogAtRuntime is the structural half: the generator
// imports the api package and reads the catalog variable, and imports no Go
// source parser at all.
func TestGenerator_ReadsTheCatalogAtRuntime(t *testing.T) {
	src, err := os.ReadFile(generatorSource)
	if err != nil {
		t.Fatalf("reading %s: %v", generatorSource, err)
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, generatorSource, src, 0)
	if err != nil {
		t.Fatalf("parsing %s: %v", generatorSource, err)
	}

	imports := map[string]bool{}
	for _, imp := range file.Imports {
		path, unquoteErr := strconv.Unquote(imp.Path.Value)
		if unquoteErr != nil {
			continue
		}
		imports[path] = true
	}
	if !imports["github.com/MoranWeissman/sharko/internal/api"] {
		t.Error("the generator does not import internal/api — it cannot be reading the real catalog")
	}
	// If it ever grows a Go source parser it has stopped reading the catalog
	// and started guessing at it, and an aliased constant is exactly what a
	// parser gets wrong.
	for _, banned := range []string{"go/ast", "go/parser", "go/token", "go/types"} {
		if imports[banned] {
			t.Errorf("the generator imports %q — it must read api.ConnectionSentences at runtime, never re-parse Go source. "+
				"A parser sees an identifier where an aliased sentence should be.", banned)
		}
	}

	readsCatalog := map[string]bool{}
	ast.Inspect(file, func(n ast.Node) bool {
		sel, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		ident, ok := sel.X.(*ast.Ident)
		if ok && ident.Name == "api" && sel.Sel != nil {
			readsCatalog[sel.Sel.Name] = true
		}
		return true
	})
	for _, name := range []string{"ConnectionSentences", "ConnectionFailureMessages"} {
		if !readsCatalog[name] {
			t.Errorf("the generator never references api.%s — whatever it writes for that family did not come from the catalog", name)
		}
	}
}

// TestGenerator_RendersWhatTheCatalogHolds drives the renderer over the REAL
// catalog and checks the words that come out are the words that went in.
//
// This is not a self-comparison: it exercises the renderer, asserting that
// what it emitted for an identifier is what the catalog holds for that
// identifier. The catalog's own honesty is Guard A's job.
func TestGenerator_RendersWhatTheCatalogHolds(t *testing.T) {
	out, err := renderTypeScript(api.ConnectionSentences, api.ConnectionFailureMessages)
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	for id, sentence := range catalogedSentences() {
		quoted, quoteErr := quoteForTypeScript(sentence)
		if quoteErr != nil {
			t.Fatalf("quoting %s: %v", id, quoteErr)
		}
		want := "  " + id + ": " + quoted + ",\n"
		if !strings.Contains(out, want) {
			t.Errorf("the rendered file does not carry %s as the catalog holds it.\nwant line: %s", id, want)
		}
	}

	for _, fixed := range []string{
		"// Code generated by cmd/gen-connection-sentences. DO NOT EDIT.",
		"// Source: internal/api/connection_sentences.go",
		"// Run `make generate-connection-sentences` to refresh.",
		"export const CONNECTION_SENTENCES = {",
		"} as const",
		"export type ConnectionSentenceId = keyof typeof CONNECTION_SENTENCES",
		"export const CONNECTION_FAILURE_MESSAGES = {",
		"export type ConnectionFailureMessageId = keyof typeof CONNECTION_FAILURE_MESSAGES",
	} {
		if !strings.Contains(out, fixed) {
			t.Errorf("the rendered file is missing the fixed line %q", fixed)
		}
	}

	// No commit SHA. A revision stamp churns the file on every unrelated
	// commit and produces "out of date" failures about correct content.
	for _, churn := range []string{"Revision:", "Commit:", "Generated at", "git rev-parse"} {
		if strings.Contains(out, churn) {
			t.Errorf("the header carries %q — a revision or timestamp stamp churns the file on every unrelated commit", churn)
		}
	}
}

// TestGenerator_OutputIsDeterministic proves the sort is doing its job: Go
// randomises map iteration, so an unsorted render would differ between runs
// over the same catalog and the CI diff check would flap.
func TestGenerator_OutputIsDeterministic(t *testing.T) {
	first, err := renderTypeScript(api.ConnectionSentences, api.ConnectionFailureMessages)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	for i := 0; i < 20; i++ {
		again, againErr := renderTypeScript(api.ConnectionSentences, api.ConnectionFailureMessages)
		if againErr != nil {
			t.Fatalf("render %d: %v", i, againErr)
		}
		if again != first {
			t.Fatalf("render %d differs from the first — the output is not deterministic and CI would flap", i)
		}
	}

	// And the keys really are in sorted order, per emitted block. Read BY
	// NAME, not by counting lines: the file holds two blocks now, and a rule
	// that only knew how many entries there ought to be in total would go on
	// passing while one block emptied and the other doubled.
	sentenceIDs := emittedIDs(first, "export const CONNECTION_SENTENCES = {")
	failureIDs := emittedIDs(first, "export const CONNECTION_FAILURE_MESSAGES = {")

	for _, block := range []struct {
		name string
		ids  []string
	}{
		{"CONNECTION_SENTENCES", sentenceIDs},
		{"CONNECTION_FAILURE_MESSAGES", failureIDs},
	} {
		if len(block.ids) == 0 {
			t.Fatalf("%s emitted no identifiers at all — this check has lost its reach", block.name)
		}
		if !sort.StringsAreSorted(block.ids) {
			t.Errorf("the identifiers in %s are not in sorted order", block.name)
		}
	}

	// Every catalogued identifier is present, named one by one when it is not.
	emitted := map[string]bool{}
	for _, id := range append(append([]string{}, sentenceIDs...), failureIDs...) {
		emitted[id] = true
	}
	for id := range catalogedSentences() {
		if !emitted[id] {
			t.Errorf("the catalog holds %q but the emitted file does not", id)
		}
	}
	for id := range emitted {
		if _, ok := catalogedSentences()[id]; !ok {
			t.Errorf("the emitted file holds %q, which is in no catalog", id)
		}
	}
}

// emittedIDs returns the identifiers of the `as const` block that opens with
// the given line.
func emittedIDs(rendered, opener string) []string {
	var ids []string
	inBlock := false
	for _, line := range strings.Split(rendered, "\n") {
		if line == opener {
			inBlock = true
			continue
		}
		if !inBlock {
			continue
		}
		if strings.HasPrefix(line, "} as const") {
			break
		}
		if !strings.HasPrefix(line, "  ") || !strings.Contains(line, ": ") {
			continue
		}
		ids = append(ids, strings.TrimSpace(strings.SplitN(line, ":", 2)[0]))
	}
	return ids
}

// TestGenerator_QuotesAwkwardCharactersAsValidTypeScript covers the characters
// these sentences actually carry — apostrophes, an em dash, a backtick — plus
// the astral-plane case Go's own strconv.Quote would render with a `\U`
// escape JavaScript does not have.
func TestGenerator_QuotesAwkwardCharactersAsValidTypeScript(t *testing.T) {
	cases := []struct{ in, want string }{
		// An apostrophe: everywhere in these sentences.
		{"This cluster's record", `"This cluster's record"`},
		// An em dash: in the headlines.
		{"Out of sync — approval required", `"Out of sync — approval required"`},
		// A backtick: in LimitReasonEKSNoStoredCredential. It must stay a
		// literal backtick — TypeScript only treats it as a template
		// delimiter inside backtick-quoted strings, and these are
		// double-quoted.
		{"compare with \x60data.config\x60.", "\"compare with \x60data.config\x60.\""},
		{`a "quoted" word`, `"a \"quoted\" word"`},
		{"a\ttab", `"a\ttab"`},
	}

	for _, tc := range cases {
		in, want := tc.in, tc.want
		got, err := quoteForTypeScript(in)
		if err != nil {
			t.Fatalf("quoting %q: %v", in, err)
		}
		if got != want {
			t.Errorf("quoteForTypeScript(%q) = %s, want %s", in, got, want)
		}
	}

	// An astral-plane rune must come out as a surrogate pair, never Go's
	// `\U0001F600`, which is not JavaScript syntax.
	got, err := quoteForTypeScript("hi \U0001F600")
	if err != nil {
		t.Fatalf("quoting an astral rune: %v", err)
	}
	if strings.Contains(got, `\U`) {
		t.Errorf("an astral rune was rendered with a Go-only \\U escape, which TypeScript cannot parse: %s", got)
	}
}
