package contentsweep

// content_sweep_test.go — reads every tracked text file in this repository and
// fails on a credential-shaped string or an email address on a domain this
// project does not use.
//
// # What this checks, and what it deliberately does not
//
// The content policy for this repository says no references to the original
// organisation the code came from, no internal domains, no employee email
// addresses and no real AWS account ids, anywhere in code or documentation.
// This sweep is what tests that policy.
//
// It is NOT a secret scanner and must never be described as one. The hosting
// platform already refuses live AWS keys and live GitHub tokens at push time.
// What the platform does not look at, and this sweep does:
//
//   - the organisation policy above — an address on a corporate mail domain, a
//     real twelve-digit AWS account id
//   - credential-shaped strings that are not live secrets: a revoked key, a
//     realistic-looking fake, a token pasted into a fixture. Those are refused
//     by nothing, and they are still content that must not be published.
//   - it runs under plain `go test ./...`, so a developer sees the problem
//     before the push instead of after it
//
// # Why the organisation is never named in this file
//
// The obvious way to test "no references to the original organisation" is to
// grep for its name. That cannot be done here: the test file would have to
// contain the very string the policy exists to keep out of a public repository,
// and this file is published like every other.
//
// So the rule is inverted. Email addresses are checked against an allowlist of
// the domains this project legitimately uses, and anything else fails. A
// corporate address is then refused without this file ever spelling out whose
// it is. The same reasoning applies to the twelve-digit AWS account ids: the
// documentation placeholders are listed, and any other twelve-digit number
// fails.
//
// # Why a Go test rather than a grep loop in the workflow
//
// This repository has been bitten twice by shell gates: a chart check that
// rendered nothing and still reported success for weeks, and a set of
// break-tests that passed for the wrong reason because brace expansion ate a
// JSON literal. A Go test gets real regular expressions, real path handling and
// a real data structure for the exceptions, and it runs locally with no extra
// tooling.
//
// # Fail closed, always
//
// A sweep that reads nothing looks exactly like a sweep that read everything
// and found nothing. So this fails rather than passes when it cannot do its
// job: when the repository root cannot be found, when listing the tracked files
// errors, when that list is empty, when a tracked file cannot be read, and when
// no readable text file was scanned at all. TestSweepReallyReadsTheTrackedTree
// in this package is the second half of that guard.

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// sweepDir is this package's own directory, relative to the repository root.
//
// It is the one and only exclusion of source files here, and it is needed
// because this file has to contain every pattern and every allowed value it
// searches for — scanning it would be circular and would fail on its own
// contents. Everything else in the tree is read, `.go` files very much
// included: a committed credential would land in a `.go` file more likely than
// anywhere else, so a blanket file-type skip would gut the whole sweep. There
// is no such skip anywhere below.
const sweepDir = "tests/contentsweep"

// machineGeneratedFiles are resolved-dependency manifests. Nothing in them is
// written by hand here, they change wholesale on every dependency bump, and
// they carry thousands of registry URLs and integrity hashes. A finding in one
// of them would be a finding about an upstream package, not about this
// repository's content.
var machineGeneratedFiles = map[string]string{
	"ui/package-lock.json": "npm-resolved dependency tree, regenerated by the package manager",
	"go.sum":               "Go module checksum database, regenerated by the go tool",
}

// binarySniffBytes is how much of a file's head is examined for a NUL byte to
// decide it is binary. This is the same rule git itself uses.
const binarySniffBytes = 8192

// credentialPattern is one shape of string that must not be committed. The
// name is what gets printed in a failure, so it reads as an explanation rather
// than as a regular expression.
type credentialPattern struct {
	name string
	re   *regexp.Regexp
}

// awsAccountIDPattern is named so the account-id placeholder allowlist can be
// applied to it and to nothing else.
const awsAccountIDPattern = "twelve-digit AWS account id"

var credentialPatterns = []credentialPattern{
	{
		name: "AWS access key id",
		re:   regexp.MustCompile(`(?:AKIA|ASIA)[0-9A-Z]{16}`),
	},
	{
		name: "GitHub token",
		re:   regexp.MustCompile(`gh[pousr]_[A-Za-z0-9]{16,}`),
	},
	{
		name: "Slack token",
		re:   regexp.MustCompile(`xox[abprs]-[0-9A-Za-z-]{10,}`),
	},
	{
		name: "private key block",
		re:   regexp.MustCompile(`BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY`),
	},
	{
		name: awsAccountIDPattern,
		re:   regexp.MustCompile(`\b[0-9]{12}\b`),
	},
}

// emailPattern finds anything shaped like an email address. The domain half is
// then checked against the allowlists below.
var emailPattern = regexp.MustCompile(`[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}`)

// allowedEmailDomains are the exact mail domains this project legitimately
// carries. The value is why each one is legitimate, so a reviewer can judge a
// new entry instead of taking it on trust.
var allowedEmailDomains = map[string]string{
	"company.com":              "generic placeholder used by the test-authoring guidance under .claude/skills",
	"example.com":              "reserved for documentation by RFC 2606; the project's default example address",
	"github.com":               "the public code host this project is published on",
	"gmail.com":                "the maintainer's own address, which every commit sign-off carries",
	"ollama.internal":          "made-up host in the documented-examples test for the local model server address",
	"test.com":                 "generic placeholder used by the test-authoring guidance under .claude/skills",
	"users.noreply.github.com": "the code host's own no-reply domain, used by the bot commit identity",
	"x.io":                     "short throwaway domain in the commit-attribution tests",
}

// allowedEmailDomainSuffixes are whole families of names that cannot belong to
// a real organisation, so listing every child would be busywork.
var allowedEmailDomainSuffixes = map[string]string{
	".example":     "second-level names under the RFC 2606 reserved example TLD",
	".example.com": "sub-domains of the RFC 2606 reserved documentation domain",
	".invalid":     "reserved by RFC 2606 and guaranteed never to resolve",
	".other":       "not delegated in the DNS root, so it cannot be a real address; used by an ArgoCD test fixture",
	".test":        "reserved by RFC 6761 for testing",
	".local":       "reserved by RFC 6762 for link-local names",
	".localhost":   "reserved by RFC 6761 for the loopback host",
}

// allowedAWSAccountIDs are the placeholder account numbers the documentation
// and the tests use. Two of them are the placeholders AWS puts in its own
// documentation; the rest are obvious counting patterns. Any other
// twelve-digit number fails, which is the whole point: a real account id looks
// nothing like these.
var allowedAWSAccountIDs = map[string]string{
	"123456789012": "the placeholder account number AWS uses throughout its own documentation",
	"111122223333": "the second placeholder account number AWS uses in its own documentation",
	"000000000000": "all-zero placeholder for 'no account known yet' in fixtures and demo data",
	"111111111111": "all-ones placeholder for a second account in the live-script guard test",
	"234567890123": "counting placeholder for the spoke account in the hub-and-spoke identity guide",
	"987654321098": "reverse-counting placeholder for the target account in the IAM setup guide",
}

// allowedSentinels lists the deliberate credential-shaped strings already in
// the tree, keyed by the exact file each one is allowed to appear in. Every
// entry is a value that exists on purpose to prove a redaction or leak guard
// works.
//
// The exception is the PAIR (file path, exact matched text), and that shape is
// the deliberate part:
//
//   - a NEW credential shape added to a file already listed here FAILS. These
//     are precisely the files most likely to gain another sentinel, and a new
//     one should be looked at by a person.
//   - a listed sentinel MOVED or copied into a different file FAILS. The path
//     half is enforced, so "it is already allowed somewhere" is not a pass.
//
// Two shapes that were considered and rejected: skipping every `_test.go` file
// (test files are published code, so a real token pasted into one would pass
// forever) and allowing a path with no value check (which silently passes any
// new credential in an already-listed file).
//
// The cost is one line of diff whenever someone deliberately adds a sentinel.
// That is the feature, not the friction: the line is visible in review and
// somebody has to agree with it, instead of the gate quietly going green.
var allowedSentinels = map[string][]string{
	// The AI-annotation guard must be proven to strip a key id and a key block
	// out of text on its way to a model provider.
	"internal/api/ai_annotate_secret_guard_test.go": {
		"AKIAIOSFODNN7EXAMPLE",
		"BEGIN RSA PRIVATE KEY",
	},
	// Proves an ArgoCD address carrying a token in the userinfo position never
	// reaches a response body.
	"internal/api/argocd_address_leak_test.go": {
		"ghp_1234567890abcdefghij",
	},
	// Proves a connection-failure sentence never repeats the token it failed
	// with.
	"internal/api/connection_failure_messages_test.go": {
		"ghp_SENTINELtokenVALUE1234567890",
	},
	// Proves the notification payloads carry no credential from the old
	// notification path.
	"internal/api/notifications_legacy_leak_test.go": {
		"ghp_APISENTINEL0123456789abcdefABCDEFxy",
	},
	// Proves the log sink rewrites a key block instead of printing it.
	"internal/logging/redact_test.go": {
		"BEGIN PRIVATE KEY",
	},
	// Proves a stored connection never marshals its token.
	"internal/models/connection_test.go": {
		"ghp_1234567890abcdef",
	},
	// Proves a notification never carries the token that produced it.
	"internal/notifications/sentinel_leak_test.go": {
		"ghp_SHARKOSENTINEL0123456789abcdefABCDEF",
	},
	// Proves annotation text handed to a model provider is stripped first.
	"internal/orchestrator/ai_annotate_test.go": {
		"AKIAIOSFODNN7EXAMPLE",
	},
	// The redaction guard itself. Not a test file: it has to name the shapes it
	// strips in order to strip them, so its own source matches. This is the one
	// non-test entry and it is why an allowlist keyed on `_test.go` would not
	// have worked anyway.
	"internal/orchestrator/ai_guard.go": {
		"AKIAIOSFODNN7EXAMPLE",
	},
	// Proves nothing the guard is supposed to strip survives into a tool result.
	"internal/orchestrator/ai_guard_leak_test.go": {
		"AKIAIOSFODNN7EXAMPLE",
		"BEGIN OPENSSH PRIVATE KEY",
		"BEGIN RSA PRIVATE KEY",
		"xoxb-1234567890-",
	},
	// The guard's own table of shapes it must catch.
	"internal/orchestrator/ai_guard_test.go": {
		"AKIAIOSFODNN7EXAMPLE",
		"ASIA0123456789ABCDEF",
		"BEGIN OPENSSH PRIVATE KEY",
		"ghp_1234567890abcdefABCDEF1234567890abcdef",
		"xoxb-1234567890-abcdefghijklm",
	},
}

// howToFixAFinding is printed with every failure. It says what an acceptable
// fix is and, just as importantly, what is not.
const howToFixAFinding = `
How to deal with the lines above:

  - If a value is a real credential, or a real address, or a real account
    number: remove it from the file AND rotate or revoke it. Deleting it from
    the working tree does not remove it from the history.
  - If a value is a DELIBERATE sentinel that proves a guard works: add it to
    allowedSentinels in tests/contentsweep/content_sweep_test.go as an exact
    (file path, exact text) pair, with a comment saying what it proves.
  - If an email address is on a domain this project should use: add that domain
    to allowedEmailDomains with the reason it is legitimate.

Not acceptable: widening a pattern so it stops matching, adding a file-type
exclusion, or skipping a directory. Any of those makes this check green while
the content it exists to keep out is still published.`

// repoRoot walks up from the test's working directory until it finds the
// directory holding go.mod. It never guesses: no go.mod found by the time the
// filesystem root is reached is a hard failure, because a wrong root would
// make the sweep read the wrong tree, or no tree at all, and report clean.
func repoRoot(t *testing.T) string {
	t.Helper()

	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("cannot read the working directory, so the repository root cannot be found: %v", err)
	}
	start := dir
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("walked from %s to the filesystem root without finding a go.mod, so there is no repository to sweep", start)
		}
		dir = parent
	}
}

// trackedFiles lists every file git has in the index, as paths relative to
// root. Tracked is the right set to sweep because tracked is what gets
// published, and it means a stray local directory, a build output or a
// leftover worktree can never be mistaken for part of the project.
func trackedFiles(t *testing.T, root string) []string {
	t.Helper()

	cmd := exec.Command("git", "ls-files", "-z")
	cmd.Dir = root
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("listing the tracked files in %s failed, so the sweep cannot say anything about this tree: %v\n%s",
			root, err, stderr.String())
	}

	var files []string
	for _, name := range strings.Split(string(out), "\x00") {
		if name != "" {
			files = append(files, name)
		}
	}
	if len(files) == 0 {
		t.Fatalf("git reported zero tracked files in %s; a sweep over nothing is not a pass", root)
	}
	return files
}

// excludedReason returns why a tracked path is not scanned, or an empty string
// when it is scanned. These are the only exclusions in the whole sweep.
func excludedReason(rel string) string {
	if reason, ok := machineGeneratedFiles[rel]; ok {
		return reason
	}
	if rel == sweepDir || strings.HasPrefix(rel, sweepDir+"/") {
		return "the sweep's own source, which must contain every pattern and value it searches for"
	}
	return ""
}

// looksBinary applies git's own rule: a NUL byte near the start means this is
// not text, so there are no lines to read and no sensible thing to report.
func looksBinary(data []byte) bool {
	head := data
	if len(head) > binarySniffBytes {
		head = head[:binarySniffBytes]
	}
	return bytes.IndexByte(head, 0) >= 0
}

func emailDomainAllowed(domain string) bool {
	if _, ok := allowedEmailDomains[domain]; ok {
		return true
	}
	for suffix := range allowedEmailDomainSuffixes {
		if strings.HasSuffix(domain, suffix) {
			return true
		}
	}
	return false
}

func sentinelAllowed(rel, matched string) bool {
	for _, allowed := range allowedSentinels[rel] {
		if allowed == matched {
			return true
		}
	}
	return false
}

// violationsInLine reports every problem on one line of one file, formatted as
// "path:line: what matched: the exact text" so the reader can go straight to
// it.
func violationsInLine(rel string, lineNo int, line string) []string {
	var out []string

	for _, pattern := range credentialPatterns {
		for _, matched := range pattern.re.FindAllString(line, -1) {
			if pattern.name == awsAccountIDPattern {
				if _, ok := allowedAWSAccountIDs[matched]; ok {
					continue
				}
			}
			if sentinelAllowed(rel, matched) {
				continue
			}
			out = append(out, fmt.Sprintf("%s:%d: %s: %s", rel, lineNo, pattern.name, matched))
		}
	}

	for _, address := range emailPattern.FindAllString(line, -1) {
		at := strings.LastIndex(address, "@")
		domain := strings.ToLower(address[at+1:])
		if emailDomainAllowed(domain) {
			continue
		}
		if sentinelAllowed(rel, address) {
			continue
		}
		out = append(out, fmt.Sprintf("%s:%d: email address on a domain this project does not use: %s", rel, lineNo, address))
	}

	return out
}

// TestTrackedFilesCarryNoForbiddenContent is the sweep.
func TestTrackedFilesCarryNoForbiddenContent(t *testing.T) {
	root := repoRoot(t)
	files := trackedFiles(t, root)

	var findings []string
	scanned := 0

	for _, rel := range files {
		if excludedReason(rel) != "" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			t.Fatalf("cannot read the tracked file %s, so the sweep cannot report on this tree: %v", rel, err)
		}
		if looksBinary(data) {
			continue
		}
		scanned++
		for i, line := range strings.Split(string(data), "\n") {
			findings = append(findings, violationsInLine(rel, i+1, line)...)
		}
	}

	if scanned == 0 {
		t.Fatalf("read %d tracked files and scanned none of them as text; that is a broken sweep, not a clean tree", len(files))
	}

	if len(findings) > 0 {
		sort.Strings(findings)
		t.Fatalf("content sweep found %d line(s) that must not be published:\n%s\n%s",
			len(findings), strings.Join(findings, "\n"), howToFixAFinding)
	}

	t.Logf("content sweep read %d text files out of %d tracked and found nothing", scanned, len(files))
}
