package service

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"

	"github.com/MoranWeissman/sharko/internal/argocd"
	"github.com/MoranWeissman/sharko/internal/config"
	"github.com/MoranWeissman/sharko/internal/gitprovider"
	"github.com/MoranWeissman/sharko/internal/models"
)

// ErrValidation marks an error as user-actionable input-validation failure
// rather than an internal failure. Handlers that receive an error wrapping
// this sentinel SHOULD respond with HTTP 400 and surface the underlying
// message — the message is generated by Sharko code (not an upstream
// service), so it's safe to expose and tells the user exactly which input
// to fix.
//
// Closes V124-3.3 (M4 — connections validation should be 400, not 500).
//
// Currently wrapped at:
//   - Create / Update — when ParseRepoURL fails (bad git URL)
//
// Add new wrap sites whenever a method validates user input and returns an
// error the operator can act on (missing field, malformed value, bad enum,
// etc.). DO NOT wrap upstream-service errors with it — those have their own
// classification path (writeUpstreamError, V124-3.2).
var ErrValidation = errors.New("validation failed")

// ConnectionService manages connections and provides active provider instances.
type ConnectionService struct {
	store               config.Store
	devMode             bool // when true, falls back to env vars for missing credentials
	gitProviderOverride gitprovider.GitProvider // when set, returned by GetActiveGitProvider (demo mode)
}

// NewConnectionService creates a new ConnectionService.
// devMode enables env var fallback for credentials (set SHARKO_DEV_MODE=true or config.devMode in Helm).
func NewConnectionService(store config.Store) *ConnectionService {
	devMode := os.Getenv("SHARKO_DEV_MODE") == "true"
	if devMode {
		slog.Info("connection service running in DEV MODE — env var credential fallback enabled")
	}
	return &ConnectionService{store: store, devMode: devMode}
}

// List returns all connections with masked tokens.
func (s *ConnectionService) List() (*models.ConnectionsListResponse, error) {
	connections, err := s.store.ListConnections()
	if err != nil {
		return nil, err
	}

	activeName, err := s.store.GetActiveConnection()
	if err != nil {
		return nil, err
	}

	responses := make([]models.ConnectionResponse, 0, len(connections))
	for _, c := range connections {
		// V124-4.2 / BUG-017 defensive read-side guard. Pre-V124-4 the Create
		// path persisted entries with an empty name on `POST {}` (no required-
		// field validation). Those entries are now rejected at write time, but
		// stores that already contain such garbage (e.g. the maintainer's demo
		// cluster from the BUG-017 reproducer) would still surface them via
		// List. We skip them here with a single warning per startup pass —
		// no destructive on-disk migration, just a read-time filter.
		if c.Name == "" {
			slog.Warn("connection skipped: empty name (legacy garbage from pre-V124-4 store)",
				"component", "connection-service")
			continue
		}
		responses = append(responses, c.ToResponse(c.Name == activeName))
	}

	return &models.ConnectionsListResponse{
		Connections:      responses,
		ActiveConnection: activeName,
	}, nil
}

// Create adds a new connection.
//
// Validation errors (currently: malformed Git URL) are wrapped with
// ErrValidation so the API layer can surface them as HTTP 400 with the
// underlying message visible to the operator (V124-3.3 / M4). Wrapping
// preserves the original error chain — callers can still errors.As for
// the concrete cause if they need it.
func (s *ConnectionService) Create(req models.CreateConnectionRequest) error {
	// V124-4.2 / BUG-017: required-field validation runs before any other
	// processing so an empty `{}` body fails fast with a 400 instead of
	// persisting a name="default" placeholder with no usable Git config.
	//
	// "Required" here is the minimum a connection needs to be useful:
	// a Git provider type AND a way to identify the repo (either an
	// explicit RepoURL or the per-provider identifier fields).
	if err := validateConnectionRequest(req); err != nil {
		return err
	}
	// Parse repo URL into provider/owner/repo if provided
	if err := req.Git.ParseRepoURL(); err != nil {
		return fmt.Errorf("invalid git URL: %w: %w", ErrValidation, err)
	}
	conn := models.Connection{
		Name:        req.Name,
		Description: req.Description,
		Git:         req.Git,
		Argocd:      req.Argocd,
		Provider:    req.Provider,
		GitOps:      req.GitOps,
		IsDefault:   req.SetAsDefault,
	}
	// Auto-derive connection name from git repo if not provided
	if conn.Name == "" || conn.Name == "default" {
		conn.Name = deriveConnectionName(conn.Git)
	}
	return s.store.SaveConnection(conn)
}

// validateConnectionRequest checks that the create/update request has the
// minimum fields needed for a usable connection. All errors are wrapped with
// ErrValidation so handlers surface them as 400 with the underlying message.
//
// Rules (V124-4.2 / BUG-017):
//   - git.provider must be set (so we know which Git backend to use)
//   - git.provider must be one of the supported values
//   - either git.repo_url is set (parsed downstream) OR the per-provider
//     identifier fields are set:
//       github      → owner + repo
//       azuredevops → organization + project + repository
//
// Token / PAT fields are NOT required at create time — the test-credentials
// endpoint and the env-var fallback (SHARKO_DEV_MODE) cover those flows.
//
// The handler `handleUpdateConnection` overlays empty token fields from the
// saved connection before calling Create, so update-with-partial-body still
// passes through this validator unchanged.
func validateConnectionRequest(req models.CreateConnectionRequest) error {
	if req.Git.Provider == "" {
		return fmt.Errorf("git.provider is required (one of: github, azuredevops): %w", ErrValidation)
	}
	switch req.Git.Provider {
	case models.GitProviderGitHub:
		if req.Git.RepoURL == "" && (req.Git.Owner == "" || req.Git.Repo == "") {
			return fmt.Errorf("git.repo_url or (git.owner + git.repo) is required for github provider: %w", ErrValidation)
		}
	case models.GitProviderAzureDevOps:
		if req.Git.RepoURL == "" && (req.Git.Organization == "" || req.Git.Project == "" || req.Git.Repository == "") {
			return fmt.Errorf("git.repo_url or (git.organization + git.project + git.repository) is required for azuredevops provider: %w", ErrValidation)
		}
	default:
		return fmt.Errorf("git.provider %q is not supported (must be one of: github, azuredevops): %w", req.Git.Provider, ErrValidation)
	}
	return nil
}

// deriveConnectionName builds a connection name from the git config.
func deriveConnectionName(git models.GitRepoConfig) string {
	switch git.Provider {
	case models.GitProviderGitHub:
		if git.Owner != "" && git.Repo != "" {
			return git.Owner + "/" + git.Repo
		}
	case models.GitProviderAzureDevOps:
		if git.Organization != "" && git.Project != "" && git.Repository != "" {
			return git.Organization + "/" + git.Project + "/" + git.Repository
		}
	}
	return "default"
}

// GetConnection returns a connection by name.
func (s *ConnectionService) GetConnection(name string) (*models.Connection, error) {
	return s.store.GetConnection(name)
}

// Delete removes a connection.
func (s *ConnectionService) Delete(name string) error {
	return s.store.DeleteConnection(name)
}

// SetActive sets the active connection.
func (s *ConnectionService) SetActive(name string) error {
	slog.Info("active connection changed", "connection", name)
	return s.store.SetActiveConnection(name)
}

// GitProviderOverride is an alias for gitprovider.GitProvider, exported so that
// callers (e.g. api.Server) can reference the type without importing gitprovider.
type GitProviderOverride = gitprovider.GitProvider

// SetGitProviderOverride installs a fixed GitProvider that bypasses connection
// lookup. Used in demo/test mode to inject a mock provider.
func (s *ConnectionService) SetGitProviderOverride(p gitprovider.GitProvider) {
	s.gitProviderOverride = p
}

// GetActiveGitProvider returns a GitProvider for the currently active connection.
func (s *ConnectionService) GetActiveGitProvider() (gitprovider.GitProvider, error) {
	if s.gitProviderOverride != nil {
		return s.gitProviderOverride, nil
	}
	conn, err := s.getActiveConn()
	if err != nil {
		return nil, err
	}
	return s.buildGitProvider(conn)
}

// GetActiveArgocdClient returns an ArgoCD client for the currently active connection.
// If server_url is empty, it uses in-cluster mode with the pod's ServiceAccount token.
func (s *ConnectionService) GetActiveArgocdClient() (*argocd.Client, error) {
	conn, err := s.getActiveConn()
	if err != nil {
		return nil, err
	}
	return s.buildArgocdClient(conn)
}

func (s *ConnectionService) buildArgocdClient(conn *models.Connection) (*argocd.Client, error) {
	token := conn.Argocd.Token
	serverURL := conn.Argocd.ServerURL

	// Dev mode: fall back to env vars
	if s.devMode {
		if token == "" {
			token = os.Getenv("ARGOCD_TOKEN")
			if token != "" {
				slog.Info("argocd: using ARGOCD_TOKEN env var (dev mode fallback)")
			}
		}
		if serverURL == "" {
			serverURL = os.Getenv("ARGOCD_SERVER_URL")
		}
	}

	// Auto-discover server URL if still empty
	if serverURL == "" {
		ns := conn.Argocd.Namespace
		if ns == "" {
			ns = "argocd"
		}
		serverURL = argocd.DiscoverServerURL(ns)
	}

	if token == "" {
		return nil, fmt.Errorf("ArgoCD token not configured. Provide it via Settings UI or set ARGOCD_TOKEN env var with SHARKO_DEV_MODE=true")
	}

	return argocd.NewClient(serverURL, token, true), nil
}

// GetGitProviderForConnection returns a GitProvider for a specific named connection.
func (s *ConnectionService) GetGitProviderForConnection(name string) (gitprovider.GitProvider, error) {
	conn, err := s.store.GetConnection(name)
	if err != nil {
		return nil, err
	}
	if conn == nil {
		return nil, fmt.Errorf("connection %q not found", name)
	}
	return s.buildGitProvider(conn)
}

// TestConnection tests both Git and ArgoCD connectivity for the active connection.
func (s *ConnectionService) TestConnection(ctx context.Context) (gitErr, argocdErr error) {
	conn, err := s.getActiveConn()
	if err != nil {
		return err, err
	}

	gp, err := s.buildGitProvider(conn)
	if err != nil {
		gitErr = err
	} else {
		gitErr = gp.TestConnection(ctx)
	}

	ac, err := s.buildArgocdClient(conn)
	if err != nil {
		argocdErr = err
	} else {
		argocdErr = ac.TestConnection(ctx)
	}

	return gitErr, argocdErr
}

// AuthInfo describes which auth method was used for each service.
type AuthInfo struct {
	GitSource    string // "provided", "env:GITHUB_TOKEN", ""
	ArgocdSource string // "provided", "env:ARGOCD_TOKEN", "serviceaccount", ""
}

// TestCredentials tests Git and ArgoCD connectivity for unsaved credentials.
func (s *ConnectionService) TestCredentials(ctx context.Context, conn *models.Connection) (gitErr, argocdErr error, auth AuthInfo) {
	// Parse repo URL if provided
	if err := conn.Git.ParseRepoURL(); err != nil {
		return err, nil, auth
	}

	// Track git auth source
	if conn.Git.Token != "" {
		auth.GitSource = "provided"
	} else if os.Getenv("GITHUB_TOKEN") != "" {
		auth.GitSource = "env:GITHUB_TOKEN"
	}

	gp, err := s.buildGitProvider(conn)
	if err != nil {
		gitErr = err
	} else {
		gitErr = gp.TestConnection(ctx)
	}

	// Track argocd auth source
	if conn.Argocd.Token != "" {
		auth.ArgocdSource = "provided"
	} else if os.Getenv("ARGOCD_TOKEN") != "" {
		auth.ArgocdSource = "env:ARGOCD_TOKEN"
	} else {
		auth.ArgocdSource = "serviceaccount"
	}

	ac, err := s.buildArgocdClient(conn)
	if err != nil {
		argocdErr = err
	} else {
		argocdErr = ac.TestConnection(ctx)
	}

	return gitErr, argocdErr, auth
}

// DiscoverArgocdURL finds the ArgoCD server URL for the given namespace.
func (s *ConnectionService) DiscoverArgocdURL(namespace string) string {
	return argocd.DiscoverServerURL(namespace)
}

// GetActiveConnection returns the active connection with its full configuration.
// Returns nil (not an error) when no active connection is configured.
func (s *ConnectionService) GetActiveConnection() (*models.Connection, error) {
	activeName, err := s.store.GetActiveConnection()
	if err != nil {
		return nil, err
	}
	if activeName == "" {
		return nil, nil
	}
	return s.store.GetConnection(activeName)
}

// GetActiveConnectionInfo returns the active connection with its full configuration.
// This is used by API handlers that need access to raw credentials (e.g., for ArgoCD repo registration).
func (s *ConnectionService) GetActiveConnectionInfo() (*models.Connection, error) {
	return s.getActiveConn()
}

// GetProviderConfig returns the provider config from the active connection, or nil if not set.
// Callers should fall back to env vars when this returns nil.
func (s *ConnectionService) GetProviderConfig() *models.ProviderConfig {
	conn, err := s.getActiveConn()
	if err != nil || conn == nil {
		return nil
	}
	return conn.Provider
}

func (s *ConnectionService) getActiveConn() (*models.Connection, error) {
	activeName, err := s.store.GetActiveConnection()
	if err != nil {
		return nil, err
	}
	if activeName == "" {
		return nil, fmt.Errorf("no active connection configured")
	}

	conn, err := s.store.GetConnection(activeName)
	if err != nil {
		return nil, err
	}
	if conn == nil {
		return nil, fmt.Errorf("active connection %q not found", activeName)
	}

	return conn, nil
}

func (s *ConnectionService) buildGitProvider(conn *models.Connection) (gitprovider.GitProvider, error) {
	switch conn.Git.Provider {
	case models.GitProviderGitHub:
		token := conn.Git.Token
		if token == "" && s.devMode {
			token = os.Getenv("GITHUB_TOKEN")
			if token != "" {
				slog.Info("git: using GITHUB_TOKEN env var (dev mode fallback)")
			}
		}
		if token == "" {
			return nil, fmt.Errorf("GitHub token not configured. Provide it via Settings UI or set GITHUB_TOKEN env var with SHARKO_DEV_MODE=true")
		}
		return gitprovider.NewGitHubProvider(conn.Git.Owner, conn.Git.Repo, token), nil
	case models.GitProviderAzureDevOps:
		pat := conn.Git.PAT
		if pat == "" && s.devMode {
			pat = os.Getenv("AZURE_DEVOPS_PAT")
			if pat != "" {
				slog.Info("git: using AZURE_DEVOPS_PAT env var (dev mode fallback)")
			}
		}
		if pat == "" {
			return nil, fmt.Errorf("Azure DevOps PAT not configured. Provide it via Settings UI or set AZURE_DEVOPS_PAT env var with SHARKO_DEV_MODE=true")
		}
		return gitprovider.NewAzureDevOpsProvider(conn.Git.Organization, conn.Git.Project, conn.Git.Repository, pat), nil
	default:
		return nil, fmt.Errorf("unsupported git provider: %s", conn.Git.Provider)
	}
}
