package service

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"

	"github.com/MoranWeissman/sharko/internal/argocd"
	"github.com/MoranWeissman/sharko/internal/config"
	"github.com/MoranWeissman/sharko/internal/gitprovider"
	"github.com/MoranWeissman/sharko/internal/models"
)

// ErrValidation marks an error as user-actionable input-validation failure
// rather than an internal failure. Handlers that receive an error wrapping
// this sentinel SHOULD respond with HTTP 400 and surface the underlying
// message — the message is generated by Sharko code (not an upstream
// service), so it's safe to expose and tells the user exactly which input
// to fix.
//
// Closes V124-3.3 (M4 — connections validation should be 400, not 500).
//
// Currently wrapped at:
//   - Create / Update — when ParseRepoURL fails (bad git URL)
//
// Add new wrap sites whenever a method validates user input and returns an
// error the operator can act on (missing field, malformed value, bad enum,
// etc.). DO NOT wrap upstream-service errors with it — those have their own
// classification path (writeUpstreamError, V124-3.2).
var ErrValidation = errors.New("validation failed")

// ConnectionService manages connections and provides active provider instances.
type ConnectionService struct {
	store               config.Store
	devMode             bool // when true, falls back to env vars for missing credentials
	gitProviderOverride gitprovider.GitProvider // when set, returned by GetActiveGitProvider (demo mode)
}

// NewConnectionService creates a new ConnectionService.
// devMode enables env var fallback for credentials (set SHARKO_DEV_MODE=true or config.devMode in Helm).
func NewConnectionService(store config.Store) *ConnectionService {
	devMode := os.Getenv("SHARKO_DEV_MODE") == "true"
	if devMode {
		slog.Info("connection service running in DEV MODE — env var credential fallback enabled")
	}
	return &ConnectionService{store: store, devMode: devMode}
}

// List returns all connections with masked tokens.
func (s *ConnectionService) List() (*models.ConnectionsListResponse, error) {
	connections, err := s.store.ListConnections()
	if err != nil {
		return nil, err
	}

	activeName, err := s.store.GetActiveConnection()
	if err != nil {
		return nil, err
	}

	responses := make([]models.ConnectionResponse, 0, len(connections))
	for _, c := range connections {
		// V124-4.2 / BUG-017 defensive read-side guard, broadened by V124-6.2 /
		// BUG-022. Pre-V124-4 the Create path persisted entries with missing
		// required fields on `POST {}`. Those are now rejected at write time
		// (validateConnectionRequest), but stores that already contain such
		// garbage (e.g. the maintainer's demo cluster from the BUG-017
		// reproducer) would still surface them via List.
		//
		// V124-4.2 only checked `Name == ""`, which let through a record with
		// a non-empty name but empty git.provider / repo identifiers — exactly
		// the case the maintainer's 2026-05-08 walkthrough reproduced. We now
		// run the full required-field check (mirrors the create-time validator
		// — see validateConnection) and skip ANY connection missing a required
		// field, with a structured log naming the missing fields so operators
		// can diagnose without grep-archaeology.
		//
		// No destructive on-disk migration — pure read-time filter. A future
		// operator-driven cleanup remains possible.
		if missing := missingRequiredConnectionFields(c); len(missing) > 0 {
			slog.Warn("connection skipped: required fields empty (legacy garbage from pre-V124-4 store)",
				"name", c.Name,
				"missing", missing,
				"component", "connection-service")
			continue
		}
		responses = append(responses, c.ToResponse(c.Name == activeName))
	}

	return &models.ConnectionsListResponse{
		Connections:      responses,
		ActiveConnection: activeName,
	}, nil
}

// Create adds a new connection.
//
// Validation errors (currently: malformed Git URL) are wrapped with
// ErrValidation so the API layer can surface them as HTTP 400 with the
// underlying message visible to the operator (V124-3.3 / M4). Wrapping
// preserves the original error chain — callers can still errors.As for
// the concrete cause if they need it.
func (s *ConnectionService) Create(req models.CreateConnectionRequest) error {
	// V124-4.2 / BUG-017: required-field validation runs before any other
	// processing so an empty `{}` body fails fast with a 400 instead of
	// persisting a name="default" placeholder with no usable Git config.
	//
	// "Required" here is the minimum a connection needs to be useful:
	// a Git provider type AND a way to identify the repo (either an
	// explicit RepoURL or the per-provider identifier fields).
	if err := validateConnectionRequest(req); err != nil {
		return err
	}
	// Parse repo URL into provider/owner/repo if provided
	if err := req.Git.ParseRepoURL(); err != nil {
		return fmt.Errorf("invalid git URL: %w: %w", ErrValidation, err)
	}
	conn := models.Connection{
		Name:        req.Name,
		Description: req.Description,
		Git:         req.Git,
		Argocd:      req.Argocd,
		Provider:    req.Provider,
		GitOps:      req.GitOps,
		IsDefault:   req.SetAsDefault,
	}
	// Auto-derive connection name from git repo if not provided
	if conn.Name == "" || conn.Name == "default" {
		conn.Name = deriveConnectionName(conn.Git)
	}
	return s.store.SaveConnection(conn)
}

// validateConnectionRequest checks that the create/update request has the
// minimum fields needed for a usable connection. All errors are wrapped with
// ErrValidation so handlers surface them as 400 with the underlying message.
//
// Rules (V124-4.2 / BUG-017, broadened internally by V124-6.2 / BUG-022 to
// share the missing-fields helper with the read-side guard):
//   - git.provider must be set (so we know which Git backend to use)
//   - git.provider must be one of the supported values
//   - either git.repo_url is set (parsed downstream) OR the per-provider
//     identifier fields are set:
//       github      → owner + repo
//       azuredevops → organization + project + repository
//
// Token / PAT fields are NOT required at create time — the test-credentials
// endpoint and the env-var fallback (SHARKO_DEV_MODE) cover those flows.
//
// The handler `handleUpdateConnection` overlays empty token fields from the
// saved connection before calling Create, so update-with-partial-body still
// passes through this validator unchanged.
func validateConnectionRequest(req models.CreateConnectionRequest) error {
	// Reject unsupported provider explicitly so the operator gets the bad
	// value echoed back. The general missing-fields helper handles empty +
	// per-provider identifier checks.
	if req.Git.Provider != "" &&
		req.Git.Provider != models.GitProviderGitHub &&
		req.Git.Provider != models.GitProviderAzureDevOps {
		return fmt.Errorf("git.provider %q is not supported (must be one of: github, azuredevops): %w", req.Git.Provider, ErrValidation)
	}

	// Probe with a synthetic non-empty name. Create() auto-derives the name
	// from owner/repo when the request name is empty or "default", so the
	// create-time validator must NOT require Name to be set in the request.
	// The read-side guard uses missingRequiredConnectionFields directly and
	// DOES enforce the name check (because at read time there's no
	// auto-derive — the FileStore already passed it through).
	probe := models.Connection{Name: "_probe", Git: req.Git}
	if missing := missingRequiredConnectionFields(probe); len(missing) > 0 {
		// First missing field becomes the message — keeps the existing
		// operator-facing wording stable for the TestRejects… cases.
		switch missing[0] {
		case "git.provider":
			return fmt.Errorf("git.provider is required (one of: github, azuredevops): %w", ErrValidation)
		case "git.owner_repo_or_repo_url":
			return fmt.Errorf("git.repo_url or (git.owner + git.repo) is required for github provider: %w", ErrValidation)
		case "git.azure_repo_or_repo_url":
			return fmt.Errorf("git.repo_url or (git.organization + git.project + git.repository) is required for azuredevops provider: %w", ErrValidation)
		default:
			return fmt.Errorf("connection request missing required fields %v: %w", missing, ErrValidation)
		}
	}
	return nil
}

// MissingRequiredConnectionFieldsForTest exposes missingRequiredConnectionFields
// for table-driven unit tests in other packages. Production code MUST call the
// unexported version; this exists only so we don't widen the public API
// surface for an internal helper. The "ForTest" suffix is intentional.
func MissingRequiredConnectionFieldsForTest(c models.Connection) []string {
	return missingRequiredConnectionFields(c)
}

// missingRequiredConnectionFields returns the list of missing required fields
// for a Connection, in canonical order. Used by both:
//
//   - validateConnectionRequest (write-time, returns ErrValidation)
//   - List() defensive read-side guard (V124-4.2 + V124-6.2 / BUG-022)
//
// Returning a list (rather than a single error) lets the read-side guard log
// every missing field at once — operators tracing pre-V124-4 garbage records
// see the full picture without re-running the check repeatedly.
//
// "Required" mirrors what V124-4.2 made required at write time. We do NOT add
// new required fields here without also adding them to the create-time
// validator — that would split the read-side and write-side contracts.
//
// V124-6.2 SCOPE NOTE: connection.Name is NOT in this list because the
// read-side caller (`List()`) already filtered empty-name entries via this
// helper's predecessor (V124-4.2). We keep that contract — empty-name is one
// of the missing-fields conditions, surfaced under the canonical key
// "name". Callers can treat "name" specially if they need to keep the old
// wording (e.g., for backward-compatible logs).
func missingRequiredConnectionFields(c models.Connection) []string {
	var missing []string

	if c.Name == "" {
		missing = append(missing, "name")
	}

	switch c.Git.Provider {
	case "":
		missing = append(missing, "git.provider")
	case models.GitProviderGitHub:
		if c.Git.RepoURL == "" && (c.Git.Owner == "" || c.Git.Repo == "") {
			missing = append(missing, "git.owner_repo_or_repo_url")
		}
	case models.GitProviderAzureDevOps:
		if c.Git.RepoURL == "" && (c.Git.Organization == "" || c.Git.Project == "" || c.Git.Repository == "") {
			missing = append(missing, "git.azure_repo_or_repo_url")
		}
	default:
		// Unsupported provider — surface as an unknown-provider missing
		// signal so the read-side log is informative. The write-side
		// path catches this earlier via the explicit unsupported-provider
		// check in validateConnectionRequest.
		missing = append(missing, "git.provider_unsupported:"+string(c.Git.Provider))
	}

	return missing
}

// deriveConnectionName builds a connection name from the git config.
func deriveConnectionName(git models.GitRepoConfig) string {
	switch git.Provider {
	case models.GitProviderGitHub:
		if git.Owner != "" && git.Repo != "" {
			return git.Owner + "/" + git.Repo
		}
	case models.GitProviderAzureDevOps:
		if git.Organization != "" && git.Project != "" && git.Repository != "" {
			return git.Organization + "/" + git.Project + "/" + git.Repository
		}
	}
	return "default"
}

// GetConnection returns a connection by name.
func (s *ConnectionService) GetConnection(name string) (*models.Connection, error) {
	return s.store.GetConnection(name)
}

// Delete removes a connection.
func (s *ConnectionService) Delete(name string) error {
	return s.store.DeleteConnection(name)
}

// SetActive sets the active connection.
func (s *ConnectionService) SetActive(name string) error {
	slog.Info("active connection changed", "connection", name)
	return s.store.SetActiveConnection(name)
}

// GitProviderOverride is an alias for gitprovider.GitProvider, exported so that
// callers (e.g. api.Server) can reference the type without importing gitprovider.
type GitProviderOverride = gitprovider.GitProvider

// SetGitProviderOverride installs a fixed GitProvider that bypasses connection
// lookup. Used in demo/test mode to inject a mock provider.
func (s *ConnectionService) SetGitProviderOverride(p gitprovider.GitProvider) {
	s.gitProviderOverride = p
}

// GetActiveGitProvider returns a GitProvider for the currently active connection.
func (s *ConnectionService) GetActiveGitProvider() (gitprovider.GitProvider, error) {
	if s.gitProviderOverride != nil {
		return s.gitProviderOverride, nil
	}
	conn, err := s.getActiveConn()
	if err != nil {
		return nil, err
	}
	return s.buildGitProvider(conn)
}

// GetActiveArgocdClient returns an ArgoCD client for the currently active connection.
// If server_url is empty, it uses in-cluster mode with the pod's ServiceAccount token.
func (s *ConnectionService) GetActiveArgocdClient() (*argocd.Client, error) {
	conn, err := s.getActiveConn()
	if err != nil {
		return nil, err
	}
	return s.buildArgocdClient(conn)
}

func (s *ConnectionService) buildArgocdClient(conn *models.Connection) (*argocd.Client, error) {
	token := conn.Argocd.Token
	serverURL := conn.Argocd.ServerURL

	// Dev mode: fall back to env vars
	if s.devMode {
		if token == "" {
			token = os.Getenv("ARGOCD_TOKEN")
			if token != "" {
				slog.Info("argocd: using ARGOCD_TOKEN env var (dev mode fallback)")
			}
		}
		if serverURL == "" {
			serverURL = os.Getenv("ARGOCD_SERVER_URL")
		}
	}

	// Auto-discover server URL if still empty
	if serverURL == "" {
		ns := conn.Argocd.Namespace
		if ns == "" {
			ns = "argocd"
		}
		serverURL = argocd.DiscoverServerURL(ns)
	}

	if token == "" {
		return nil, fmt.Errorf("ArgoCD token not configured. Provide it via Settings UI or set ARGOCD_TOKEN env var with SHARKO_DEV_MODE=true")
	}

	return argocd.NewClient(serverURL, token, true), nil
}

// GetGitProviderForConnection returns a GitProvider for a specific named connection.
func (s *ConnectionService) GetGitProviderForConnection(name string) (gitprovider.GitProvider, error) {
	conn, err := s.store.GetConnection(name)
	if err != nil {
		return nil, err
	}
	if conn == nil {
		return nil, fmt.Errorf("connection %q not found", name)
	}
	return s.buildGitProvider(conn)
}

// TestConnection tests both Git and ArgoCD connectivity for the active connection.
func (s *ConnectionService) TestConnection(ctx context.Context) (gitErr, argocdErr error) {
	conn, err := s.getActiveConn()
	if err != nil {
		return err, err
	}

	gp, err := s.buildGitProvider(conn)
	if err != nil {
		gitErr = err
	} else {
		gitErr = gp.TestConnection(ctx)
	}

	ac, err := s.buildArgocdClient(conn)
	if err != nil {
		argocdErr = err
	} else {
		argocdErr = ac.TestConnection(ctx)
	}

	return gitErr, argocdErr
}

// AuthInfo describes which auth method was used for each service.
type AuthInfo struct {
	GitSource    string // "provided", "env:GITHUB_TOKEN", ""
	ArgocdSource string // "provided", "env:ARGOCD_TOKEN", "serviceaccount", ""
}

// TestCredentials tests Git and ArgoCD connectivity for unsaved credentials.
func (s *ConnectionService) TestCredentials(ctx context.Context, conn *models.Connection) (gitErr, argocdErr error, auth AuthInfo) {
	// Parse repo URL if provided
	if err := conn.Git.ParseRepoURL(); err != nil {
		return err, nil, auth
	}

	// Track git auth source
	if conn.Git.Token != "" {
		auth.GitSource = "provided"
	} else if os.Getenv("GITHUB_TOKEN") != "" {
		auth.GitSource = "env:GITHUB_TOKEN"
	}

	gp, err := s.buildGitProvider(conn)
	if err != nil {
		gitErr = err
	} else {
		gitErr = gp.TestConnection(ctx)
	}

	// Track argocd auth source
	if conn.Argocd.Token != "" {
		auth.ArgocdSource = "provided"
	} else if os.Getenv("ARGOCD_TOKEN") != "" {
		auth.ArgocdSource = "env:ARGOCD_TOKEN"
	} else {
		auth.ArgocdSource = "serviceaccount"
	}

	ac, err := s.buildArgocdClient(conn)
	if err != nil {
		argocdErr = err
	} else {
		argocdErr = ac.TestConnection(ctx)
	}

	return gitErr, argocdErr, auth
}

// DiscoverArgocdURL finds the ArgoCD server URL for the given namespace.
func (s *ConnectionService) DiscoverArgocdURL(namespace string) string {
	return argocd.DiscoverServerURL(namespace)
}

// GetActiveConnection returns the active connection with its full configuration.
// Returns nil (not an error) when no active connection is configured.
func (s *ConnectionService) GetActiveConnection() (*models.Connection, error) {
	activeName, err := s.store.GetActiveConnection()
	if err != nil {
		return nil, err
	}
	if activeName == "" {
		return nil, nil
	}
	return s.store.GetConnection(activeName)
}

// GetActiveConnectionInfo returns the active connection with its full configuration.
// This is used by API handlers that need access to raw credentials (e.g., for ArgoCD repo registration).
func (s *ConnectionService) GetActiveConnectionInfo() (*models.Connection, error) {
	return s.getActiveConn()
}

// GetProviderConfig returns the provider config from the active connection, or nil if not set.
// Callers should fall back to env vars when this returns nil.
func (s *ConnectionService) GetProviderConfig() *models.ProviderConfig {
	conn, err := s.getActiveConn()
	if err != nil || conn == nil {
		return nil
	}
	return conn.Provider
}

func (s *ConnectionService) getActiveConn() (*models.Connection, error) {
	activeName, err := s.store.GetActiveConnection()
	if err != nil {
		return nil, err
	}
	if activeName == "" {
		return nil, fmt.Errorf("no active connection configured")
	}

	conn, err := s.store.GetConnection(activeName)
	if err != nil {
		return nil, err
	}
	if conn == nil {
		return nil, fmt.Errorf("active connection %q not found", activeName)
	}

	return conn, nil
}

func (s *ConnectionService) buildGitProvider(conn *models.Connection) (gitprovider.GitProvider, error) {
	switch conn.Git.Provider {
	case models.GitProviderGitHub:
		token := conn.Git.Token
		if token == "" && s.devMode {
			token = os.Getenv("GITHUB_TOKEN")
			if token != "" {
				slog.Info("git: using GITHUB_TOKEN env var (dev mode fallback)")
			}
		}
		if token == "" {
			return nil, fmt.Errorf("GitHub token not configured. Provide it via Settings UI or set GITHUB_TOKEN env var with SHARKO_DEV_MODE=true")
		}
		return gitprovider.NewGitHubProvider(conn.Git.Owner, conn.Git.Repo, token), nil
	case models.GitProviderAzureDevOps:
		pat := conn.Git.PAT
		if pat == "" && s.devMode {
			pat = os.Getenv("AZURE_DEVOPS_PAT")
			if pat != "" {
				slog.Info("git: using AZURE_DEVOPS_PAT env var (dev mode fallback)")
			}
		}
		if pat == "" {
			return nil, fmt.Errorf("Azure DevOps PAT not configured. Provide it via Settings UI or set AZURE_DEVOPS_PAT env var with SHARKO_DEV_MODE=true")
		}
		return gitprovider.NewAzureDevOpsProvider(conn.Git.Organization, conn.Git.Project, conn.Git.Repository, pat), nil
	default:
		return nil, fmt.Errorf("unsupported git provider: %s", conn.Git.Provider)
	}
}
