// Command gen-lifecycle-events reads lifecycleevents.Declared — the Go
// catalog of every connection-lifecycle audit event the server can write — and
// writes a TypeScript `as const` list plus a union type at
// ui/src/generated/lifecycle-events.ts, so the browser's activity feed is
// keyed on names it never types by hand.
//
// # Why
//
// The feed renders lifecycle events by name from an allowlist, with a human
// title for each and no fallback: an unrecognised event is skipped rather
// than shown as a raw identifier. Right for a reader, and it means a
// server-side RENAME turns a visible event into silence — which on that page
// looks exactly like nothing having happened, ending in a supported surface
// stating as a fact "Nothing recorded since Sharko started." while things did
// happen.
//
// The browser held a hand-written copy of the names, and the test that was
// supposed to catch a rename held a SECOND hand-written copy to compare the
// first against. The two agreed with each other and with nothing else: no .go
// file and no CI job referred to either. This generator is what makes the two
// sides one.
//
// # It reads the catalog at RUNTIME, and parses nothing
//
// Same argument as its siblings cmd/gen-notification-codes and
// cmd/gen-connection-sentences: what it needs is a slice of strings that IS a
// runtime value, so it imports the package and reads the value rather than
// walking Go source with go/ast. This file therefore holds no copy of any
// event name, and main_test.go fails the build if one ever appears here.
//
// (The other sibling, cmd/gen-provider-types, does parse source, because what
// it needs — the arms of a switch statement — has no runtime representation.)
//
// # The TypeScript key is derived from the wire value
//
// The key is the lower_snake_case wire value converted to camelCase, exactly
// as gen-notification-codes does it. Deriving the key from the value means no
// second source can go stale, so a Go rename cannot produce a TypeScript key
// that no longer matches the string on the wire.
//
// # No commit SHA in the header
//
// Deliberately, for the reason gen-connection-sentences gives: a generated
// file stamped with the revision it was built from churns on every unrelated
// commit and fails CI saying "out of date" about content that is correct.
//
// Usage:
//
//	go run ./cmd/gen-lifecycle-events
//
// or via the Makefile:
//
//	make generate-lifecycle-events
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/MoranWeissman/sharko/internal/lifecycleevents"
)

const defaultOutputPath = "ui/src/generated/lifecycle-events.ts"

func main() {
	var outputPath string
	flag.StringVar(&outputPath, "output", defaultOutputPath,
		"path to the TypeScript file to (over)write")
	flag.Parse()

	if err := run(lifecycleevents.Declared(), outputPath); err != nil {
		fmt.Fprintf(os.Stderr, "gen-lifecycle-events: %v\n", err)
		os.Exit(1)
	}
}

// run is the testable entry point: it renders `events` and writes the result
// to `outputPath`. The output directory is created if it doesn't exist.
//
// The catalog is a PARAMETER rather than a package reference so the renderer
// can be driven over a synthetic list in tests. main passes the real
// lifecycleevents.Declared() and nothing else does.
func run(events []lifecycleevents.Event, outputPath string) error {
	if len(events) == 0 {
		return fmt.Errorf("the lifecycle event catalog is empty — refusing to write an empty contract to %s", outputPath)
	}

	rendered, err := renderTypeScript(events)
	if err != nil {
		return fmt.Errorf("render: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o750); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(outputPath), err)
	}
	if err := os.WriteFile(outputPath, []byte(rendered), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}
	fmt.Printf("gen-lifecycle-events: wrote %d events to %s\n", len(events), outputPath)
	return nil
}

// renderTypeScript renders the deterministic TS output. The format is pinned
// by tests and by the CI "Lifecycle Events Up To Date" check — keep it
// byte-stable across refactors.
//
// The order is Declared()'s own order, which is the Go declaration order,
// which is fixed source. There is deliberately no sort: re-sorting here would
// hide a reordering in Go rather than showing it in the diff.
func renderTypeScript(events []lifecycleevents.Event) (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen-lifecycle-events. DO NOT EDIT.\n")
	b.WriteString("// Source: internal/lifecycleevents/events.go\n")
	b.WriteString("// Run `make generate-lifecycle-events` to refresh.\n")
	b.WriteString("//\n")
	b.WriteString("// Every connection-lifecycle audit event the server can write.\n")
	b.WriteString("//\n")
	b.WriteString("// The connection page's activity feed renders these by name, from a table\n")
	b.WriteString("// with no fallback: an event it does not recognise is skipped rather than\n")
	b.WriteString("// shown as a raw identifier. So a rename on the server used to turn a visible\n")
	b.WriteString("// lifecycle event into silence, which on that page looks exactly like nothing\n")
	b.WriteString("// having happened. The feed's table is keyed on this list, so a rename now\n")
	b.WriteString("// either fails the type-check or fails CI's drift job — never quietly empties\n")
	b.WriteString("// the feed.\n")
	b.WriteString("\n")
	b.WriteString("export const LIFECYCLE_EVENTS = {\n")

	seenKeys := make(map[string]lifecycleevents.Event, len(events))
	seenValues := make(map[lifecycleevents.Event]struct{}, len(events))
	for _, event := range events {
		key, err := tsKey(event)
		if err != nil {
			return "", err
		}
		if previous, clash := seenKeys[key]; clash {
			return "", fmt.Errorf("events %q and %q both produce the TypeScript key %q — one would silently overwrite the other",
				previous, event, key)
		}
		if _, dup := seenValues[event]; dup {
			return "", fmt.Errorf("event %q is declared more than once", event)
		}
		seenKeys[key] = event
		seenValues[event] = struct{}{}

		quoted, err := quoteForTypeScript(string(event))
		if err != nil {
			return "", fmt.Errorf("event %q: %w", event, err)
		}
		b.WriteString("  ")
		b.WriteString(key)
		b.WriteString(": ")
		b.WriteString(quoted)
		b.WriteString(",\n")
	}

	b.WriteString("} as const\n")
	b.WriteString("\n")
	b.WriteString("// The closed set of event names this build knows about.\n")
	b.WriteString("export type LifecycleEvent = (typeof LIFECYCLE_EVENTS)[keyof typeof LIFECYCLE_EVENTS]\n")
	b.WriteString("\n")
	b.WriteString("// Every name, in the server's own declaration order. The feed's table must\n")
	b.WriteString("// have an entry for each one; the test that checks that reads THIS, so it\n")
	b.WriteString("// cannot go stale the way a hand-written copy of the list did.\n")
	b.WriteString("export const LIFECYCLE_EVENT_NAMES: readonly LifecycleEvent[] = Object.values(LIFECYCLE_EVENTS)\n")
	return b.String(), nil
}

// tsKey converts a snake_case wire value into a camelCase TypeScript property
// name: "some_broken_thing" -> "someBrokenThing".
//
// The example is deliberately made up. Pasting a real event name in here would
// be a second copy of the contract sitting in a comment, going stale quietly —
// and main_test.go fails the build if one appears.
//
// It rejects anything that would not be a bare JavaScript property name, so a
// value that cannot be rendered without quoting fails the generator rather
// than producing TypeScript that needs a per-key decision.
func tsKey(event lifecycleevents.Event) (string, error) {
	raw := string(event)
	if raw == "" {
		return "", fmt.Errorf("a lifecycle event is empty — every event needs a name")
	}

	parts := strings.Split(raw, "_")
	var b strings.Builder
	for i, part := range parts {
		if part == "" {
			return "", fmt.Errorf("event %q has an empty word in it — expected lower_snake_case", raw)
		}
		for j, r := range part {
			isLower := r >= 'a' && r <= 'z'
			isDigit := r >= '0' && r <= '9'
			if !isLower && !isDigit {
				return "", fmt.Errorf("event %q contains %q — expected lower_snake_case (a-z, 0-9 and underscores)", raw, r)
			}
			if i == 0 && j == 0 && isDigit {
				return "", fmt.Errorf("event %q starts with a digit, which is not a valid TypeScript property name", raw)
			}
		}
		if i == 0 {
			b.WriteString(part)
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String(), nil
}

// quoteForTypeScript renders one value as a TypeScript double-quoted string
// literal.
//
// It goes through encoding/json rather than strconv.Quote for the reason
// cmd/gen-connection-sentences gives: JSON's string grammar is a strict subset
// of JavaScript's, whereas Go's own quoting can emit `\U0001F600`, an escape
// JavaScript does not have.
func quoteForTypeScript(s string) (string, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(s); err != nil {
		return "", err
	}
	// Encode appends a newline of its own.
	return strings.TrimRight(buf.String(), "\n"), nil
}
