package main

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// fixtureSource mimics the shape of internal/providers/provider.go's
// New() switch — distinct types in random order, an empty-string arm, a
// default arm, plus a multi-literal case (string-literal alias) so the
// extractor's contract is exercised end-to-end without coupling tests to
// the live provider list.
const fixtureSource = `package providers

func unrelated() {
	x := "ignore-me"
	_ = x
}

func New(cfg Config) (interface{}, error) {
	switch cfg.Type {
	case "k8s-secrets", "kubernetes":
		return nil, nil
	case "aws-sm", "aws-secrets-manager":
		return nil, nil
	case "argocd":
		return nil, nil
	case "":
		return nil, nil
	default:
		return nil, nil
	}
}
`

func TestExtractProviderTypes_Fixture(t *testing.T) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "fixture.go", fixtureSource, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	got, err := extractProviderTypes(file)
	if err != nil {
		t.Fatalf("extractProviderTypes: %v", err)
	}
	want := []string{
		"argocd",
		"aws-secrets-manager",
		"aws-sm",
		"k8s-secrets",
		"kubernetes",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("extractProviderTypes mismatch:\n  got:  %#v\n  want: %#v", got, want)
	}
}

// TestExtractProviderTypes_LiveSource is the regression-prevention test:
// it parses the real internal/providers/provider.go (relative to the
// repo root) and asserts that the extractor (a) finds at least one
// type and (b) includes the well-known stable identifiers that have
// shipped since v1.x. New types added later will be picked up
// automatically — this test only pins the contract, not the full set.
func TestExtractProviderTypes_LiveSource(t *testing.T) {
	// cmd/gen-provider-types/main_test.go → repo root is two dirs up.
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("repo root abs: %v", err)
	}
	source := filepath.Join(repoRoot, "internal", "providers", "provider.go")
	got, err := extractProviderTypesFromFile(source)
	if err != nil {
		t.Fatalf("extractProviderTypesFromFile(%s): %v", source, err)
	}
	if len(got) == 0 {
		t.Fatalf("expected at least one provider type, got 0")
	}
	mustContain := []string{"argocd", "aws-sm", "k8s-secrets"}
	for _, want := range mustContain {
		if !contains(got, want) {
			t.Errorf("expected %q in extracted types, got %v", want, got)
		}
	}
	// "" must always be filtered out — it represents the auto-default
	// branch, not a user-selectable type.
	if contains(got, "") {
		t.Errorf("empty string must be filtered from extracted types, got %v", got)
	}
}

func TestRenderTypeScript_Deterministic(t *testing.T) {
	types := []string{"argocd", "aws-sm", "k8s-secrets"}
	a := renderTypeScript(types, "internal/providers/provider.go")
	b := renderTypeScript(types, "internal/providers/provider.go")
	if a != b {
		t.Fatal("renderTypeScript is not deterministic")
	}
	for _, want := range []string{
		"// Code generated by cmd/gen-provider-types. DO NOT EDIT.",
		"// Source: internal/providers/provider.go::New",
		"export const VALID_PROVIDER_TYPES = [",
		`  "argocd",`,
		`  "aws-sm",`,
		`  "k8s-secrets",`,
		"] as const",
		"export type ProviderType = (typeof VALID_PROVIDER_TYPES)[number]",
	} {
		if !strings.Contains(a, want) {
			t.Errorf("rendered output missing %q.\nfull output:\n%s", want, a)
		}
	}
}

func TestRenderTypeScript_PathNormalization(t *testing.T) {
	// Windows-style separator should not leak into the header.
	rendered := renderTypeScript([]string{"argocd"}, `internal\providers\provider.go`)
	if !strings.Contains(rendered, "// Source: internal/providers/provider.go::New") {
		t.Fatalf("path not normalized to forward slashes:\n%s", rendered)
	}
}

func TestRun_WritesFile(t *testing.T) {
	// Stage a temp source file and a temp output path; verify run() writes
	// the expected bytes. Mirrors the production invocation without
	// touching the real ui/src/generated/provider-types.ts.
	dir := t.TempDir()
	src := filepath.Join(dir, "provider.go")
	if err := os.WriteFile(src, []byte(fixtureSource), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	out := filepath.Join(dir, "nested", "provider-types.ts")
	if err := run(src, out); err != nil {
		t.Fatalf("run: %v", err)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	body := string(data)
	for _, want := range []string{
		`"argocd",`,
		`"aws-sm",`,
		`"kubernetes",`,
		"as const",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("output missing %q.\nfull output:\n%s", want, body)
		}
	}
}

func contains(haystack []string, needle string) bool {
	for _, s := range haystack {
		if s == needle {
			return true
		}
	}
	return false
}
