package appsets

// handoff.go — the ONLY write surface in this package (v4 Wave 2, review
// finding B-1: the v3 → v4 runtime handoff).
//
// Everything else here is read-only and stays that way. These three
// operations exist because of one specific, unavoidable fact about the
// v3 → v4 migration:
//
// The pull request that migrates a repo destroys BOTH generator arms of
// every ApplicationSet the v3 bootstrap scaffold left running in ArgoCD.
// The git arm reads configuration/addons-clusters-values/<cluster>.yaml
// (the PR deletes those files); the clusters arm selects a bare
// `<addon>: enabled` label on the cluster Secret (the reconciler replaces
// those with addons.sharko.dev/* once the PR merges). An ApplicationSet
// whose generators produce nothing deletes every Application it made —
// and the v3 template stamps `resources-finalizer.argocd.argoproj.io` on
// each one and sets no preserveResourcesOnDeletion, so that deletion
// cascades into the live workloads. Merging the migration PR on a running
// fleet would uninstall every addon on every cluster.
//
// So before the PR is even opened, Sharko has to make those old
// ApplicationSets harmless. That needs writes, and there is no read-only
// way to do it.
//
// Two ArgoCD facts this code depends on, both verified against the ArgoCD
// operator manual (operator-manual/applicationset/Application-Deletion.md
// and Controlling-Resource-Modification.md) rather than assumed:
//
//  1. `spec.syncPolicy.preserveResourcesOnDeletion: true` stops the
//     ApplicationSet controller from putting the Argo CD resources
//     finalizer on the Applications it generates. Without the finalizer,
//     deleting an Application leaves everything it deployed running.
//  2. Applications generated by an ApplicationSet carry an ownerReference
//     back to it, which is how Kubernetes garbage collection removes them
//     when the ApplicationSet goes away.
//
// Fact 1 is about Applications the controller generates FROM NOW ON. It
// says nothing about an Application that is already on the cluster with
// the finalizer already on it — and in the v3 scaffold the finalizer comes
// from the user-facing `spec.template.metadata.finalizers` block, not from
// the controller's own auto-add. That is why ReleaseGeneratedApplications
// exists: it takes the finalizer off the LIVE Applications directly, so
// the safety of the transition does not depend on the controller
// reconciling the template change in time. Belt (the template patch, for
// anything regenerated) and braces (the live patch, for what is running).
//
// Scope of the template read/write: exactly
// `spec.template.metadata.finalizers`, and exactly the one ArgoCD
// finalizer string. Nothing else in spec.template is read, and nothing
// else is written. The package's promise — "we never read your Application
// template" — narrows to "we read and write one finalizer entry on it,
// and only during a migration you asked for".

import (
	"context"
	"encoding/json"
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
)

// ResourcesFinalizer is the ArgoCD finalizer whose presence on an
// Application means "when this Application is deleted, delete everything
// it installed too". Removing it is what turns an Application deletion
// into a no-op for the running workloads.
const ResourcesFinalizer = "resources-finalizer.argocd.argoproj.io"

// ApplicationsGroupVersionResource is the Application CRD coordinate.
// Needed only by ReleaseGeneratedApplications.
var ApplicationsGroupVersionResource = schema.GroupVersionResource{
	Group:    "argoproj.io",
	Version:  "v1alpha1",
	Resource: "applications",
}

// Writer is the narrow write surface described in the file comment. Kept
// separate from Reader so a caller that only needs to look can be handed
// something that physically cannot change anything.
type Writer interface {
	// Preserve makes one ApplicationSet safe to strand and safe to delete:
	// preserveResourcesOnDeletion goes on, and the ArgoCD resources
	// finalizer comes off its Application template. Idempotent.
	Preserve(ctx context.Context, name string) error

	// ReleaseGeneratedApplications takes the ArgoCD resources finalizer off
	// every live Application this ApplicationSet generated, and returns the
	// names it changed. Idempotent — an Application that never had the
	// finalizer is left alone and not reported.
	ReleaseGeneratedApplications(ctx context.Context, appSetName string) ([]string, error)

	// Delete removes one ApplicationSet. Call it only after Preserve has
	// been confirmed, never before — on an unprepared ApplicationSet this
	// is the workload-deleting move, not the safe one.
	Delete(ctx context.Context, name string) error
}

// Manager is a Reader that can also perform the handoff writes. The
// dynamic-client implementation satisfies it; test fakes satisfy it too.
type Manager interface {
	Reader
	Writer
}

// compile-time proof the real client covers the whole surface.
var _ Manager = (*DynamicReader)(nil)

// Preserve implements Writer.
//
// One JSON merge patch carries both halves so there is no window where
// the flag is set but the finalizer is still on the template (or the other
// way round). A merge patch replaces a list wholesale, which is exactly
// what is wanted for the finalizers field.
func (r *DynamicReader) Preserve(ctx context.Context, name string) error {
	if r == nil || r.client == nil {
		return fmt.Errorf("no ApplicationSet client wired")
	}
	obj, err := r.client.Resource(GroupVersionResource).Namespace(r.namespace).
		Get(ctx, name, metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf("reading ApplicationSet %q in namespace %q: %w", name, r.namespace, err)
	}

	patch := map[string]interface{}{
		"spec": map[string]interface{}{
			"syncPolicy": map[string]interface{}{
				"preserveResourcesOnDeletion": true,
			},
		},
	}

	// Only touch the template's finalizers when the ArgoCD one is actually
	// there — a patch that rewrites the list for no reason is a diff
	// somebody has to explain later.
	if current, found := templateFinalizers(obj.Object); found && containsString(current, ResourcesFinalizer) {
		spec, _ := patch["spec"].(map[string]interface{})
		spec["template"] = map[string]interface{}{
			"metadata": map[string]interface{}{
				"finalizers": toInterfaceSlice(withoutString(current, ResourcesFinalizer)),
			},
		}
	}

	body, err := json.Marshal(patch)
	if err != nil {
		return fmt.Errorf("building the patch for ApplicationSet %q: %w", name, err)
	}
	if _, err := r.client.Resource(GroupVersionResource).Namespace(r.namespace).
		Patch(ctx, name, types.MergePatchType, body, metav1.PatchOptions{}); err != nil {
		return fmt.Errorf("making ApplicationSet %q safe to retire: %w", name, err)
	}
	return nil
}

// ReleaseGeneratedApplications implements Writer.
func (r *DynamicReader) ReleaseGeneratedApplications(ctx context.Context, appSetName string) ([]string, error) {
	if r == nil || r.client == nil {
		return nil, fmt.Errorf("no ApplicationSet client wired")
	}
	list, err := r.client.Resource(ApplicationsGroupVersionResource).Namespace(r.namespace).
		List(ctx, metav1.ListOptions{})
	if err != nil {
		return nil, fmt.Errorf("listing Applications in namespace %q: %w", r.namespace, err)
	}

	var released []string
	for i := range list.Items {
		app := list.Items[i].Object
		if !ownedByApplicationSet(app, appSetName) {
			continue
		}
		finalizers, _ := objectFinalizers(app)
		if !containsString(finalizers, ResourcesFinalizer) {
			continue
		}
		appName, _ := nestedString(app, "metadata", "name")
		patch, err := json.Marshal(map[string]interface{}{
			"metadata": map[string]interface{}{
				"finalizers": toInterfaceSlice(withoutString(finalizers, ResourcesFinalizer)),
			},
		})
		if err != nil {
			return released, fmt.Errorf("building the patch for Application %q: %w", appName, err)
		}
		if _, err := r.client.Resource(ApplicationsGroupVersionResource).Namespace(r.namespace).
			Patch(ctx, appName, types.MergePatchType, patch, metav1.PatchOptions{}); err != nil {
			return released, fmt.Errorf(
				"taking the delete-everything marker off Application %q: %w", appName, err)
		}
		released = append(released, appName)
	}
	return released, nil
}

// Delete implements Writer. Background propagation is the Kubernetes
// default and is what we want: the owned Applications are collected in the
// background, and with the finalizer already gone their removal touches
// nothing on the workload clusters.
func (r *DynamicReader) Delete(ctx context.Context, name string) error {
	if r == nil || r.client == nil {
		return fmt.Errorf("no ApplicationSet client wired")
	}
	policy := metav1.DeletePropagationBackground
	err := r.client.Resource(GroupVersionResource).Namespace(r.namespace).
		Delete(ctx, name, metav1.DeleteOptions{PropagationPolicy: &policy})
	if err != nil {
		return fmt.Errorf("removing ApplicationSet %q from namespace %q: %w", name, r.namespace, err)
	}
	return nil
}

// ─── unstructured helpers ────────────────────────────────────────────────
//
// All defensive: a field of the wrong type yields the zero value rather
// than a panic, matching Parse's stance in appsets.go.

func templateFinalizers(obj map[string]interface{}) ([]string, bool) {
	spec, ok := obj["spec"].(map[string]interface{})
	if !ok {
		return nil, false
	}
	template, ok := spec["template"].(map[string]interface{})
	if !ok {
		return nil, false
	}
	return objectFinalizers(template)
}

func objectFinalizers(obj map[string]interface{}) ([]string, bool) {
	meta, ok := obj["metadata"].(map[string]interface{})
	if !ok {
		return nil, false
	}
	raw, ok := meta["finalizers"].([]interface{})
	if !ok {
		return nil, false
	}
	out := make([]string, 0, len(raw))
	for _, item := range raw {
		if s, ok := item.(string); ok {
			out = append(out, s)
		}
	}
	return out, true
}

// ownedByApplicationSet reports whether obj carries an ownerReference back
// to the named ApplicationSet. This is the link ArgoCD's own documentation
// names as the one between a generated Application and its parent, so it
// is the honest way to ask "did this ApplicationSet make this?" — far
// better than guessing from the Application's name.
func ownedByApplicationSet(obj map[string]interface{}, appSetName string) bool {
	meta, ok := obj["metadata"].(map[string]interface{})
	if !ok {
		return false
	}
	refs, ok := meta["ownerReferences"].([]interface{})
	if !ok {
		return false
	}
	for _, raw := range refs {
		ref, ok := raw.(map[string]interface{})
		if !ok {
			continue
		}
		kind, _ := ref["kind"].(string)
		name, _ := ref["name"].(string)
		if kind == "ApplicationSet" && name == appSetName {
			return true
		}
	}
	return false
}

func nestedString(obj map[string]interface{}, keys ...string) (string, bool) {
	cur := obj
	for i, key := range keys {
		if i == len(keys)-1 {
			s, ok := cur[key].(string)
			return s, ok
		}
		next, ok := cur[key].(map[string]interface{})
		if !ok {
			return "", false
		}
		cur = next
	}
	return "", false
}

func containsString(list []string, want string) bool {
	for _, s := range list {
		if s == want {
			return true
		}
	}
	return false
}

func withoutString(list []string, drop string) []string {
	out := make([]string, 0, len(list))
	for _, s := range list {
		if s != drop {
			out = append(out, s)
		}
	}
	return out
}

func toInterfaceSlice(list []string) []interface{} {
	out := make([]interface{}, 0, len(list))
	for _, s := range list {
		out = append(out, s)
	}
	return out
}
