package auth

import (
	"bytes"
	"context"
	"log/slog"
	"strings"
	"testing"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
)

const (
	testBootstrapNS     = "sharko-test"
	testBootstrapSecret = "sharko"
)

// captureSlog redirects the default slog logger to a buffer for the duration
// of the test, returning the buffer and a restore func.
func captureSlog(t *testing.T) (*bytes.Buffer, func()) {
	t.Helper()
	prev := slog.Default()
	buf := new(bytes.Buffer)
	slog.SetDefault(slog.New(slog.NewTextHandler(buf, &slog.HandlerOptions{Level: slog.LevelDebug})))
	return buf, func() { slog.SetDefault(prev) }
}

func newBootstrapStore(t *testing.T, secretData map[string][]byte) *Store {
	t.Helper()
	clientset := fake.NewSimpleClientset(&corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{Name: testBootstrapSecret, Namespace: testBootstrapNS},
		Data:       secretData,
	})
	s := &Store{
		users:      make(map[string]*UserAccount),
		passHash:   make(map[string]string),
		userTokens: make(map[string]string),
		tokens:     make(map[string]*APIToken),
	}
	s.SetClientForTest(clientset, testBootstrapNS, testBootstrapSecret)
	return s
}

// --- MaybeLogBootstrapCredential ----------------------------------------------

func TestMaybeLogBootstrapCredential_AutoGenerated_LogsBlock(t *testing.T) {
	t.Setenv(EnvBootstrapAdminPassword, "")

	const generated = "GeneratedABC12345"
	s := newBootstrapStore(t, map[string][]byte{
		"admin.password":        []byte("$2a$10$fakebcrypt"),
		"admin.initialPassword": []byte(generated),
	})

	buf, restore := captureSlog(t)
	defer restore()

	s.MaybeLogBootstrapCredential()

	out := buf.String()
	if !strings.Contains(out, "BOOTSTRAP ADMIN CREDENTIAL") {
		t.Fatalf("expected BOOTSTRAP marker in logs, got: %s", out)
	}
	if !strings.Contains(out, generated) {
		t.Fatalf("expected generated password in logs, got: %s", out)
	}
	if !strings.Contains(out, "END BOOTSTRAP ADMIN CREDENTIAL") {
		t.Fatalf("expected END marker in logs, got: %s", out)
	}

	// admin.initialPassword should have been removed from the secret so that
	// the credential is not re-emitted on the next restart.
	updated, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Get(context.Background(), testBootstrapSecret, metav1.GetOptions{})
	if err != nil {
		t.Fatalf("read secret after log: %v", err)
	}
	if _, present := updated.Data["admin.initialPassword"]; present {
		t.Fatalf("admin.initialPassword should be deleted after first log, but it persisted")
	}
}

func TestMaybeLogBootstrapCredential_OperatorSuppliedNotLogged(t *testing.T) {
	// CRITICAL security invariant: when the operator supplied a password via
	// env var (Helm `bootstrapAdmin.password` or `existingSecret`), the log
	// path MUST NOT emit anything — even if a stale admin.initialPassword
	// happens to be present in the secret.
	t.Setenv(EnvBootstrapAdminPassword, "OperatorSecret123")

	s := newBootstrapStore(t, map[string][]byte{
		"admin.password":        []byte("$2a$10$fakebcrypt"),
		"admin.initialPassword": []byte("StaleAutoGen99"),
	})

	buf, restore := captureSlog(t)
	defer restore()

	s.MaybeLogBootstrapCredential()

	out := buf.String()
	if strings.Contains(out, "BOOTSTRAP ADMIN CREDENTIAL") {
		t.Fatalf("operator-supplied path must NOT emit BOOTSTRAP block, got: %s", out)
	}
	if strings.Contains(out, "StaleAutoGen99") {
		t.Fatalf("operator-supplied path must NOT log any password, got: %s", out)
	}
	if strings.Contains(out, "OperatorSecret123") {
		t.Fatalf("operator-supplied password must NEVER appear in logs, got: %s", out)
	}
}

func TestMaybeLogBootstrapCredential_NoMarker_NoLog(t *testing.T) {
	// When admin.initialPassword is absent (e.g. operator path with
	// existingSecret, or after the first log+delete cycle), the function
	// must be a no-op.
	t.Setenv(EnvBootstrapAdminPassword, "")

	s := newBootstrapStore(t, map[string][]byte{
		"admin.password": []byte("$2a$10$fakebcrypt"),
	})

	buf, restore := captureSlog(t)
	defer restore()

	s.MaybeLogBootstrapCredential()

	if strings.Contains(buf.String(), "BOOTSTRAP ADMIN CREDENTIAL") {
		t.Fatalf("no admin.initialPassword should mean no log, got: %s", buf.String())
	}
}

func TestMaybeLogBootstrapCredential_LocalMode_NoLog(t *testing.T) {
	t.Setenv(EnvBootstrapAdminPassword, "")

	s := &Store{
		mode:       ModeLocal,
		users:      make(map[string]*UserAccount),
		passHash:   make(map[string]string),
		userTokens: make(map[string]string),
		tokens:     make(map[string]*APIToken),
	}

	buf, restore := captureSlog(t)
	defer restore()

	s.MaybeLogBootstrapCredential()

	if strings.Contains(buf.String(), "BOOTSTRAP ADMIN CREDENTIAL") {
		t.Fatalf("local mode must not log bootstrap credential, got: %s", buf.String())
	}
}

// --- SeedBootstrapAdminFromEnv ------------------------------------------------

func TestSeedBootstrapAdminFromEnv_AppliesPassword(t *testing.T) {
	const operatorPass = "OperatorChosen!42"
	t.Setenv(EnvBootstrapAdminPassword, operatorPass)

	s := newBootstrapStore(t, map[string][]byte{
		"admin.initialPassword": []byte("StaleAutoGen99"),
	})

	if err := s.SeedBootstrapAdminFromEnv(); err != nil {
		t.Fatalf("SeedBootstrapAdminFromEnv: %v", err)
	}

	// admin.password must now bcrypt-validate the operator-supplied value.
	updated, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Get(context.Background(), testBootstrapSecret, metav1.GetOptions{})
	if err != nil {
		t.Fatalf("read secret: %v", err)
	}
	hash, ok := updated.Data["admin.password"]
	if !ok || len(hash) == 0 {
		t.Fatalf("admin.password not written to secret")
	}
	if !s.ValidateCredentials("admin", operatorPass) {
		t.Fatalf("ValidateCredentials should accept the operator-supplied password")
	}

	// The stale initial-password marker must have been cleared so
	// MaybeLogBootstrapCredential does not subsequently log it.
	if _, present := updated.Data["admin.initialPassword"]; present {
		t.Fatalf("admin.initialPassword should be cleared after seed, but persisted")
	}
}

func TestSeedBootstrapAdminFromEnv_DoesNotLogPassword(t *testing.T) {
	// SECURITY invariant: the plaintext env value must NEVER appear in logs.
	const operatorPass = "OperatorSecret-Should-Not-Leak"
	t.Setenv(EnvBootstrapAdminPassword, operatorPass)

	s := newBootstrapStore(t, nil)

	buf, restore := captureSlog(t)
	defer restore()

	if err := s.SeedBootstrapAdminFromEnv(); err != nil {
		t.Fatalf("SeedBootstrapAdminFromEnv: %v", err)
	}

	out := buf.String()
	if strings.Contains(out, operatorPass) {
		t.Fatalf("operator-supplied password leaked into logs: %s", out)
	}
	// We DO want a benign acknowledgement that the operator-supplied path
	// was taken — operators need to confirm their value was applied.
	if !strings.Contains(out, "operator-supplied bootstrap admin password applied") {
		t.Fatalf("expected operator-supplied acknowledgement log line, got: %s", out)
	}
}

func TestSeedBootstrapAdminFromEnv_EmptyEnvIsNoOp(t *testing.T) {
	t.Setenv(EnvBootstrapAdminPassword, "")

	s := newBootstrapStore(t, map[string][]byte{
		"admin.password":        []byte("$2a$10$fakebcrypt"),
		"admin.initialPassword": []byte("Original"),
	})

	if err := s.SeedBootstrapAdminFromEnv(); err != nil {
		t.Fatalf("SeedBootstrapAdminFromEnv: %v", err)
	}

	// Secret should be untouched.
	updated, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Get(context.Background(), testBootstrapSecret, metav1.GetOptions{})
	if err != nil {
		t.Fatalf("read secret: %v", err)
	}
	if string(updated.Data["admin.password"]) != "$2a$10$fakebcrypt" {
		t.Fatalf("admin.password should be untouched when env is empty, got: %s", updated.Data["admin.password"])
	}
	if string(updated.Data["admin.initialPassword"]) != "Original" {
		t.Fatalf("admin.initialPassword should be untouched when env is empty")
	}
}

func TestSeedBootstrapAdminFromEnv_LocalModeIsNoOp(t *testing.T) {
	t.Setenv(EnvBootstrapAdminPassword, "AnyValue")

	s := &Store{
		mode:       ModeLocal,
		users:      make(map[string]*UserAccount),
		passHash:   make(map[string]string),
		userTokens: make(map[string]string),
		tokens:     make(map[string]*APIToken),
	}

	if err := s.SeedBootstrapAdminFromEnv(); err != nil {
		t.Fatalf("SeedBootstrapAdminFromEnv in local mode should not error: %v", err)
	}
}

// --- V124-6.3 / BUG-023: sharko-initial-admin-secret -------------------------

func TestMaybeLogBootstrapCredential_AutoGenerated_WritesInitialAdminSecret(t *testing.T) {
	// Auto-generated path with default writeInitialSecret (env unset → true)
	// MUST write `sharko-initial-admin-secret` carrying the plaintext.
	t.Setenv(EnvBootstrapAdminPassword, "")
	t.Setenv(EnvWriteInitialAdminSecret, "")

	const generated = "GenABC456789xyz"
	s := newBootstrapStore(t, map[string][]byte{
		"admin.password":        []byte("$2a$10$fakebcrypt"),
		"admin.initialPassword": []byte(generated),
	})

	s.MaybeLogBootstrapCredential()

	got, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Get(context.Background(), InitialAdminSecretName, metav1.GetOptions{})
	if err != nil {
		t.Fatalf("expected %s to exist after auto-gen bootstrap, got: %v", InitialAdminSecretName, err)
	}
	if string(got.Data["password"]) != generated {
		t.Errorf("password mismatch: got %q want %q", got.Data["password"], generated)
	}
	if string(got.Data["username"]) != "admin" {
		t.Errorf("username mismatch: got %q want %q", got.Data["username"], "admin")
	}
	if got.Labels["app.kubernetes.io/managed-by"] != "sharko" {
		t.Errorf("missing managed-by label: %+v", got.Labels)
	}
	if got.Labels["app.kubernetes.io/component"] != "bootstrap" {
		t.Errorf("missing bootstrap component label: %+v", got.Labels)
	}
	if got.Annotations["sharko.io/initial-secret"] != "delete-after-first-password-change" {
		t.Errorf("missing initial-secret annotation: %+v", got.Annotations)
	}
}

func TestMaybeLogBootstrapCredential_AutoGenerated_OptOut_DoesNotWriteSecret(t *testing.T) {
	// Auto-generated path WITH writeInitialSecret=false MUST NOT write the
	// secret. The log path remains the source of truth.
	t.Setenv(EnvBootstrapAdminPassword, "")
	t.Setenv(EnvWriteInitialAdminSecret, "false")

	s := newBootstrapStore(t, map[string][]byte{
		"admin.password":        []byte("$2a$10$fakebcrypt"),
		"admin.initialPassword": []byte("AnyAutoGen"),
	})

	s.MaybeLogBootstrapCredential()

	_, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Get(context.Background(), InitialAdminSecretName, metav1.GetOptions{})
	if !apierrorsIsNotFound(err) {
		t.Fatalf("expected %s to NOT exist when writeInitialSecret=false, got err=%v", InitialAdminSecretName, err)
	}
}

func TestMaybeLogBootstrapCredential_OperatorSupplied_DoesNotWriteSecret(t *testing.T) {
	// Operator-supplied via env var (Helm bootstrapAdmin.password OR
	// existingSecret) MUST NEVER trigger the initial-admin-secret write —
	// even if writeInitialSecret=true. The credential's source of truth is
	// the operator's input; Sharko owns nothing here.
	t.Setenv(EnvBootstrapAdminPassword, "OperatorSecret999")
	t.Setenv(EnvWriteInitialAdminSecret, "true")

	s := newBootstrapStore(t, map[string][]byte{
		"admin.password":        []byte("$2a$10$fakebcrypt"),
		"admin.initialPassword": []byte("StaleAutoGen"),
	})

	s.MaybeLogBootstrapCredential()

	_, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Get(context.Background(), InitialAdminSecretName, metav1.GetOptions{})
	if !apierrorsIsNotFound(err) {
		t.Fatalf("operator-supplied path must NOT write %s, got err=%v", InitialAdminSecretName, err)
	}
}

func TestMaybeLogBootstrapCredential_AutoGenerated_RewriteIsIdempotent(t *testing.T) {
	// If the secret already exists (e.g. operator left it in place across
	// a re-bootstrap), the create-or-update path must succeed and refresh
	// the password without crashing.
	t.Setenv(EnvBootstrapAdminPassword, "")
	t.Setenv(EnvWriteInitialAdminSecret, "")

	const newPass = "RebootstrapXYZ123"
	s := newBootstrapStore(t, map[string][]byte{
		"admin.password":        []byte("$2a$10$fakebcrypt"),
		"admin.initialPassword": []byte(newPass),
	})

	// Pre-create the initial-admin-secret with stale data to simulate a
	// re-bootstrap scenario.
	if _, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Create(context.Background(), &corev1Secret{
		ObjectMeta: metav1.ObjectMeta{Name: InitialAdminSecretName, Namespace: testBootstrapNS},
		Type:       corev1SecretTypeOpaque,
		Data:       map[string][]byte{"username": []byte("admin"), "password": []byte("STALE")},
	}, metav1.CreateOptions{}); err != nil {
		t.Fatalf("seed pre-existing initial-admin-secret: %v", err)
	}

	s.MaybeLogBootstrapCredential()

	got, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Get(context.Background(), InitialAdminSecretName, metav1.GetOptions{})
	if err != nil {
		t.Fatalf("expected %s to exist after rewrite, got err=%v", InitialAdminSecretName, err)
	}
	if string(got.Data["password"]) != newPass {
		t.Errorf("password not refreshed: got %q want %q", got.Data["password"], newPass)
	}
	if got.Labels["app.kubernetes.io/managed-by"] != "sharko" {
		t.Errorf("labels not refreshed on update: %+v", got.Labels)
	}
}

// --- V124-6.3 / BUG-023: DeleteInitialAdminSecret ----------------------------

func TestDeleteInitialAdminSecret_DeletesWhenPresent(t *testing.T) {
	s := newBootstrapStore(t, nil)

	// Pre-create the secret.
	if _, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Create(context.Background(), &corev1Secret{
		ObjectMeta: metav1.ObjectMeta{Name: InitialAdminSecretName, Namespace: testBootstrapNS},
		Type:       corev1SecretTypeOpaque,
		Data:       map[string][]byte{"username": []byte("admin"), "password": []byte("p")},
	}, metav1.CreateOptions{}); err != nil {
		t.Fatalf("seed initial-admin-secret: %v", err)
	}

	if err := s.DeleteInitialAdminSecret(context.Background()); err != nil {
		t.Fatalf("DeleteInitialAdminSecret: %v", err)
	}
	_, err := s.clientset.CoreV1().Secrets(testBootstrapNS).Get(context.Background(), InitialAdminSecretName, metav1.GetOptions{})
	if !apierrorsIsNotFound(err) {
		t.Fatalf("expected %s to be deleted, got err=%v", InitialAdminSecretName, err)
	}
}

func TestDeleteInitialAdminSecret_IdempotentOnMissing(t *testing.T) {
	// The reset-admin flow calls DeleteInitialAdminSecret unconditionally;
	// if the operator opted out (writeInitialSecret=false) or already
	// deleted it manually, the function must NOT error.
	s := newBootstrapStore(t, nil)

	if err := s.DeleteInitialAdminSecret(context.Background()); err != nil {
		t.Fatalf("DeleteInitialAdminSecret should be a no-op when missing, got: %v", err)
	}
}

func TestDeleteInitialAdminSecret_LocalModeIsNoOp(t *testing.T) {
	s := &Store{
		mode:       ModeLocal,
		users:      make(map[string]*UserAccount),
		passHash:   make(map[string]string),
		userTokens: make(map[string]string),
		tokens:     make(map[string]*APIToken),
	}
	if err := s.DeleteInitialAdminSecret(context.Background()); err != nil {
		t.Fatalf("DeleteInitialAdminSecret in local mode should not error: %v", err)
	}
}

// --- V124-6.3 / BUG-023: env toggle parsing ----------------------------------

func TestWriteInitialAdminSecretEnabled(t *testing.T) {
	// Default (unset) → true
	t.Setenv(EnvWriteInitialAdminSecret, "")
	if !writeInitialAdminSecretEnabled() {
		t.Errorf("default (unset) should enable initial-admin-secret writing")
	}
	// Explicit true → true
	t.Setenv(EnvWriteInitialAdminSecret, "true")
	if !writeInitialAdminSecretEnabled() {
		t.Errorf(`"true" should enable`)
	}
	// "false" → disabled
	t.Setenv(EnvWriteInitialAdminSecret, "false")
	if writeInitialAdminSecretEnabled() {
		t.Errorf(`"false" should disable`)
	}
	// "0" → disabled
	t.Setenv(EnvWriteInitialAdminSecret, "0")
	if writeInitialAdminSecretEnabled() {
		t.Errorf(`"0" should disable`)
	}
	// "no" → disabled
	t.Setenv(EnvWriteInitialAdminSecret, "no")
	if writeInitialAdminSecretEnabled() {
		t.Errorf(`"no" should disable`)
	}
	// Mixed-case false → disabled
	t.Setenv(EnvWriteInitialAdminSecret, "FALSE")
	if writeInitialAdminSecretEnabled() {
		t.Errorf(`"FALSE" should disable (case-insensitive)`)
	}
}
