// Command gen-engine-version reads charts/sharko-engine/Chart.yaml and emits
// a tiny generated Go file, internal/engineversion/generated.go, that lets
// the Sharko server know its own bundled engine chart version without
// reading a chart file off disk at runtime.
//
// Why this exists (v4 Wave 1 Story 2.5): the engine pin-bump check compares
// "what engine chart is pinned in the user's repo" (read from
// sharko-engine.yaml via the Git provider) against "what engine chart
// ships with THIS Sharko binary". The second number has to come from
// somewhere that cannot drift from charts/sharko-engine/Chart.yaml — the
// actual chart this binary's release pipeline packages, pushes, and signs
// (Story 2.4).
//
// Two ways to get there were considered:
//
//  1. go:embed charts/sharko-engine/Chart.yaml directly from a package
//     under internal/. Rejected: Go's embed package refuses `..` path
//     elements, and charts/ is not a subdirectory of any internal/ package
//     — the exact limitation internal/schema/embed.go already documents
//     for why docs/schemas/ is mirrored into internal/schema/ instead of
//     embedded directly.
//  2. A tiny code generator + a committed generated file + a CI diff gate.
//     This is the LEAST-MAGIC option available given (1) is closed off: it
//     reuses the exact pattern already proven twice in this repo
//     (cmd/schema-gen, cmd/gen-provider-types) rather than inventing a
//     third mechanism. Chosen.
//
// Usage:
//
//	go run ./cmd/gen-engine-version
//
// or via the Makefile:
//
//	make generate-engine-version
//
// CI's "Engine Version Up To Date" job (.github/workflows/ci.yml) re-runs
// this and fails the build on any diff — same shape as "Schemas Up To
// Date" and "Provider Types Up To Date".
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// chartYAMLPath is hard-coded (no CLI flag) for the same reason
// cmd/schema-gen's output dirs are hard-coded: it is part of the public
// contract between this generator, the CI gate, and the generated file's
// own doc comment. relative to the repository root, which is the expected
// CWD for `go run ./cmd/gen-engine-version` / `make generate-engine-version`.
const chartYAMLPath = "charts/sharko-engine/Chart.yaml"

// outputPath is the single generated file. Unlike the schema generator
// there is no second "human-facing" copy to keep in step — the engine
// chart version has exactly one consumer (the pin-bump check), which is a
// Go package, so one file is the whole contract.
const outputPath = "internal/engineversion/generated.go"

// chartMeta holds the two Chart.yaml fields this generator cares about.
// Deliberately minimal — everything else in Chart.yaml (description,
// keywords, annotations, ...) is irrelevant to the pin-bump check.
type chartMeta struct {
	Name    string `yaml:"name"`
	Version string `yaml:"version"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-engine-version: "+err.Error())
		os.Exit(1)
	}
}

func run() error {
	raw, err := os.ReadFile(chartYAMLPath)
	if err != nil {
		return fmt.Errorf("reading %s: %w", chartYAMLPath, err)
	}

	var meta chartMeta
	if err := yaml.Unmarshal(raw, &meta); err != nil {
		return fmt.Errorf("parsing %s: %w", chartYAMLPath, err)
	}
	if meta.Name == "" {
		return fmt.Errorf("%s: missing required field %q", chartYAMLPath, "name")
	}
	if meta.Version == "" {
		return fmt.Errorf("%s: missing required field %q", chartYAMLPath, "version")
	}

	out := renderGoFile(meta)

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o750); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}
	if err := os.WriteFile(outputPath, []byte(out), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", outputPath, err)
	}

	fmt.Printf("gen-engine-version: wrote %s (chart=%s version=%s)\n", outputPath, meta.Name, meta.Version)
	return nil
}

// renderGoFile produces the exact byte content of the generated file.
// Deterministic — same input always produces the same output — which is
// what makes the CI diff gate meaningful.
func renderGoFile(meta chartMeta) string {
	return fmt.Sprintf(`// Code generated by cmd/gen-engine-version. DO NOT EDIT.
// Source: %s (name + version fields).
// Run 'go run ./cmd/gen-engine-version' or 'make generate-engine-version' to
// refresh after bumping the engine chart's version. CI's "Engine Version Up
// To Date" job fails the build on any diff.
package engineversion

// BundledChartName is the sharko-engine chart's name, as declared in its
// own Chart.yaml. Used to locate the engine chart's source block inside a
// user's sharko-engine.yaml (the source with a matching 'chart:'
// field is the engine pin; the second source in that file, the git values
// ref, has no 'chart:' field at all — see
// docs/design/2026-07-30-v4-data-file-format.md section 2.5).
const BundledChartName = %q

// BundledVersion is the sharko-engine chart version bundled with THIS
// build of the Sharko server — i.e. the version Story 2.4's release
// pipeline packages, pushes to the OCI registry, and cosign-signs
// alongside this binary. The engine pin-bump check compares a repo's
// pinned sharko-engine.yaml targetRevision against this constant.
const BundledVersion = %q
`, chartYAMLPath, meta.Name, meta.Version)
}
